import {chromium} from '@playwright/test';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import assert from 'node:assert/strict';
const out=resolve(process.env.ECLIPSE_PUBLIC_URL?'test-results/eclipse-public':'test-results/eclipse');await mkdir(out,{recursive:true});
const root=resolve('dist/eclipse'),errors=[],warnings=[];const results={checks:[],screenshots:[],commit:process.env.ECLIPSE_HEAD_SHA||process.env.GITHUB_SHA,publicUrl:process.env.ECLIPSE_PUBLIC_URL||null};let server,currentPage;
const types={'.html':'text/html','.js':'text/javascript','.json':'application/json','.css':'text/css','.glb':'model/gltf-binary','.gltf':'model/gltf+json','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml'};
if(!process.env.ECLIPSE_PUBLIC_URL){server=createServer(async(req,res)=>{try{let name=decodeURIComponent(new URL(req.url,'http://localhost').pathname);if(name.endsWith('/'))name+='index.html';const path=resolve(root,'.'+name);if(!path.startsWith(root+'/'))throw Error('Invalid path');res.setHeader('Content-Type',types[extname(path)]||'application/octet-stream');res.end(await readFile(path));}catch{res.writeHead(404);res.end('not found');}});await new Promise(r=>server.listen(8087,'127.0.0.1',r));}
const base=process.env.ECLIPSE_PUBLIC_URL||'http://127.0.0.1:8087/';
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--enable-webgl','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
const snapshot=page=>page.evaluate(()=>window.__ECLIPSE__?.snapshot());
const shot=async(page,name)=>{await page.screenshot({path:resolve(out,name+'.png'),timeout:90000,animations:'disabled'});results.screenshots.push(name+'.png');};
function track(page){page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());if(m.type()==='warning'&&/PropertyBinding|No target node/.test(m.text()))warnings.push(m.text());});}
async function ready(page){await page.goto(base+'?test=1',{waitUntil:'networkidle',timeout:180000});await page.waitForFunction(()=>window.__ECLIPSE__?.snapshot().loaded===window.__ECLIPSE__?.assetManifest.length,null,{timeout:180000});assert.equal(await page.locator('#fatal').isVisible(),false);}
async function live(page){for(let i=0;i<40;i++){await page.waitForTimeout(1000);const s=await snapshot(page);assert.equal(s.hidden,false);assert.equal(s.state,'playing');if(s.time>6)return s;}throw Error('Real-time battle did not advance six seconds');}
try{
 const c=await browser.newContext({viewport:{width:1440,height:900},deviceScaleFactor:1}),p=await c.newPage();currentPage=p;track(p);await ready(p);await p.waitForTimeout(1000);await shot(p,'desktop-title');
 results.assets=await p.evaluate(()=>{const t=window.__ECLIPSE_TEST__,a=t.world.assets,allowed=new Set();for(const m of a.models.values())m.scene.traverse(o=>{if(o.isMesh)allowed.add(o.geometry);});const unverified=[];t.world.scene.traverse(o=>{if(o.isMesh&&!allowed.has(o.geometry))unverified.push(o.name);});return {manifest:a.manifest.map(m=>({id:m.id,author:m.author,role:m.role,source:m.source})),unverified,heroSource:t.game.hero.assetId,heroClip:t.game.hero.sourceAnimation};});
 assert.equal(results.assets.manifest.length,22);assert.deepEqual(results.assets.unverified,[]);assert.equal(results.assets.heroSource,'Ranger');results.checks.push('22 fresh third-party assets loaded; every rendered mesh has an original artist geometry');
 const audit=await p.evaluate(async()=>{const r=await fetch('./models/exclusion-audit.json');if(!r.ok)throw Error('Audit unavailable');return r.json();});assert.deepEqual(audit.collisions,[]);assert.equal(audit.generatedModels,0);assert.equal(audit.geometryRewrites,0);results.audit={snapshots:Object.entries(audit.excludedSnapshots).map(([ref,d])=>({ref,commit:d.commit,modelCount:d.models.length})),collisions:audit.collisions};
 results.animation=await p.evaluate(()=>{const h=window.__ECLIPSE_TEST__.game.hero;const pose=()=>{let a=[];h.model.traverse(n=>{if(n.isBone)a.push(...n.quaternion.toArray());});return a;};h.play('1H_Melee_Attack_Chop',{once:true,duration:1});h.mixer.update(.1);const a=pose();h.mixer.update(.27);const b=pose();const delta=a.reduce((s,n,i)=>s+Math.abs(n-b[i]),0);h.idle();return {boneCount:a.length/4,delta,clip:h.sourceAnimation};});assert.ok(results.animation.boneCount>40);assert.ok(results.animation.delta>.1,'artist animation must move actual ranger bones');results.checks.push('artist sword animation moves the ranger skeleton, not just its root');
 await p.locator('#start-button').click();results.early=await live(p);assert.ok(results.early.enemies>0);await shot(p,'desktop-battle');
 await p.locator('#auto-button').click();const before=await snapshot(p);await p.keyboard.down('d');try{await p.waitForFunction(t=>window.__ECLIPSE__.snapshot().time>=t+1.5,before.time,{timeout:90000});}finally{await p.keyboard.up('d');}const after=await snapshot(p);assert.ok(Math.hypot(after.hero.x-before.hero.x,after.hero.z-before.hero.z)>.5);await p.locator('#auto-button').click();results.checks.push('manual WASD movement responds during combat');
 await p.locator('[data-action=pause]').click();const t=(await snapshot(p)).time;await p.waitForTimeout(500);assert.equal((await snapshot(p)).time,t);assert.equal((await snapshot(p)).audio,'suspended');await shot(p,'desktop-pause');await p.locator('[data-action=resume]').click();results.checks.push('pause freezes simulation and audio; resume works');
 await p.evaluate(()=>{window.__ECLIPSE_TEST__.stopRender();window.__ECLIPSE_TEST__.sound.suspend();window.__ECLIPSE_TEST__.game.start();});results.simulation=[];
 for(let i=0;i<26;i++){const s=await p.evaluate(()=>window.__ECLIPSE_TEST__.step(15));results.simulation.push({state:s.state,wave:s.wave,kills:s.kills,hp:s.hp});if(s.wave===5&&s.state==='playing'&&!results.bossCaptured){await shot(p,'desktop-boss');results.bossCaptured=true;}if(s.state==='result')break;}
 results.final=await snapshot(p);await shot(p,'desktop-result');assert.equal(results.final.state,'result');assert.equal(results.final.win,true);assert.equal(results.final.kills,73);results.checks.push('default autonomous five-wave run defeats the final boss and reaches victory');
 // Dedicated visual inspection: the real hero, original outfit, sword and native animation.
 await p.evaluate(()=>{const t=window.__ECLIPSE_TEST__;t.game.start();t.game.hero.play('1H_Melee_Attack_Chop',{once:true,duration:1});t.game.hero.mixer.update(.36);t.world.camera.zoom=2.2;t.world.camera.updateProjectionMatrix();t.world.lastRender=0;t.world.render();});await shot(p,'hero-detail');await c.close();
 const mc=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true}),m=await mc.newPage();currentPage=m;track(m);await ready(m);await shot(m,'mobile-title');await m.locator('#start-button').tap();results.mobile=await live(m);await shot(m,'mobile-battle');assert.equal(await m.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await m.locator('[data-skill="2"]').isVisible(),true);assert.equal(results.mobile.quality,'low');
 await m.locator('[data-action=pause]').tap();await m.locator('#pause-screen [data-action=settings]').tap();await m.locator('#quality-setting').selectOption('high');await m.locator('[data-action=close-settings]').tap();await m.locator('[data-action=resume]').tap();await m.waitForTimeout(500);results.checks.push('390px touch layout, visible skills, quality settings and no horizontal overflow');await mc.close();assert.deepEqual(errors,[]);assert.deepEqual(warnings,[]);results.checks.push('no runtime errors or animation-binding warnings');results.success=true;
}catch(e){results.success=false;results.failure=String(e);console.error(e);try{results.failureState=await snapshot(currentPage);await shot(currentPage,'failure');}catch(captureError){results.captureError=String(captureError);}process.exitCode=1;}finally{results.errors=errors;results.bindingWarnings=warnings;await writeFile(resolve(out,'results.json'),JSON.stringify(results,null,2));console.log('ECLIPSE_BROWSER_RESULT',JSON.stringify(results));await browser.close();server?.close();}
