"""Real Chromium/WebGL interaction checks. Fixture/clock/camera setup is explicit.
No scene, shaders, materials, NPCs or renderer features are disabled for testing.
"""
from pathlib import Path
from playwright.sync_api import sync_playwright
import json, time, os, traceback
ROOT=Path(__file__).resolve().parents[1]
RESULTS=[]; ERRORS=[]
REPORTS=ROOT.parents[1]/'test-results/village'
REPORTS.mkdir(parents=True,exist_ok=True)
URL=os.environ.get('VILLAGE_URL','http://127.0.0.1:5174/')
if not (REPORTS/'settled-village.json').is_file():
 raise SystemExit('Run node apps/village/tests/progression.mjs from the repository first')
def record(name,condition,detail=None):
 row={'name':name,'pass':bool(condition)}
 if detail is not None: row['detail']=detail
 RESULTS.append(row);print(('PASS ' if condition else 'FAIL ')+name, detail or '',flush=True)
 if not condition: raise AssertionError(name+': '+str(detail))
def ready(p):
 p.goto(URL,wait_until='domcontentloaded')
 p.wait_for_function('window.village && document.getElementById("loading").hidden',timeout=90000)
 metadata=p.locator('#game').evaluate('(canvas)=>({...canvas.dataset})')
 record('integrated canvas identity and actual renderer are ready', metadata.get('renderer')=='ready' and metadata.get('app')=='village' and metadata.get('gameWorld')=='hoshitsugi.life-and-guard.v5' and metadata.get('world')=='village.foundation.v1' and bool(metadata.get('commit')), metadata)
 record('shared emblem was loaded',p.locator('#emblem').evaluate('(img)=>img.complete&&img.naturalWidth>0'))
 p.evaluate('village.world.state.settings.speed=0; village.view.lastInteraction=performance.now();')
 p.wait_for_timeout(350)
def shot(p,name):
 p.wait_for_timeout(600);p.screenshot(path=str(REPORTS/name))
def close_dialog(p):
 if p.locator('#dialog').evaluate('(e)=>e.open'): p.locator('.dialogClose').click()
def clear_ui(p):
 close_dialog(p)
 p.evaluate('village.cancelPlacement(); document.getElementById("closeDrawer").click(); document.getElementById("deselect").click(); village.activity();')
 if p.locator('#leaveRoom').is_visible():p.locator('#leaveRoom').click()
def focus(p,x,z,span=55):
 p.evaluate('([x,z,span])=>{let v=village.view;v.cameraGoal=null;v.target.set(x,0,z);v.span=span;v.lastInteraction=performance.now();v.updateCamera();}',[x,z,span]);p.wait_for_timeout(120)
def point(p,x,z,y=0):return p.evaluate('([x,y,z])=>village.view.project(x,y,z)',[x,y,z])
def tap_ground(p,x,z,touch=False):
 q=point(p,x,z)
 if touch:p.touchscreen.tap(q['x'],q['y'])
 else:p.mouse.click(q['x'],q['y'])
 p.wait_for_timeout(200)
def click_object(p,id,touch=False):
 # Search visible surface pixels of the actual mesh, excluding NPC hit areas.
 q=p.evaluate('''id=>{const v=village.view,o=village.world.objects.find(o=>o.id===id)||village.world.list(v.roomId).find(o=>o.id===id);let x=o.x,z=o.z;if(v.roomId&&!village.world.object(id)){let h=village.world.object(v.roomId);x=h.x+o.x*Math.cos(h.rot)+o.z*Math.sin(h.rot);z=h.z-o.x*Math.sin(h.rot)+o.z*Math.cos(h.rot);}for(let h of [2,1,3,4,0]){let p=v.project(x,h,z);for(let d of [0,8,16,24,32])for(let a of [0,1.5,3,4.5]){let sx=p.x+Math.cos(a)*d,sy=p.y+Math.sin(a)*d;if(sx<22||sx>innerWidth-22||sy<130||sy>innerHeight-240)continue;if(v.pick(sx,sy)===id&&!v.pickPerson(sx,sy))return {x:sx,y:sy};}}return null;}''',id)
 if not q:raise AssertionError('No unobscured mesh surface found for '+id)
 if touch:p.touchscreen.tap(q['x'],q['y'])
 else:p.mouse.click(q['x'],q['y'])
 p.wait_for_timeout(200)
def choose(p,kind,cat,touch=False):
 if not p.locator('#drawer').is_visible():p.locator('#build').click()
 p.locator(f'[data-category="{cat}"]').click()
 p.locator(f'[data-kind="{kind}"]').click()
 p.wait_for_timeout(150)
def export_current(p,destination):
 clear_ui(p);p.locator('#build').click();p.locator('#more').click()
 with p.expect_download() as info:p.locator('#exportSave').click()
 d=info.value;d.save_as(str(destination));return json.loads(destination.read_text())
def load_fixture(p,file):
 clear_ui(p)
 p.locator('#importFile').set_input_files(str(file))
 p.wait_for_function('village.world.people.length>6',timeout=60000)
 p.evaluate('village.world.state.settings.speed=0; village.view.lastInteraction=performance.now();')
 p.wait_for_timeout(500)
def desktop(p):
 ready(p)
 record('desktop: genuine WebGL renderer boots v5',p.evaluate('village.version===5&&!!village.view.renderer.getContext()'))
 record('desktop: initial mayor/guard/fire layout and actual actors',p.evaluate('village.world.objects.length===3&&village.world.people.length===2&&village.view.actorNodes.size>=7'))
 record('desktop: only one permanent primary action, no observation mode',p.locator('#build').is_visible() and p.locator('#observe').count()==0 and not p.locator('#drawer').is_visible())
 record('desktop: initial tutorial recommends the empty tent',p.locator('#tutorialText').inner_text()=='空きテントをひとつ')
 record('desktop: idle stats initially hidden',not p.locator('#idleStatus').evaluate('(e)=>e.classList.contains("visible")'))
 yaw=p.evaluate('village.view.yaw');p.wait_for_timeout(10000)
 record('desktop: stats fade in after a real idle wait',p.locator('#idleStatus').evaluate('(e)=>e.classList.contains("visible")&&Number(getComputedStyle(e).opacity)>.6'))
 record('desktop: slow orbit continues even with world clock paused',p.evaluate('village.view.yaw')>yaw+.01)
 record('desktop: tiltshift remains active',p.evaluate('village.view.blurMaterial.uniforms.strength.value>0&&village.view.rt.width>0'))
 shot(p,'01_initial_idle.png')
 p.locator('#build').click()
 record('desktop: any interaction dismisses idle information',not p.locator('#idleStatus').evaluate('(e)=>e.classList.contains("visible")'))
 p.locator('[data-category="仕事"]').click()
 record('desktop: locked content is absent, not greyed out',p.locator('[data-kind="smith"]').count()==0 and p.locator('[data-kind="carpenter"]').count()==0 and p.locator('[data-category="守り"]').count()==0)
 p.locator('#closeDrawer').click();p.locator('#tutorialAction').click()
 record('desktop: tutorial opens recommended catalog with badge',p.locator('[data-kind="tent"]').evaluate('(e)=>e.classList.contains("recommended")'))
 p.locator('[data-kind="tent"]').click();focus(p,-22,12,48);tap_ground(p,-22,12)
 tent=p.evaluate('village.world.objects.find(o=>o.kind==="tent").id')
 record('desktop: tap builds a real empty tent',p.evaluate('id=>!!village.world.object(id)',tent))
 p.locator('#enter').click()
 record('desktop: seamless roof cut retains the same village',p.evaluate('id=>village.view.roomId===id&&village.view.objects.children.length===village.world.objects.length',tent))
 focus(p,-22,12,18)
 choose(p,'plant','家具');tap_ground(p,-24,9)
 record('desktop: room furniture is placed in the selected home',p.evaluate('id=>village.world.object(id).room.length===1',tent))
 shot(p,'02_seamless_starter.png')
 p.locator('#leaveRoom').click();focus(p,-22,12,46);click_object(p,tent);p.locator('#details').click();p.locator('#delete').click()
 record('desktop: deletion confirmation tells the furniture count', '1個' in p.locator('#dialogContent').inner_text())
 p.locator('#confirmDelete').click()
 record('desktop: confirmed deletion removes the home',p.evaluate('id=>!village.world.object(id)',tent))
 p.locator('#build').click();p.locator('#undo').click()
 record('desktop: undo restores the same ID and interior',p.evaluate('id=>village.world.object(id)?.room.length===1',tent))
 choose(p,'logging','仕事');focus(p,30,-80,52);tap_ground(p,30,-80)
 record('desktop: unsuitable forest placement is rejected with explanation',p.evaluate('!village.world.objects.some(o=>o.kind==="logging")') and '林' in p.locator('#toastText').inner_text())
 record('desktop: required terrain is actually highlighted',p.evaluate('village.view.hintGroup.children.length>0'))
 focus(p,-32,-25,50);tap_ground(p,-32,-25)
 record('desktop: forestry can be placed beside actual forest',p.evaluate('village.world.objects.some(o=>o.kind==="logging")'))
 # A controlled resource injection isolates acquisition-driven UI behavior.
 p.evaluate('village.world.gain("wood",90);village.world.gain("stone",90);village.world.gain("clay",90);village.world.gain("plank",90);');clear_ui(p)
 p.locator('#build').click();p.locator('[data-category="仕事"]').click()
 record('desktop: first acquisition reveals the carpenter',p.locator('[data-kind="carpenter"]').count()==1)
 p.locator('[data-category="守り"]').click()
 record('desktop: guard facilities appear on resource discovery',p.locator('[data-kind="guardpost"]').count()==1 and p.locator('[data-kind="watchtower"]').count()==1)
 clear_ui(p);choose(p,'home','住まい');p.locator('[data-material="stone"]').click()
 record('desktop: material choice displays actual stone recipe','石 23' in p.locator('#placementCost').inner_text())
 focus(p,32,24,52);tap_ground(p,32,24)
 home=p.evaluate('village.world.objects.find(o=>o.kind==="home").id');before=p.evaluate('village.world.state.stock.stone')
 p.evaluate('village.sim.construction(80)')
 record('desktop: stone structure consumes stone and retains chosen material',p.evaluate('([id,before])=>village.world.object(id).material==="stone"&&village.world.object(id).phase==="built"&&village.world.state.stock.stone===before-23',[home,before]))
 p.wait_for_timeout(300);clear_ui(p);focus(p,32,24,48);click_object(p,home);p.locator('#details').click();p.locator('#upgrade').click()
 record('desktop: upgrade starts through facility detail action',p.evaluate('id=>!!village.world.object(id).upgrade',home))
 p.evaluate('village.sim.construction(46)');p.wait_for_function("id=>village.world.object(id).level===2&&village.view.buildingCache.has('home:stone:2')",arg=home,timeout=20000)
 record('desktop: completed upgrade changes capacity and rendered geometry key',p.evaluate('id=>village.world.object(id).level===2&&village.view.buildingCache.has("home:stone:2")',home))
 # Select the avatar from its rendered screen position, not its detail API.
 clear_ui(p);m=p.evaluate('village.world.people.find(p=>p.role==="mayor")');focus(p,m['x'],m['z'],35)
 q=point(p,m['x'],m['z'],1.2);p.mouse.click(q['x'],q['y'])
 record('desktop: tapping mayor opens personal details',p.locator('#dialog').evaluate('(e)=>e.open') and 'あなたの分身' in p.locator('#dialogContent').inner_text())
 shot(p,'03_mayor_detail.png');p.locator('#followPerson').click()
 record('desktop: personal detail can follow the actual actor',p.evaluate('village.view.followId==="mayor-npc"'))
 focus(p,0,0,55);before=point(p,5,8);p.mouse.move(700,420);p.mouse.down();p.mouse.move(780,450,steps=8);p.mouse.up();after=point(p,5,8)
 record('desktop: scenery follows the drag direction',after['x']>before['x']+65 and after['y']>before['y']+20,{'dx':after['x']-before['x'],'dy':after['y']-before['y']})
 record('desktop: dragging cancels personal camera following',p.evaluate('village.view.followId===null'))
 clear_ui(p);focus(p,-10,-44,55);p.locator('#build').click();p.locator('[data-category="仕事"]').click();card=p.locator('[data-kind="wheat"]');box=card.bounding_box();q=point(p,-10,-44)
 p.mouse.move(box['x']+box['width']/2,box['y']+box['height']/2);p.mouse.down();p.wait_for_timeout(350);p.mouse.move(q['x'],q['y'],steps=10);p.mouse.up();p.wait_for_timeout(400)
 record('desktop: real catalog drag-and-drop places a field',p.evaluate('village.world.objects.some(o=>o.kind==="wheat")'))
 state=export_current(p,REPORTS/'ui-export.json')
 record('desktop: browser downloads valid save JSON',state['version']==5 and any(o['kind']=='home' for o in state['objects']))
 close_dialog(p);clear_ui(p)
 if p.url.startswith('http'):
  p.evaluate('village.save()');p.reload(wait_until='domcontentloaded');p.wait_for_function('window.village',timeout=90000);p.evaluate('village.world.state.settings.speed=0')
  record('desktop: localStorage survives a real reload',p.evaluate('village.world.objects.some(o=>o.kind==="home"&&o.material==="stone")'))
 load_fixture(p,REPORTS/'settled-village.json')
 record('desktop: long-running village imports through file input',p.evaluate('village.world.people.length>=15&&village.world.state.stats.furnished>0'))
 record('desktop: wildlife actors and working trail texture remain present',p.evaluate('village.world.state.wildlife.length>=5&&Object.values(village.world.state.traffic).some(n=>n>1.1)'))
 # Stage a real new manor using accumulated stocks from the simulated settlement.
 r=p.evaluate('''()=>{const w=village.world;for(let z of [7,75,-22])for(let x of [-66,-80,60]){const r=w.add('clanManor',x,z,0,null,{material:'earth'});if(r.ok){village.sim.construction(100);for(let t=0;t<1200&&r.object.phase!=='built';t++)village.sim.update(1);return {id:r.object.id,x:r.object.x,z:r.object.z,phase:r.object.phase};}}return {error:'No manor site'};}''')
 record('desktop: dedicated manor can be built in established village',r.get('phase')=='built',r)
 clear_ui(p);p.locator('#build').click();p.locator('#more').click();p.locator('summary').click();p.locator('#demoPlayer').click();p.wait_for_timeout(300)
 record('desktop: local clan demonstration is explicitly marked as a demo',p.evaluate('village.world.people.some(p=>p.source==="local-player-demo")'))
 guest=p.evaluate('village.world.people.find(p=>p.source==="local-player-demo")');focus(p,guest['x'],guest['z'],34);q=point(p,guest['x'],guest['z'],1.2);p.mouse.click(q['x'],q['y'])
 record('desktop: tap clan resident exposes clan and demo status','星渡りの一族' in p.locator('#dialogContent').inner_text() and 'デモ' in p.locator('#dialogContent').inner_text());shot(p,'04_clan_detail.png')
 clear_ui(p);focus(p,-6,6,140)
 p.evaluate('village.world.state.time=15;village.world.state.clock=Math.floor(village.world.state.clock)+15/24;village.ui.lastActivity=performance.now()-15000;village.updateIdle();');p.wait_for_timeout(4000)
 shot(p,'05_developed_village.png')
 # Show a furnished home at its actual location; use public UI to enter.
 furnished=p.evaluate('village.world.objects.find(o=>o.room?.length>3&&!o.kind.includes("mayor"))')
 clear_ui(p);focus(p,furnished['x'],furnished['z'],42);click_object(p,furnished['id']);p.locator('#enter').click();focus(p,furnished['x'],furnished['z'],23);shot(p,'06_resident_interior.png')
 record('desktop: NPC-bought furniture survives seamless roof cut',p.evaluate('village.world.object(village.view.roomId).room.some(f=>f.ownerId)'))
 clear_ui(p);focus(p,0,0,100)
 p.evaluate('village.sim.startRaid();village.activity();village.ui.lastActivity=performance.now()-15000;village.updateIdle()');p.wait_for_timeout(500)
 record('desktop: regular warning is reflected in idle status','魔王軍' in p.locator('#idleMood').inner_text())
 p.evaluate('for(let i=0;i<46;i++)village.sim.update(1)');p.wait_for_timeout(500)
 record('desktop: timed warning leads to rendered AI attackers',p.evaluate('village.sim.raid?.phase==="active"&&[...village.view.actorNodes.keys()].some(k=>k.startsWith("raid-"))'))
 shot(p,'07_raid.png')
 p.evaluate('for(let i=0;i<120;i++)village.sim.update(1)');p.wait_for_timeout(400)
 record('desktop: guards resolve the raid and restore ordinary life',p.evaluate('!village.sim.raid&&village.world.state.defense.nextRaid>village.world.state.clock'))
 clear_ui(p);p.locator('#build').click();p.locator('#more').click()
 with p.expect_download() as info:p.locator('#photo').click()
 info.value.save_as(str(REPORTS/'photo-export.png'))
 record('desktop: photo export is a real PNG image',(REPORTS/'photo-export.png').read_bytes()[:8]==b'\x89PNG\r\n\x1a\n')
 p.locator('#journal').click();record('desktop: life journal records actual simulation events',p.locator('.journalEntry').count()>0)
 shot(p,'08_life_journal.png')

def mobile(p):
 ready(p)
 record('mobile: portrait layout has no horizontal overflow',p.evaluate('document.documentElement.scrollWidth<=innerWidth'))
 record('mobile: initial tutorial badge and single build entry fit',p.locator('#tutorial').bounding_box()['width']<412 and p.locator('#build').is_visible())
 p.evaluate('village.ui.lastActivity=performance.now()-15000;village.updateIdle()');p.wait_for_timeout(1800);shot(p,'09_mobile_idle.png')
 record('mobile: compact idle status fits in portrait',p.locator('#idleStatus').bounding_box()['x']+p.locator('#idleStatus').bounding_box()['width']<=412)
 choose(p,'tent','住まい');focus(p,-22,12,38);tap_ground(p,-22,12,touch=True)
 tent=p.evaluate('village.world.objects.find(o=>o.kind==="tent").id')
 record('mobile: touch placement creates the tent',bool(tent))
 p.locator('#enter').tap();focus(p,-22,12,15);choose(p,'chair','家具');tap_ground(p,-24,9,touch=True)
 record('mobile: empty-tent interior editing uses touch',p.evaluate('id=>village.world.object(id).room.length===1',tent))
 p.locator('#leaveRoom').tap();clear_ui(p);focus(p,0,0,40)
 g=p.evaluate('village.world.people.find(p=>p.id==="guard-npc")');focus(p,g['x'],g['z'],24);q=point(p,g['x'],g['z'],1.2);p.touchscreen.tap(q['x'],q['y'])
 record('mobile: dedicated guard can be tapped for details','専属護衛' in p.locator('#dialogContent').inner_text() and 'アルド' in p.locator('#dialogContent').inner_text());shot(p,'10_mobile_guard.png')
 clear_ui(p);focus(p,0,0,40);before=point(p,5,8);cdp=p.context.new_cdp_session(p)
 def touch(typ,pts):cdp.send('Input.dispatchTouchEvent',{'type':typ,'touchPoints':[{'x':x,'y':y,'id':i+1} for i,(x,y) in enumerate(pts)]})
 touch('touchStart',[(200,460)])
 for i in range(1,7):touch('touchMove',[(200+10*i,460+3*i)]);p.wait_for_timeout(25)
 touch('touchEnd',[]);after=point(p,5,8)
 record('mobile: native one-finger drag moves scenery with the finger',after['x']>before['x']+40 and after['y']>before['y']+8,{'dx':after['x']-before['x'],'dy':after['y']-before['y']})
 span=p.evaluate('village.view.span');touch('touchStart',[(150,430),(260,430)])
 for i in range(1,8):touch('touchMove',[(150-i*5,430),(260+i*5,430)]);p.wait_for_timeout(30)
 touch('touchEnd',[])
 record('mobile: native two-finger pinch zoom works',p.evaluate('village.view.span')<span*.9)
 p.locator('#build').tap();p.locator('[data-category="仕事"]').tap();record('mobile: unacquired facilities remain absent',p.locator('[data-kind="smith"]').count()==0);shot(p,'11_mobile_catalog.png')
 clear_ui(p);p.locator('#dismissTutorial').tap();p.wait_for_timeout(400)
 record('mobile: initial guidance can be dismissed persistently',p.evaluate('village.world.state.tutorial.dismissed') and not p.locator('#tutorial').is_visible())
 load_fixture(p,REPORTS/'settled-village.json');focus(p,0,0,130)
 p.evaluate('village.world.state.clock=Math.floor(village.world.state.clock)+.60;village.world.state.time=14.4;village.ui.lastActivity=performance.now()-15000;village.updateIdle();');p.wait_for_timeout(4200);shot(p,'12_mobile_developed.png')
 record('mobile: developed village has live actors and no overflow',p.evaluate('village.view.actorNodes.size>=village.world.people.length&&document.documentElement.scrollWidth<=innerWidth'))
 clear_ui(p);p.locator('#build').tap();p.locator('[data-category="守り"]').tap();record('mobile: guard catalog appears after actual imported discoveries',p.locator('[data-kind="watchtower"]').count()==1)
 # Test small landscape layout without adding a separate toolbar.
 clear_ui(p);p.set_viewport_size({'width':915,'height':412});p.wait_for_timeout(400);p.locator('#build').tap();p.locator('[data-category="仕事"]').tap();shot(p,'13_mobile_landscape.png')
 record('mobile: landscape catalog remains on-screen and scrollable',p.locator('#drawer').bounding_box()['x']>=0 and p.locator('#drawer').bounding_box()['y']>=0 and p.evaluate('document.documentElement.scrollWidth<=innerWidth'))

try:
 with sync_playwright() as pw:
  browser=pw.chromium.launch(executable_path=os.environ.get('CHROMIUM_EXECUTABLE') or None,headless=os.environ.get('HEADED')!='1',args=['--no-sandbox','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'])
  for name,fn,kwargs in [('desktop',desktop,{'viewport':{'width':1280,'height':850},'device_scale_factor':1}),('mobile',mobile,{'viewport':{'width':412,'height':915},'device_scale_factor':1,'is_mobile':True,'has_touch':True})]:
   context=browser.new_context(**kwargs);p=context.new_page();p.set_default_timeout(20000)
   p.on('pageerror',lambda e:ERRORS.append(str(e)))
   try:fn(p)
   except Exception as e:
    ERRORS.append(name+': '+str(e));traceback.print_exc();shot(p,name+'_failure.png')
   context.close()
  record('runtime: no JavaScript exceptions across both screen sizes',not ERRORS,ERRORS)
  browser.close()
except Exception as e:
 ERRORS.append('runner: '+str(e))
 print('RUN END:',e,flush=True)
finally:
 out={'execution_origin':URL,'engine':'repository dependency resolved by Vite; not the handoff vendor','environment':'Chromium + ANGLE SwiftShader; actual WebGL scene, native URL and localStorage; explicit clock/camera/settlement fixtures','results':RESULTS,'errors':ERRORS,'passed':sum(x['pass'] for x in RESULTS),'total':len(RESULTS)}
 (REPORTS/'browser-results.json').write_text(json.dumps(out,ensure_ascii=False,indent=2))
 print('RESULT',out['passed'],'/',out['total'],'errors',len(ERRORS),flush=True)
 if ERRORS or out['passed']!=out['total']:raise SystemExit(1)
