import test from 'node:test';
import assert from 'node:assert/strict';
import {World,initial,defs,BUILDINGS,GARDEN,unlocked,recipe,materialOptions,capacityOf,jobsOf,ready,entry,localToWorld,worldToLocal,validate,DAYS_YEAR,RESOURCE_NAMES} from '../src/game/core.js';
import {Simulation,Navigation} from '../src/game/simulation.js';
import {PlayerResidenceBridge} from '../src/game/bridge.js';
import {terrainError,naturalTrees,TERRAIN_SITES} from '../src/game/terrain.js';
const give=(w,n=500)=>{for(const k of Object.keys(RESOURCE_NAMES))w.gain(k,n);};
function add(w,k,x,z,room=null,material='base'){const r=w.add(k,x,z,0,room,{material});assert.equal(r.error,undefined,`${k} at ${x},${z}: ${r.error}`);return r.object;}
function build(w,k,x,z,material='base'){const o=add(w,k,x,z,null,material);o.phase='built';w.changed();return o;}
function advance(s,n){for(let t=0;t<n;t+=.5)s.update(Math.min(.5,n-t));}
function baseVillage(){const w=new World();add(w,'tent',-22,12);add(w,'tent',25,13);add(w,'tent',-24,34);add(w,'logging',-32,-25);add(w,'wheat',-10,-44);return{w,s:new Simulation(w)};}
function civilian(w,home,x,z){const p={id:'test-person-'+w.state.nextId++,name:'住人テスト',source:'local-npc',role:'resident',homeId:home.id,x,z,health:100,hunger:85,happiness:80,skill:0,purse:0,task:'idle',timer:0,path:[],seed:1,memories:[]};w.people.push(p);return p;}

test('founding village contains mayor tent, campfire and a separate guard home',()=>{const w=new World();assert.deepEqual(w.objects.map(o=>o.kind),['mayor','campfire','guardhome']);assert.equal(w.people.length,2);assert.equal(w.people[0].role,'mayor');assert.equal(w.people[1].role,'guard');assert.notEqual(w.people[0].homeId,w.people[1].homeId);});
test('beginning homes and campfire cannot be accidentally deleted',()=>{const w=new World();for(const o of w.objects)assert.ok(w.remove(o.id).error);});
test('all eight original free facilities still have no material cost',()=>{for(const k of ['tent','storage','logging','quarry','carpenter','wheat','clay','market'])assert.deepEqual(defs[k].cost,{});});
test('unseen resource facilities are absent, not disabled cards',()=>{const w=new World();for(const k of ['smith','clanManor','jeweler','guardpost','carpenter'])assert.equal(unlocked(w.state,k),false);});
test('first wood acquisition reveals carpenter, guardpost and wooden props',()=>{const w=new World();w.gain('wood',1);for(const k of ['carpenter','guardpost','fence','home'])assert.ok(unlocked(w.state,k),k);});
test('unlock knowledge remains when stock is consumed',()=>{const w=new World();w.gain('wood',5);w.spend({wood:5});assert.equal(w.state.stock.wood,0);assert.ok(unlocked(w.state,'guardpost'));const v=new World(JSON.parse(w.export()));assert.ok(unlocked(v.state,'guardpost'));});
test('unlocked recipes reject an unknown resource key and overspending',()=>{const w=new World();assert.equal(w.spend({gold:1}),false);w.gain('wood',3);assert.equal(w.spend({wood:4}),false);assert.equal(w.state.stock.wood,3);});
test('logging requires real trees shared with renderer',()=>{assert.ok(naturalTrees().length>100);assert.equal(terrainError('forest',-32,-25),null);assert.match(terrainError('forest',30,-80),/林/);});
test('player planting creates a legal forestry site',()=>{const w=new World();give(w);add(w,'tree',-200,0);assert.equal(terrainError('forest',-190,0,w.objects),null);});
test('quarry requires visible rock deposit',()=>{const w=new World();assert.match(w.add('quarry',-20,70).error,/露岩/);assert.equal(w.canPlace('quarry',36,-62),null);});
test('clay requires wetlands or river bank',()=>{const w=new World();assert.match(w.add('clay',20,-70).error,/湿/);assert.equal(w.canPlace('clay',-44,28),null);});
test('wheat requires fertile soil',()=>{const w=new World();assert.match(w.add('wheat',-160,0).error,/肥沃/);assert.equal(w.canPlace('wheat',-10,-44),null);});
test('fishpond requires nearby water, harbor requires coast',()=>{const w=new World();give(w);assert.match(w.add('fishpond',-180,0).error,/水/);const h=add(w,'harbor',205,0);assert.equal(h.x,166);});
test('terrain rules are rechecked when moving a facility',()=>{const w=new World(),o=add(w,'logging',-32,-25);assert.ok(w.move(o.id,30,-80,0).error);assert.equal(o.x,-32);});
test('placement is continuous rather than snapping to the hidden navigation cells',()=>{const w=new World(),o=add(w,'tent',-22.137,12.731);assert.equal(o.x,-22.137);assert.equal(o.z,12.731);});
test('water and building overlap are rejected',()=>{const w=new World();assert.ok(w.add('tent',205,0).error);assert.ok(w.add('tent',-7,-5).error);});
test('housing cannot grow infinitely before support exists',()=>{const w=new World();let placed=0,stopped=false;for(let i=0;i<12;i++){const r=w.add('tent',-150+i*13,100);if(r.error){assert.match(r.error,/余裕/);stopped=true;break;}placed++;}assert.ok(stopped);assert.ok(placed>0&&placed<12);});
test('food alone cannot grow population beyond the starter defense limit',()=>{const{w,s}=baseVillage();advance(s,240);assert.ok(w.people.length<=6);assert.equal(w.population().safety,6);});
test('staffed defense increases settlement population limit',()=>{const{w,s}=baseVillage();advance(s,140);give(w);build(w,'guardpost',-8,23);s.assignJobs();assert.ok(w.people.some(p=>p.jobId&&p.role==='guard'));assert.ok(w.population().limit>6);});
test('removing defense never evicts existing villagers',()=>{const{w,s}=baseVillage();advance(s,90);give(w);const post=build(w,'guardpost',-8,23);s.assignJobs();const n=w.people.length;assert.ok(w.remove(post.id).ok);assert.equal(w.people.length,n);});
test('remote unguarded housing does not attract immigrants',()=>{const w=new World();add(w,'tent',-200,0);const s=new Simulation(w);advance(s,120);assert.equal(w.people.length,2);});
test('decorative defenses help only near homes, with a gentle cap',()=>{const w=new World();give(w);const before=w.population().safety;for(let i=0;i<8;i++)add(w,'fence',-200+i*5,100);assert.equal(w.population().safety,before);for(let i=0;i<4;i++)add(w,'wall',-17+i*5,19);assert.ok(w.population().safety>before);});
test('early tutorial recommends empty tent then forestry; can be dismissed persistently',()=>{const w=new World();assert.equal(w.tutorialStep().kind,'tent');add(w,'tent',-22,12);assert.equal(w.tutorialStep().kind,'logging');w.state.tutorial.dismissed=true;assert.equal(new World(JSON.parse(w.export())).tutorialStep(),null);});
test('completed tutorial does not appear again after reload',()=>{const w=new World();give(w);for(const t of [{k:'tent',x:-22,z:12},{k:'logging',x:-32,z:-25},{k:'wheat',x:-10,z:-44},{k:'carpenter',x:14,z:-30},{k:'guardpost',x:-8,z:23}])build(w,t.k,t.x,t.z);assert.equal(w.tutorialStep(),null);assert.equal(new World(JSON.parse(w.export())).tutorialStep(),null);});
test('material recipes reflect actual resource types and counts',()=>{const w=new World();w.gain('stone',30);w.gain('wood',5);const options=materialOptions(w.state,'home');assert.ok(options.find(v=>v.id==='stone').affordable);assert.equal(options.some(v=>v.id==='earth'),false);assert.deepEqual(recipe('home','stone'),{stone:23,wood:5});});
test('stone-built home consumes stone once and preserves its material',()=>{const w=new World();w.gain('stone',23);w.gain('wood',5);const o=add(w,'home',25,13,null,'stone'),s=new Simulation(w);assert.equal(o.material,'stone');s.construction(1);assert.equal(o.phase,'building');assert.equal(w.state.stock.stone,0);s.construction(100);assert.equal(o.phase,'built');assert.equal(w.state.stock.stone,0);});
test('insufficient resources leave a blueprint waiting, not negative stock',()=>{const w=new World();w.gain('wood',1);const h=add(w,'home',25,13),s=new Simulation(w);s.construction(10);assert.equal(h.phase,'planned');assert.equal(w.state.stock.wood,1);});
test('upgrade payment is atomic and cannot be paid twice',()=>{const w=new World();give(w);const o=build(w,'home',25,13),cost=w.upgradeCost(o),before=w.state.stock.wood;assert.ok(w.upgrade(o.id).ok);assert.equal(w.state.stock.wood,before-cost.wood);assert.ok(w.upgrade(o.id).error);assert.equal(w.state.stock.wood,before-cost.wood);});
test('upgrade enhances capacity and preserves resident furniture and building id',()=>{const w=new World();give(w);const o=build(w,'home',25,13);add(w,'plant',-3,-3,o.id);const id=o.room[0].id,s=new Simulation(w),cap=capacityOf(o);w.upgrade(o.id);s.construction(50);assert.equal(o.level,2);assert.ok(capacityOf(o)>cap);assert.equal(o.room[0].id,id);assert.equal(w.state.stats.upgrades,1);});
test('upgrade resumes after save without paying twice',()=>{const w=new World();give(w);const o=build(w,'home',25,13),s=new Simulation(w);w.upgrade(o.id);s.construction(15);const balance=w.state.stock.wood,w2=new World(JSON.parse(w.export())),s2=new Simulation(w2);s2.construction(40);assert.equal(w2.object(o.id).level,2);assert.equal(w2.state.stock.wood,balance);});
test('all facilities define a nonempty trait and productive facilities define actual yields',()=>{for(const d of BUILDINGS){assert.ok(d.trait.length>3,d.id);if(d.produce)for(const[k,n]of Object.entries(d.produce)){assert.ok(RESOURCE_NAMES[k]);assert.ok(n>0);}}});
test('mayor acts as a real worker and dedicated guard follows',()=>{const{w,s}=baseVillage();advance(s,130);const mayor=w.people.find(p=>p.role==='mayor'),guard=w.people.find(p=>p.id==='guard-npc');assert.ok(mayor.jobId);assert.ok(w.state.stats.produced>0);assert.ok(Math.hypot(guard.x-mayor.x,guard.z-mayor.z)<17);});
test('unprotected wildlife damage can down a resident',()=>{const w=new World(),home=add(w,'tent',-150,100),p=civilian(w,home,-150,110),s=new Simulation(w);s.hurt(p,110,'wildlife');assert.equal(p.health,0);assert.ok(p.downed);});
test('nearby active guard guarantees no fatal wildlife damage',()=>{const w=new World(),home=add(w,'tent',-22,12),p=civilian(w,home,1,6),s=new Simulation(w),g=w.people.find(p=>p.id==='guard-npc');g.x=0;g.z=6;g.health=80;for(let i=0;i<100;i++)s.hurt(p,1000,'wildlife');assert.ok(p.health>=25);assert.equal(p.downed,undefined);assert.ok(g.health>=40);});
test('guard physically intercepts wildlife during simulation, not only arithmetic tests',()=>{const w=new World(),s=new Simulation(w),m=w.people[0],g=w.people[1];m.x=0;m.z=6;m.task='home';m.timer=100;m.insideId=null;g.x=1;g.z=7;s.world.state.wildlife=[{id:'wild-check',species:'wolf',name:'狼',hostile:true,x:3,z:8,health:35,homeX:3,homeZ:8,damage:8,speed:2,seed:1,path:[],repath:0}];advance(s,8);assert.ok(m.health>0);assert.equal(w.state.wildlife.some(a=>a.id==='wild-check'),false);assert.ok(w.state.stats.defeated>0);});
test('unrescued regular NPC can die, while furniture and memorial remain',()=>{const w=new World(),h=add(w,'tent',-150,100),p=civilian(w,h,-150,110),s=new Simulation(w);h.room.push({id:'f991',kind:'plant',x:0,z:0,rot:0,ownerId:p.id});s.hurt(p,110,'wildlife');s.rescueAndRecovery(91);assert.equal(w.people.includes(p),false);assert.equal(h.room.length,1);assert.equal(w.state.memorial[0].name,p.name);});
test('a guard rescues a downed resident within range',()=>{const w=new World(),h=add(w,'tent',-22,12),p=civilian(w,h,1,6),s=new Simulation(w),g=w.people[1];p.health=0;p.downed={left:90,source:'monster'};g.x=0;g.z=6;s.guardStep(g,1);assert.equal(p.downed,undefined);assert.equal(w.state.stats.rescues,1);});
test('regular AI raids have a first grace period and are scheduled without a menu command',()=>{const w=new World(),s=new Simulation(w);w.state.clock=7.74;s.update(.1);assert.equal(s.raid,null);w.state.clock=7.8;s.update(.1);assert.equal(s.raid.phase,'warning');advance(s,46);assert.equal(s.raid.phase,'active');assert.equal(w.state.stats.raids,1);});
test('raid wave composition scales with current population',()=>{const s=new Simulation(new World()),a=s.raidBudget(2),b=s.raidBudget(18),c=s.raidBudget(60);assert.ok(a.count<b.count&&b.count<c.count);assert.ok(a.health<b.health&&b.damage<c.damage);assert.ok(c.count<=18);});
test('wave budget is a population snapshot, not instant reinforcement on immigration',()=>{const w=new World(),s=new Simulation(w);s.startRaid({immediate:true});const count=s.raid.monsters.length;w.people.push({...w.people[0],id:'temp'});assert.equal(s.raid.monsters.length,count);assert.equal(s.raid.popSnapshot,2);});
test('defeated wave schedules a rest period and leaves buildings intact',()=>{const w=new World(),s=new Simulation(w);s.startRaid({immediate:true});s.raid.monsters=[];const homes=w.objects.length;s.updateRaid(.1);assert.equal(s.raid,null);assert.ok(w.state.defense.nextRaid-w.state.clock>=12);assert.equal(w.objects.length,homes);});
test('raid warning phase survives save/load without duplicate wave',()=>{const w=new World(),s=new Simulation(w);s.startRaid();const id=s.raid.id,w2=new World(JSON.parse(w.export())),s2=new Simulation(w2);assert.equal(s2.raid.id,id);assert.equal(s2.startRaid(),false);});
test('local lineage demo requires a dedicated manor',()=>{const w=new World(),bridge=new PlayerResidenceBridge(w);assert.ok(bridge.upsert({id:'a',name:'旅人',clanId:'一族'},{demo:true}).error);});
test('ordinary NPCs cannot occupy a clan manor, lineage actors can',()=>{const w=new World();give(w);const h=build(w,'clanManor',-35,-68),tent=add(w,'tent',-22,12),p=civilian(w,tent,-22,20),s=new Simulation(w);assert.equal(s.availableHomes().some(o=>o.id===h.id),false);assert.ok(w.assign(p.id,h.id).error);const result=new PlayerResidenceBridge(w).upsert({id:'a',name:'旅の一族',clanId:'星の一族'},{demo:true});assert.ok(result.ok);assert.equal(result.person.homeId,h.id);assert.equal(result.person.source,'local-player-demo');});
test('lineage residence upsert is idempotent and capacity checked',()=>{const w=new World();give(w);build(w,'clanManor',-35,-68);const b=new PlayerResidenceBridge(w);for(let i=0;i<4;i++)assert.ok(b.upsert({id:String(i),name:'一族'+i,clanId:'a'},{demo:true}).ok);assert.ok(b.upsert({id:'0',name:'改名',clanId:'a'},{demo:true}).ok);assert.equal(w.people.length,6);assert.ok(b.upsert({id:'fifth',name:'五人目',clanId:'a'},{demo:true}).error);});
test('all completed unoccupied buildings allow seamless-room furniture records',()=>{const w=new World();give(w);for(const [k,x,z]of [['home',25,13],['school',-40,-65],['guardpost',-8,23]]){const h=build(w,k,x,z);assert.ok(add(w,'plant',-2,-3,h.id));}});
test('delete and undo restore the same building and the same furnishings',()=>{const w=new World(),h=add(w,'tent',-22,12);const f=add(w,'plant',-2,-3,h.id);assert.ok(w.remove(h.id).ok);assert.ok(w.undo().ok);assert.equal(w.object(h.id).room[0].id,f.id);});
test('undo does not rewind simulation or remove newly bought furniture on moved buildings',()=>{const w=new World(),h=add(w,'tent',-22,12);w.move(h.id,-35,12,0);h.room.push({id:'f991',kind:'plant',x:0,z:0,rot:0});w.state.clock=22.7;assert.ok(w.undo().ok);assert.equal(h.room.length,1);assert.equal(w.state.clock,22.7);});
test('paid decorative placement supports resource-safe undo and redo',()=>{const w=new World();w.gain('wood',4);add(w,'fence',0,25);assert.equal(w.state.stock.wood,3);assert.ok(w.undo().ok);assert.equal(w.state.stock.wood,4);assert.ok(w.redo().ok);assert.equal(w.state.stock.wood,3);});
test('rotated seamless housing round-trips local coordinates',()=>{const h={x:33.2,z:-44.1,rot:1.23},q=localToWorld(h,1.25,-4.2),r=worldToLocal(h,q.x,q.z);assert.ok(Math.abs(r.x-1.25)<1e-10);assert.ok(Math.abs(r.z+4.2)<1e-10);});
test('movement creates actual trails that fade when unused',()=>{const{w,s}=baseVillage();advance(s,180);assert.ok(Object.values(w.state.traffic).some(v=>v>1.1));w.state.traffic['100,100']=15;advance(s,65);assert.ok(w.state.traffic['100,100']<15);});
test('navigation routes around fences and cannot walk through water',()=>{const w=new World();w.gain('wood',3);add(w,'fence',0,25);const nav=new Navigation(w);const route=nav.route({x:0,z:18},{x:0,z:32});assert.ok(route);assert.ok(route.every(p=>!nav.blocked(Math.round(p.x/2),Math.round(p.z/2))));assert.ok(nav.blocked(105,0));});
test('quiet observation generates memories and short life events without user clicks',()=>{const{w,s}=baseVillage();advance(s,150);assert.ok(w.state.stats.moments>0);assert.ok(w.state.moments.length>0);assert.ok(w.people.some(p=>p.memories.length));});
test('first-acquired resources and resident life survive JSON round trip',()=>{const{w,s}=baseVillage();advance(s,160);const w2=new World(JSON.parse(w.export()));assert.equal(w2.people.length,w.people.length);assert.deepEqual(w2.state.stock,w.state.stock);assert.deepEqual(w2.state.known,w.state.known);assert.deepEqual(w2.state.traffic,w.state.traffic);});
test('v4 migration preserves player-built houses, stock and trails while adding mayor and guard',()=>{const x=initial();x.version=4;x.objects=x.objects.filter(o=>o.kind!=='guardhome');x.people=[];x.stock={wood:12,stone:3,plank:5,clay:1,food:2};x.objects.push({id:'b8',kind:'tent',x:25,z:13,rot:0,phase:'built',room:[]});x.traffic={'1,2':5};const w=new World(x);assert.equal(w.state.version,5);assert.ok(w.object('b8'));assert.equal(w.people.length,2);assert.equal(w.state.stock.wood,12);assert.equal(w.state.traffic['1,2'],5);});
test('malformed saves are rejected without mutating the current village',()=>{const w=new World();for(const mutate of [s=>s.version=3,s=>s.clock=-1,s=>s.stock.wood=null,s=>s.objects[0].kind='evil',s=>s.people[0].homeId='missing',s=>s.defense.nextRaid=null]){const s=initial();mutate(s);assert.ok(w.load(JSON.stringify(s)).error);assert.equal(w.people.length,2);}});
test('five-year ship boundary still brings supplies once and departs',()=>{const w=new World();give(w);build(w,'harbor',166,0);const s=new Simulation(w);w.state.clock=60-.005;s.update(1);assert.equal(w.state.voyage.phase,'arriving');advance(s,19);assert.equal(w.state.voyage.phase,'docked');advance(s,26);assert.equal(w.state.voyage.phase,'departing');advance(s,20);assert.equal(w.state.stats.ships,1);});

test('enclosed non-housing facilities support material variants and keep functional resources',()=>{const w=new World();give(w);assert.ok(materialOptions(w.state,'clinic').some(v=>v.id==='earth'));assert.equal(recipe('weapons','stone').metal,8);assert.equal(recipe('clanManor','timber').cloth,8);});
test('autonomous workers change jobs when unattended resources block construction',()=>{const {w,s}=baseVillage();advance(s,220);const q=add(w,'quarry',30,-60);add(w,'guardpost',-8,23);advance(s,90);add(w,'home',42,15);advance(s,800);assert.ok(w.state.known.includes('stone'));assert.ok(w.state.stats.produced>0);assert.ok(w.people.some(p=>p.memories.some(m=>/石切場/.test(m.text)))||w.state.stock.stone>0);});
test('dedicated guard eats without dropping defense or becoming an inert prop',()=>{const w=new World(),s=new Simulation(w),g=w.people.find(p=>p.id==='guard-npc');g.hunger=36;w.gain('food',2);s.guardStep(g,.25);assert.ok(g.hunger>50);assert.equal(w.state.stock.food,1);assert.match(g.status,/食事/);assert.equal(w.population().safety,6);});
test('guard lethal hits never create negative health in saved threat snapshots',()=>{const w=new World(),s=new Simulation(w),g=w.people.find(p=>p.id==='guard-npc');s.startRaid({immediate:true});const a=s.raid.monsters[0];a.x=g.x+1;a.z=g.z;a.health=.1;s.guardStep(g,1);assert.ok(a.health>=0);assert.doesNotThrow(()=>new World(JSON.parse(w.export())));});

test('save reload clears transient guard-snack and worker-assignment timers',()=>{const w=new World();const g=w.people.find(p=>p.id==='guard-npc');g.snackUntil=9000;w.people[0].jobAssignedAt=9000;const v=new World(JSON.parse(w.export())),s=new Simulation(v);const guard=v.people.find(p=>p.id==='guard-npc');assert.equal(guard.snackUntil,undefined);assert.equal(v.people[0].jobAssignedAt,undefined);s.guardStep(guard,1);assert.match(guard.status,/見守る/);});
test('broken injury timers and malformed raid budgets are safely rejected',()=>{const w=new World(),s=new Simulation(w);const data=initial();data.people[0].downed={source:'wildlife',left:null};assert.ok(w.load(JSON.stringify(data)).error);s.startRaid();const raid=JSON.parse(w.export());delete raid.defense.raid.budget;assert.ok(w.load(JSON.stringify(raid)).error);});

test('evacuated villagers remain indoors until the active raid ends',()=>{const w=new World(),s=new Simulation(w),p=w.people.find(p=>p.role==='mayor');s.startRaid({immediate:true});p.insideId=p.homeId;p.targetId=p.homeId;p.task='home';for(let i=0;i<10;i++)s.finish(p);assert.equal(p.insideId,p.homeId);assert.equal(p.task,'home');s.raid=null;s.finish(p);assert.equal(p.insideId,null);});
