/** Browser audio adapter: deliberately silent until a user gesture. No audio downloads. */
export class TitleAudio {
 constructor(){this.context=null;this.active=false;this.timer=null;this.index=0;this.sources=new Set();}
 async setActive(active){if(active&&this.active&&this.timer)return;this.active=active;if(!active){this.stop();return;}const C=window.AudioContext||window.webkitAudioContext;if(!C){this.active=false;return;}try{if(!this.context){this.context=new C();this.gain=this.context.createGain();this.gain.gain.value=0;this.gain.connect(this.context.destination);}await this.context.resume();if(!this.active||this.timer)return;this.gain.gain.cancelScheduledValues(this.context.currentTime);this.gain.gain.setTargetAtTime(.14,this.context.currentTime,.5);this.next=this.context.currentTime+.1;if(!this.timer){this.schedule();this.timer=setInterval(()=>this.schedule(),180);}}catch{this.active=false;this.stop();}}
 note(hz,when,length=.9,volume=.18){if(!this.context||!this.active)return;const c=this.context,o=c.createOscillator(),g=c.createGain();o.type='sine';o.frequency.value=hz;g.gain.setValueAtTime(0,when);g.gain.linearRampToValueAtTime(volume,when+.015);g.gain.exponentialRampToValueAtTime(.0001,when+length);o.connect(g);g.connect(this.gain);this.sources.add(o);o.onended=()=>{this.sources.delete(o);o.disconnect();g.disconnect();};o.start(when);o.stop(when+length+.02);}
 schedule(){if(!this.active||!this.context)return;const melody=[62,69,74,76,74,69,67,69,62,67,71,74,71,67,64,69];while(this.next<this.context.currentTime+.65){const m=melody[this.index%melody.length];this.note(440*Math.pow(2,(m-69)/12),this.next,1.9,.20);if(this.index%4===0)this.note(146.832,this.next,2.7,.10);this.next+=.64;this.index++;}}
 chime(){if(!this.active||!this.context)return;const now=this.context.currentTime;[440,660,880].forEach((hz,i)=>this.note(hz,now+i*.09,1,.22));}
 stop(){if(this.timer){clearInterval(this.timer);this.timer=null;}if(this.context){this.gain?.gain.cancelScheduledValues(this.context.currentTime);this.gain?.gain.setTargetAtTime(0,this.context.currentTime,.1);for(const o of this.sources){try{o.stop(this.context.currentTime+.3);}catch{}}}}
 dispose(){this.active=false;this.stop();this.context?.close().catch(()=>{});}
}
