const freeze=Object.freeze;
export const BODY_PARTS=freeze(['head','torso','leftArm','rightArm','leftLeg','rightLeg']);
const clamp=(n,a=0,b=1)=>Math.min(b,Math.max(a,Number(n)||0));
export function createJohakyuDomainActor({id,side='enemy',hp=100,maxHp=hp,stamina=100,staminaCap=100,body}={}){
 if(typeof id!=='string'||!id)throw new TypeError('actor id required');
 return {id,side,hp:Math.max(0,Number(hp)||0),maxHp:Math.max(1,Number(maxHp)||1),stamina:clamp(stamina,0,staminaCap),staminaCap:Math.max(1,Number(staminaCap)||100),body:Object.fromEntries(BODY_PARTS.map(p=>[p,clamp(body?.[p]??0)])),dead:false,incapacitated:false};
}
export function createJohakyuBattle({battleId='battle',actors=[],seed=1}={}){const map=new Map(actors.map(a=>[a.id,createJohakyuDomainActor(a)]));if(map.size!==actors.length)throw Error('duplicate actor id');return {battleId,seed:seed>>>0,actors:map,applied:new Set(),result:null,revision:0};}
export function spendJohakyuStamina(actor,amount){amount=Math.max(0,Number(amount)||0);if(actor.stamina<amount)return false;actor.stamina-=amount;actor.staminaCap=Math.max(22,actor.staminaCap-amount*.08);return true;}
export function recoverJohakyuStamina(actor,seconds,{resting=false}={}){seconds=clamp(seconds,0,30);actor.stamina=Math.min(actor.staminaCap,actor.stamina+(resting?32:14)*seconds);if(resting)actor.staminaCap=Math.min(100,actor.staminaCap+8*seconds);return actor.stamina;}
export function applyJohakyuImpactOnce(battle,{eventId,attackId,sourceId,targetId,damage,part='torso',phase='ha'}={}){
 if(!eventId||!attackId||battle.applied.has(eventId))return {applied:false,duplicate:true};
 const source=battle.actors.get(sourceId),target=battle.actors.get(targetId);if(!source||!target||source===target)throw Error('invalid impact actors');if(!BODY_PARTS.includes(part))throw Error('invalid body part');if(target.dead)return {applied:false,dead:true};
 battle.applied.add(eventId);const dealt=Math.min(target.hp,Math.max(0,Number(damage)||0));target.hp-=dealt;const scale=phase==='kyu'?1.38:phase==='ha'?1.14:.95;
 target.body[part]=clamp(target.body[part]+Math.min(.24,(dealt/Math.max(1,target.maxHp))*1.08*scale+.004));target.incapacitated=target.body.head>=.86||target.body.torso>=.91||(target.body.leftLeg>=.82&&target.body.rightLeg>=.82);target.dead=target.hp<=0||target.body.head>=.97||target.body.torso>=.99;battle.revision++;if(target.dead)target.hp=0;
 const living=[...battle.actors.values()].filter(a=>!a.dead),sides=new Set(living.map(a=>a.side));if(sides.size<=1)battle.result=freeze({winner:[...sides][0]??null,reason:'incapacitated'});
 return {applied:true,dealt,part,severity:target.body[part],incapacitated:target.incapacitated,dead:target.dead,result:battle.result};
}
export function selectReachableTarget({source,candidates,reach=2.35,blocked=()=>false}={}){if(!source)return null;return candidates.filter(a=>a&&a.id!==source.id&&!a.dead).map(a=>({...a,distance:Math.hypot((a.x??0)-(source.x??0),(a.z??0)-(source.z??0))})).filter(a=>a.distance<=reach&&!blocked(source,a)).sort((a,b)=>a.distance-b.distance||String(a.id).localeCompare(String(b.id)))[0]??null;}
export function validateTechniqueSelection({catalog,known=[],techniqueId,weapon,ageYears=100}={}){if(!catalog?.[techniqueId])return {ok:false,reason:'catalog'};if(!known.includes(techniqueId)&&!techniqueId.startsWith('basic.'))return {ok:false,reason:'unlearned'};if(ageYears<7&&weapon!=='fist')return {ok:false,reason:'age'};return {ok:true,technique:catalog[techniqueId]};}
export function johakyuLifeGate(state,{action='combat'}={}){if(!state||state.ended)return {ok:false,reason:'ended'};if(action==='equip'&&Number(state.ageYears)<7)return {ok:false,reason:'age'};if(action==='depart'&&Number(state.ageYears)<15)return {ok:false,reason:'age'};if(action==='combat'&&state.zone!=='frontier')return {ok:false,reason:'zone'};return {ok:true};}
export function createJohakyuCheckpoint({battle,lifeId,ageSeconds,encounterId,rewardsApplied=[]}={}){return freeze({version:1,lifeId,ageSeconds:Number(ageSeconds)||0,encounterId,battleId:battle.battleId,revision:battle.revision,result:battle.result,actors:[...battle.actors.values()].map(a=>structuredClone(a)),applied:[...battle.applied],rewardsApplied:[...new Set(rewardsApplied)]});}
export function restoreJohakyuCheckpoint(raw){if(!raw||raw.version!==1||!Array.isArray(raw.actors)||!Array.isArray(raw.applied))throw Error('invalid johakyu checkpoint');const battle=createJohakyuBattle({battleId:raw.battleId,actors:raw.actors});battle.applied=new Set(raw.applied);battle.result=raw.result??null;battle.revision=Number(raw.revision)||0;return {battle,rewardsApplied:new Set(raw.rewardsApplied||[]),lifeId:raw.lifeId,ageSeconds:Number(raw.ageSeconds)||0,encounterId:raw.encounterId};}
export function applyRewardOnce(restored,rewardId,apply){if(restored.rewardsApplied.has(rewardId))return false;apply();restored.rewardsApplied.add(rewardId);return true;}
export function johakyuAcceptanceSnapshot({battle,renderer='nocturne',clockOwner='rinne-domain'}={}){return freeze({schemaVersion:1,renderer,clockOwner,battleId:battle.battleId,revision:battle.revision,result:battle.result,actors:[...battle.actors.values()].map(a=>freeze({id:a.id,side:a.side,hp:a.hp,stamina:a.stamina,dead:a.dead,incapacitated:a.incapacitated,body:freeze({...a.body})}))});}
