import * as THREE from 'three';
import { findNode } from './assets.js';
import { clamp } from '../domain/rules.js';
const reusableColor=new THREE.Color();
const heroAnimation={Idle:'Sword_Idle',Idle_Combat:'Sword_Idle',Running_A:'Run_Stylized',Running_B:'Run_Sprint',Walking_A:'Walking_Slow',Cheer:'BackFlip',Death_A:'Dodge_Left',Spawn_Ground_Skeletons:'Jump_Landing',Spellcast_Raise:'SwordKick',Spellcast_Long:'Attack_Dash',Spellcast_Shoot:'Sword_Attack','1H_Melee_Attack_Slice_Horizontal':'Sword_Attack','1H_Melee_Attack_Slice_Diagonal':'Sword_Attack','1H_Melee_Attack_Chop':'SwordSlash_Heavy','2H_Melee_Attack_Spin':'Sword_Attack'};
const monsterAnimation={Idle_Combat:'Idle',Running_A:'Run',Running_B:'Run',Walking_A:'Walk',Spawn_Ground_Skeletons:'Jump_Land',Death_C_Skeletons:'Death',Death_A:'Death',Cheer:'Wave',Spellcast_Shoot:'Punch',Spellcast_Raise:'Jump',Spellcast_Long:'Punch','1H_Melee_Attack_Chop':'Punch','1H_Melee_Attack_Slice_Diagonal':'Punch','1H_Melee_Attack_Slice_Horizontal':'Punch','2H_Melee_Attack_Spin':'Punch'};
export class Actor {
 constructor(assets,kind='hero',position={x:0,z:0}){
  this.kind=kind;this.isHero=kind==='hero';this.isBoss=kind==='boss';this.isMage=kind==='mage';this.assetId=this.isHero?'Ranger':this.isMage?'Wizard':this.isBoss?'Dragon':kind==='minion'?'Ninja':'Demon';this.model=assets.character(this.assetId);this.root=new THREE.Group();this.root.name=`actor:${this.assetId}`;this.root.add(this.model);this.root.position.set(position.x,.065,position.z);this.position=this.root.position;
  this.model.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(this.model),size=box.getSize(new THREE.Vector3());const height=this.isHero?2.45:this.isBoss?4.5:this.isMage?2.6:kind==='minion'?1.85:2.6;this.scale=height/Math.max(.001,size.y);this.model.scale.multiplyScalar(this.scale);this.model.position.y-=box.min.y*this.scale;
  this.radius=this.isBoss?1.1:this.isHero?.58:.52;this.hp=100;this.maxHp=100;this.alive=true;this.deadTime=0;this.cooldown=.4;this.busy=0;this.hitAt=0;this.pending=null;this.spawnTime=0;this.slow=0;this.flash=0;this.velocity=new THREE.Vector3();this.materials=[];this.heading=0;this.targetHeading=0;this.animation='';this.extraMaterials=[];
  this.model.traverse(o=>{if(!o.isMesh)return;o.castShadow=true;o.receiveShadow=true;o.frustumCulled=false;const cm=original=>{const m=original.clone();if(!this.isHero){m.roughness=.78;m.color.multiply(new THREE.Color(this.isBoss?'#c8a4bc':this.isMage?'#a7bedd':'#c4cbc5'));}if(m.emissive)this.materials.push({m,emissive:m.emissive.clone(),intensity:m.emissiveIntensity??1});return m;};o.material=Array.isArray(o.material)?o.material.map(cm):cm(o.material);});
  if(this.isHero){const hand=findNode(this.model,'hand_r');if(!hand)throw Error('Ranger right hand is missing');const sword=assets.weapon();sword.updateMatrixWorld(true);const size=new THREE.Box3().setFromObject(sword).getSize(new THREE.Vector3());sword.scale.multiplyScalar(1.3/(Math.max(size.x,size.y,size.z)*this.scale));sword.rotation.set(Math.PI/2,0,Math.PI);hand.add(sword);}
  this.mixer=new THREE.AnimationMixer(this.model);this.actions=new Map();this.clips=new Map(assets.model(this.isHero?'RangerAnimations':this.assetId).animations.map(clip=>[clip.name,clip]));this.play(this.isHero?'Idle':'Idle_Combat');this.mixer.update(.001);
 }
 play(name,{once=false,duration=null,fade=.12}={}){let mapped=(this.isHero?heroAnimation:monsterAnimation)[name]||name;if(!this.clips.has(mapped)&&/Attack|Melee|Spellcast/.test(name))mapped=this.isHero?'Sword_Attack':'Punch';const clip=this.clips.get(mapped)||this.clips.get(this.isHero?'Sword_Idle':'Idle');if(!clip)return;if(this.animation===name&&!once)return;let next=this.actions.get(clip.name);if(!next){next=this.mixer.clipAction(clip);this.actions.set(clip.name,next);}const previous=this.current;this.animation=name;this.sourceAnimation=clip.name;this.current=next;next.reset().setEffectiveWeight(1).setEffectiveTimeScale(duration?clip.duration/duration:1);next.setLoop(once?THREE.LoopOnce:THREE.LoopRepeat,once?1:Infinity);next.clampWhenFinished=once;next.play();if(previous&&previous!==next)previous.crossFadeTo(next,fade,false);}
 act(name,duration,hitAt,pending){if(!this.alive)return;this.busy=duration;this.hitAt=duration-hitAt;this.pending=pending;this.play(name,{once:true,duration,fade:.07});}
 face(target){this.targetHeading=Math.atan2(target.x-this.position.x,target.z-this.position.z);}
 move(dx,dz,speed,dt){if(!this.alive||this.spawnTime>0)return;const len=Math.hypot(dx,dz);if(len<.001)return;this.targetHeading=Math.atan2(dx,dz);const slow=this.slow>0?.38:1;this.position.x=clamp(this.position.x+dx/len*speed*dt*slow,-12.8,12.8);this.position.z=clamp(this.position.z+dz/len*speed*dt*slow,-10.3,10.3);if(this.busy<=0)this.play('Running_A');}
 idle(){if(this.alive&&this.busy<=0&&this.spawnTime<=0)this.play(this.isHero?'Idle':'Idle_Combat');}
 tick(dt){this.mixer.update(dt*(this.slow>0&&!this.isHero?.6:1));this.flash=Math.max(0,this.flash-dt*5.5);this.slow=Math.max(0,this.slow-dt);for(const {m,emissive,intensity}of this.materials){m.emissive.copy(emissive);m.emissiveIntensity=intensity;if(this.flash>0){m.emissive.lerp(reusableColor.set('#fff3d2'),this.flash);m.emissiveIntensity=2.4;}else if(this.slow>0){m.emissive.lerp(reusableColor.set('#1994bf'),.28);m.emissiveIntensity=.9;}}let da=this.targetHeading-this.heading;da=Math.atan2(Math.sin(da),Math.cos(da));this.heading+=da*Math.min(1,dt*17);this.model.rotation.y=this.heading;this.position.x=clamp(this.position.x+this.velocity.x*dt,-13,13);this.position.z=clamp(this.position.z+this.velocity.z*dt,-10.5,10.5);this.velocity.multiplyScalar(Math.exp(-dt*9));if(!this.alive){this.deadTime+=dt;if(this.deadTime>1.7)this.position.y-=dt*.8;return;}this.cooldown=Math.max(0,this.cooldown-dt);this.spawnTime=Math.max(0,this.spawnTime-dt);if(this.busy>0){this.busy=Math.max(0,this.busy-dt);if(this.pending&&this.busy<=this.hitAt){const event=this.pending;this.pending=null;event();}if(this.busy===0)this.idle();}}
 die(){if(!this.alive)return;this.alive=false;this.pending=null;this.busy=0;this.velocity.multiplyScalar(.3);this.play(this.isHero?'Death_A':'Death_C_Skeletons',{once:true,duration:this.isHero?1.6:1.4,fade:.06});}
 dispose(){this.root.removeFromParent();this.mixer.stopAllAction();this.mixer.uncacheRoot(this.model);for(const {m}of this.materials)m.dispose();for(const m of this.extraMaterials)m.dispose();}
}
