import * as THREE from 'three';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
import { seededRandom } from '../domain/rules.js';
export class World {
 constructor(canvas,assets,settings){this.canvas=canvas;this.settings=settings;this.assets=assets;this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#11212c');this.scene.fog=new THREE.FogExp2('#142c37',.024);this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});const gl=this.renderer.getContext(),debug=gl.getExtension('WEBGL_debug_renderer_info');this.software=debug?/swiftshader|llvmpipe|software/i.test(gl.getParameter(debug.UNMASKED_RENDERER_WEBGL)):false;this.renderer.info.autoReset=false;this.lastRender=0;this.renderCount=0;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.04;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.camera=new THREE.OrthographicCamera(-20,20,12,-12,.1,120);this.camera.position.set(13,25,22);this.focus=new THREE.Vector3();this.camera.lookAt(this.focus);this.scene.add(new THREE.HemisphereLight('#a9c9dd','#27342e',2));const sun=new THREE.DirectionalLight('#ffe4b6',3.7);sun.position.set(-13,22,-8);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-25,right:25,top:24,bottom:-24,far:65});sun.shadow.bias=-.0003;sun.shadow.normalBias=.035;this.scene.add(sun);this.sun=sun;const rim=new THREE.DirectionalLight('#6597d3',2.2);rim.position.set(8,7,15);this.scene.add(rim);this.heroLight=new THREE.PointLight('#ffe3ae',14,9,2);this.heroLight.position.set(0,3,0);this.scene.add(this.heroLight);this.flashLight=new THREE.PointLight('#ffc875',0,15,2);this.scene.add(this.flashLight);this.lamps=[];this.firePositions=[];this.shake=0;this.shakeTime=0;this.elapsed=0;this.mode='title';this.buildEnvironment();this.composer=new EffectComposer(this.renderer);this.composer.addPass(new RenderPass(this.scene,this.camera));this.bloom=new UnrealBloomPass(new THREE.Vector2(800,600),.42,.45,1.08);this.composer.addPass(this.bloom);this.composer.addPass(new OutputPass());this.resize();}
 buildEnvironment(){const rng=seededRandom(492),batches=new Map(),prototypes=new Map();const add=(id,x,z,{height=1,width=null,depth=null,y=0,angle=0,scale=1}={})=>{if(!prototypes.has(id)){const source=this.assets.model(id).scene;source.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(source);prototypes.set(id,{source,box,size:box.getSize(new THREE.Vector3()),center:box.getCenter(new THREE.Vector3())});}const {box,size,center}=prototypes.get(id),s=height/Math.max(size.y,.001),sx=width?width/Math.max(size.x,.001):s,sz=depth?depth/Math.max(size.z,.001):s;const local=new THREE.Matrix4().makeScale(sx*scale,s*scale,sz*scale).multiply(new THREE.Matrix4().makeTranslation(-center.x,-box.min.y,-center.z));const matrix=new THREE.Matrix4().makeTranslation(x,y,z).multiply(new THREE.Matrix4().makeRotationY(angle)).multiply(local);if(!batches.has(id))batches.set(id,[]);batches.get(id).push(matrix);};
  // Ground, paving and architecture are all original downloaded models.
  add('Ground',0,0,{width:46,depth:44,height:.25,y:-.38});for(let x=-3;x<=3;x++)for(let z=-3;z<=2;z++)add('Paving',x*4,z*4+2,{width:4.02,depth:4.02,height:.14,y:-.14,angle:(x+z)%2*Math.PI});for(let i=-3;i<=3;i++)if(i!==0)add('Wall',i*4.2,-13.4,{height:4.5,width:4.3,depth:.85});add('Arch',0,-13.5,{height:6.8,width:5.8,depth:1.4});add('Steps',0,-11.8,{height:.65,width:4,depth:1.8,y:-.1});for(const x of [-12,-6,6,12]){add('Pillar',x,-11,{height:6});add('Banner',x,-10.8,{height:2.4,y:2.8});}for(const z of [-5,4,10])for(const x of [-14.5,14.5])add(z===4?'BrokenPillar':'Pillar',x,z,{height:z===4?2.7:5.3,angle:rng()*.5});for(const [x,z]of [[-11,-8],[11,-8],[-12,7],[12,7]]){add('Lantern',x,z,{height:3.8});add('Candles',x+.7,z+.4,{height:.75});this.firePositions.push({x,y:3.2,z});if(z<0){const light=new THREE.PointLight('#ffbb65',24,10,2);light.position.set(x,3.2,z);this.scene.add(light);this.lamps.push(light);}}add('Well',-10,-8,{height:2.1,angle:.5});add('Crate',11,8.5,{height:1,angle:-.2});for(let i=0;i<24;i++){const side=i%2?1:-1,x=side*(15+rng()*5),z=-13+rng()*27;add('Rock',x,z,{height:.6+rng()*1.4,angle:rng()*Math.PI*2});if(i%2===0)add('Fern',x-side,z+.4,{height:.7+rng()*.6,angle:rng()*6});}for(let i=0;i<12;i++)add('Pine',(i-5.5)*4.1,-19-rng()*4,{height:7+rng()*5,angle:rng()*6});for(const x of [-21,21])for(const z of [-8,1,10])add('Pine',x,z,{height:9+rng()*4,angle:rng()*6});for(const [id,matrices]of batches){const {source}=prototypes.get(id);source.traverse(o=>{if(!o.isMesh)return;const tint=m=>{const material=m.clone();if(!/Lantern|Candles|Banner/.test(id)){material.roughness=Math.max(material.roughness??.8,.76);material.color.multiply(new THREE.Color(/Paving|Wall|Pillar|Arch|Steps/.test(id)?'#c8d2d4':'#9ab3ad'));}return material;};const materials=Array.isArray(o.material)?o.material.map(tint):tint(o.material);const instanced=new THREE.InstancedMesh(o.geometry,materials,matrices.length);for(let i=0;i<matrices.length;i++)instanced.setMatrixAt(i,matrices[i].clone().multiply(o.matrixWorld));instanced.castShadow=!/Ground|Paving/.test(id);instanced.receiveShadow=true;instanced.computeBoundingSphere();instanced.name=`original:${id}`;instanced.userData.originalAsset=id;this.scene.add(instanced);});}}
 setQuality(value){this.settings.quality=value;this.resize();}
 resize(){const w=innerWidth,h=innerHeight;this.mobile=w<700||matchMedia('(pointer:coarse)').matches;this.low=this.settings.quality==='low'||(this.settings.quality==='auto'&&(this.mobile||this.software));const dpr=Math.min(devicePixelRatio||1,this.software?.65:this.low?1.1:1.5);this.renderer.setPixelRatio(dpr);this.renderer.setSize(w,h,false);this.composer.setPixelRatio(dpr);this.composer.setSize(w,h);const viewH=w/h<.8?24:w/h<1.2?22:19;this.camera.left=-viewH*w/h/2;this.camera.right=viewH*w/h/2;this.camera.top=viewH/2;this.camera.bottom=-viewH/2;this.camera.updateProjectionMatrix();const ss=this.software?512:this.low?1024:2048;this.sun.shadow.mapSize.set(ss,ss);if(this.sun.shadow.map){this.sun.shadow.map.dispose();this.sun.shadow.map=null;}this.bloom.enabled=!this.low;}
 impact(pos,power=1,color='#ffd289'){this.flashLight.position.copy(pos);this.flashLight.position.y=2;this.flashLight.color.set(color);this.flashLight.intensity=Math.max(this.flashLight.intensity,35*power);if(this.settings.shake){this.shake=Math.max(this.shake,power*.17);this.shakeTime=.23;}}
 update(dt,hero){this.elapsed+=dt;const title=this.mode==='title',follow=hero?.position||new THREE.Vector3(),weight=this.mobile?.9:.42;const desired=new THREE.Vector3(follow.x*weight,0,follow.z*weight+(this.mobile?1.5:0));if(title&&!this.mobile)desired.x=-3.3;this.focus.lerp(desired,1-Math.exp(-dt*3));const sway=title?Math.sin(this.elapsed*.11)*1.3:0;this.camera.position.set(this.focus.x+13+sway,this.focus.y+25,this.focus.z+22);if(this.shakeTime>0){this.shakeTime-=dt;this.camera.position.x+=(Math.random()-.5)*this.shake;this.camera.position.y+=(Math.random()-.5)*this.shake;this.shake*=Math.exp(-dt*9);}this.camera.lookAt(this.focus);this.camera.updateMatrixWorld();if(hero){this.heroLight.position.copy(hero.position);this.heroLight.position.y=3.3;}this.flashLight.intensity*=Math.exp(-dt*12);for(let i=0;i<this.lamps.length;i++)this.lamps[i].intensity=22+Math.sin(this.elapsed*5+i*7)*2+Math.sin(this.elapsed*8.1+i)*1.3;}
 render(){const now=performance.now();if(this.software&&now-this.lastRender<100)return;this.lastRender=now;this.renderCount++;this.renderer.info.reset();if(this.low)this.renderer.render(this.scene,this.camera);else this.composer.render();}
}
