import json
from pathlib import Path
from common import VERSION,digest,save_json

def create_manifest(spec,report,clips,model):
    from validation import read_export
    _,doc,get=read_export(model)
    points=[p for m in doc['meshes'] for p in get(m['primitives'][0]['attributes']['POSITION'])]
    lo=[min(p[i] for p in points) for i in range(3)];hi=[max(p[i] for p in points) for i in range(3)]
    return {'schemaVersion':'rinne.character-package/v1','id':spec['id'],'displayName':spec['displayName'],'forgeVersion':VERSION,
      'representation':'3d','reconstructionMode':spec['reconstructionMode'],'sourceViews':spec['views'],'model':{'path':'build/character.glb','sha256':report['modelSha256']},
      'skeleton':spec['rig'],'animations':[{'name':c['name'],'duration':c['duration'],'loop':c['loop'],'status':'generated'} for c in clips],
      'sockets':spec['sockets'],'scale':{'unit':'metre','height':1.6},'bounds':{'min':lo,'max':hi},
      'presentation':{'headAnchor':[0,spec['levels']['chin']*1.6,0],'bodyCenter':[(a+b)/2 for a,b in zip(lo,hi)],'focusTarget':[0,.8,0],'groundPoint':[0,0,0]},
      'reviewStatus':'review-candidate','visualApproval':'pending','productionReady':False,'provenance':spec['provenance'],'validationStatus':report['structuralStatus'],
      'validationReport':'validation-report.json','qualityRefinement':'review/quality-refinement.json','reconstructionSpec':'spec/reconstruction.json','comparisons':{v:f'review/comparisons/{v}-silhouette-overlay.png' for v in report['comparisons']}}

def register_review(root):
    entries=[];imports=[]
    for path in sorted((root/'packages/assets/characters/forge').glob('*/manifest.json')):
        m=json.loads(path.read_text());directory=path.parent
        # Transaction/recovery folders are never published as packages.
        if directory.name!=m.get('id'):continue
        if m.get('validationStatus')!='passed' or m.get('reviewStatus')!='review-candidate':continue
        if digest((directory/m['model']['path']).read_bytes())!=m['model']['sha256']:raise ValueError('Model hash mismatch while registering '+m['id'])
        i=len(entries);relative='../characters/forge/'+directory.name+'/'
        # Generated from discovered manifests. No hand-maintained imports/arrays.
        imports.append(f'import m{i} from {json.dumps(relative+"manifest.json")} with {{type:"json"}};')
        url=lambda p:'new URL('+json.dumps(relative+p)+',import.meta.url).href'
        refs=','.join(json.dumps(v)+':'+url('review/references/'+v+'.png') for v in m['sourceViews'])
        raw=','.join(json.dumps(v)+':'+url('source/'+v+'.png') for v in m['sourceViews'])
        entries.append('{manifest:m'+str(i)+',modelUrl:'+url(m['model']['path'])+',references:{'+refs+'},sourceReferences:{'+raw+'},reportUrl:'+url(m['validationReport'])+',qualityRefinementUrl:'+url(m['qualityRefinement'])+'}')
    target=root/'packages/assets/generated/create-forge-registry.js';target.parent.mkdir(parents=True,exist_ok=True)
    target.write_text('// Generated by character-forge:create; discovered packages, never edit by hand.\n'+'\n'.join(imports)+'\nexport const characterForgeCandidates=['+','.join(entries)+'];\n')
    return len(entries)
