import{createTidebreakRuntime}from'@soul/tidebreak-combat';
import{observerPresenceSnapshot}from'./presence-lod.js';
export const RAID_LEDGER_KEY='soul.village.raid-ledger.v1';
export function canonicalVillageId(world){if(!world?.id)throw Error('村IDがありません。');return String(world.id);}
const clone=value=>structuredClone(value);
const validPeer=p=>p&&['human','demon','standby'].includes(p.role)&&p.playerId&&['x','z','hp','maxhp'].every(k=>Number.isFinite(p[k]));
export class RaidHost{
 constructor({villageId,storage,now=()=>Date.now()}){this.villageId=villageId;this.storage=storage;this.now=now;this.peers=new Map();this.battle=null;this.ledger=this.read();}
 read(){try{const value=JSON.parse(this.storage.getItem(RAID_LEDGER_KEY)||'{"version":1,"visits":{}}');if(value.version!==1||!value.visits||Array.isArray(value.visits))throw Error();return value;}catch{throw Error('村の襲撃台帳を安全に読み込めません。');}}
 save(){this.storage.setItem(RAID_LEDGER_KEY,JSON.stringify(this.ledger));}
 join(peerId,message){const role=message?.app==='village'&&message?.hostEligible===true?'standby':message?.role;if(message?.type!=='join'||!['human','demon','standby'].includes(role)||!message.playerId)throw Error('参加情報が不正です。');const key=`${this.villageId}:${message.playerId}`;if(role==='demon'&&this.ledger.visits[key])return{type:'rejected',reason:'この魔物はすでにこの村へ侵入しました。再入場できません。'};if(role==='demon'){this.ledger.visits[key]={villageId:this.villageId,playerId:message.playerId,status:'entered',enteredAt:this.now()};this.save();}const hp=role==='demon'?230:role==='human'?180:1;this.peers.set(peerId,{role,playerId:message.playerId,name:String(message.name||role).slice(0,40),x:0,z:role==='demon'?8:0,yaw:0,state:role,action:null,hp,maxhp:hp});return{type:'accepted',villageId:this.villageId,player:this.peers.get(peerId)};}
 leave(peerId){this.peers.delete(peerId);if(this.battle&&(this.battle.demon===peerId||this.battle.human===peerId))this.battle=null;}
 input(peerId,message){const p=this.peers.get(peerId);if(!p||p.role==='standby'||message?.type!=='state')return;for(const key of ['x','z'])if(Number.isFinite(message[key]))p[key]=Math.max(-40,Math.min(40,message[key]));if(Number.isFinite(message.yaw))p.yaw=((message.yaw+Math.PI*3)%(Math.PI*2))-Math.PI;if(typeof message.state==='string')p.state=message.state.slice(0,32);if(typeof message.action==='string'||message.action===null)p.action=message.action===null?null:message.action.slice(0,32);}
 snapshotFor(peerId,{qualityLevel=0}={}){const observer=this.peers.get(peerId);if(!observer)return{type:'snapshot',villageId:this.villageId,players:{},battle:this.battle};const players=Object.fromEntries([...this.peers].filter(([,p])=>p.role!=='standby'));return{type:'snapshot',villageId:this.villageId,players:observerPresenceSnapshot({id:peerId,...observer},players,{qualityLevel}),battle:this.battle};}
 checkpoint(){const battle=this.battle?{demon:this.battle.demon,human:this.battle.human,time:Number(this.battle.time)||0,finished:Boolean(this.battle.finished),winner:this.battle.winner??null}:null;return{schemaVersion:1,peers:[...this.peers].map(([id,p])=>({id,...clone(p)})),battle,ledger:clone(this.ledger)};}
 restoreCheckpoint(value){if(!value||value.schemaVersion!==1||!Array.isArray(value.peers)||value.peers.length>128||!value.ledger||value.ledger.version!==1||!value.ledger.visits||Array.isArray(value.ledger.visits))throw Error('オンライン村のcheckpointが不正です。');const peers=new Map();for(const row of value.peers){if(!row?.id||peers.has(row.id)||!validPeer(row))throw Error('オンライン参加者のcheckpointが不正です。');const{id,...peer}=row;peers.set(String(id),clone(peer));}this.peers=peers;this.ledger={version:1,visits:{...this.ledger.visits,...clone(value.ledger.visits)}};this.save();this.battle=null;const b=value.battle;if(!b)return;if(!b.demon||!b.human||!Number.isFinite(b.time)||b.time<0)throw Error('戦闘checkpointが不正です。');if(b.finished){this.battle={demon:b.demon,human:b.human,time:b.time,winner:b.winner??null,finished:true};return;}const d=this.peers.get(b.demon),h=this.peers.get(b.human);if(!d||!h||d.role!=='demon'||h.role!=='human')return;const core=createTidebreakRuntime({seed:hash(`${this.villageId}:${d.playerId}:${h.playerId}`)});core.configure({weapon:'fist',enemyWeapon:'katana',hp:d.hp,maxhp:d.maxhp,enemyHp:h.hp,enemyStyle:'balanced',mindset:'balanced',positions:{hero:{x:d.x,z:d.z},enemy:{x:h.x,z:h.z}}});this.battle={demon:b.demon,human:b.human,time:b.time,core};}
 tick(dt,{observerId=null,qualityLevel=0}={}){const entries=[...this.peers];if(!this.battle){const demons=entries.filter(([,p])=>p.role==='demon'&&p.hp>0),humans=entries.filter(([,p])=>p.role==='human'&&p.hp>0);outer:for(const[di,d]of demons)for(const[hi,h]of humans)if(Math.hypot(d.x-h.x,d.z-h.z)<4){const core=createTidebreakRuntime({seed:hash(`${this.villageId}:${d.playerId}:${h.playerId}`)});core.configure({weapon:'fist',enemyWeapon:'katana',hp:d.hp,maxhp:d.maxhp,enemyHp:h.hp,enemyStyle:'balanced',mindset:'balanced',positions:{hero:{x:d.x,z:d.z},enemy:{x:h.x,z:h.z}}});this.battle={demon:di,human:hi,time:0,core};break outer;}}
  if(this.battle&&!this.battle.finished){const d=this.peers.get(this.battle.demon),h=this.peers.get(this.battle.human);if(!d||!h){this.battle=null;}else{this.battle.time+=dt;const state=this.battle.core.step(Math.min(dt,1/30));d.hp=state.hero.hp;h.hp=state.enemy.hp;d.x=state.hero.x;d.z=state.hero.z;h.x=state.enemy.x;h.z=state.enemy.z;if(state.hero.dead||state.enemy.dead){const winner=state.enemy.dead?'demon':'human',key=`${this.villageId}:${d.playerId}`;if(this.ledger.visits[key]){this.ledger.visits[key].status=winner==='demon'?'completed':'defeated';this.ledger.visits[key].finishedAt=this.now();this.save();}this.battle={demon:this.battle.demon,human:this.battle.human,time:this.battle.time,winner,finished:true};}}}
  if(observerId)return this.snapshotFor(observerId,{qualityLevel});return{type:'snapshot',villageId:this.villageId,players:Object.fromEntries(entries.filter(([,p])=>p.role!=='standby')),battle:this.battle};
 }
}
function hash(text){let h=2166136261;for(const c of text)h=Math.imul(h^c.charCodeAt(0),16777619);return h>>>0;}
