// Rendering-facing adapter. The authoritative portable implementation remains in @soul/animations.
export {
  MOTION_RUNTIME_VERSION,
  MOTION_SYNC_CONTRACT,
  MOTION_PERSONALITIES,
  resolveMotionPersonality,
  locomotionTransition,
  solveTwoBodyInteraction,
  conditionMotionProfile,
  microMotionSample,
  pairedImpactResponse,
  bodyMotionAdaptation,
  createMotionSyncFrame,
  validateMotionSyncFrame,
  reconcileMotionSync,
  createSharedMotionRuntime,
  MOTION_ORCHESTRATION_VERSION,
  MOTION_LAYER_CONTRACTS,
  compileMotionLayerPlan,
  SEMANTIC_MOTION_EVENTS,
  createSemanticMotionTimeline,
  semanticEventsBetween,
  predictMotionTrajectory,
  rankPoseCandidates,
  selectPoseCandidate,
  motionVariationProfile,
  INTERACTION_SCHEMAS,
  resolveInteractionSchema,
  weaponContactConstraint,
  ragdollBlendBridge,
  personalSpaceSteering,
  MOTION_BUDGET_TARGETS,
  createMotionProfiler,
  buildMotionReviewPlan,
  motionDebugOverlayData,
  reviewRepairRequest,
} from '@soul/animations';
