"""Materialize reviewed DCC output into the first-party origin and female record only."""
import argparse,hashlib,json,shutil,struct
from pathlib import Path
p=argparse.ArgumentParser();p.add_argument('--out',required=True);a=p.parse_args();out=Path(a.out)
load=lambda path:json.loads(Path(path).read_text())
def write(path,value):
    path=Path(path);path.parent.mkdir(parents=True,exist_ok=True);path.write_text(json.dumps(value,ensure_ascii=False,indent=2)+'\n')
def copy(src,dst):
    dst=Path(dst);dst.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(src,dst)
audit=load(out/'inspection.json');body=(out/'HeroineDawn.glb').read_bytes();assert hashlib.sha256(body).hexdigest()==audit['sha256'];assert audit['motionStreams']=='byte-for-byte unchanged' and audit['jointCount']==41 and audit['motionClips']==76
origin='https://soul-lineage-review-dev.c-okamoto.workers.dev/library/';relative=f"model/{audit['gitBlobSha']}/HeroineDawn.glb";mesh='apps/review/public/library/'+relative
source='assets/characters/heroine-dawn/source/HeroineDawn.blend';qa='docs/characters/qa/heroine-dawn-v1';provenance='apps/review/public/library/provenance/heroine-dawn-v1.json'
copy(out/'HeroineDawn.glb',mesh);copy(out/'HeroineDawn.blend',source);copy(out/'HeroineDawnPalette.png','assets/characters/heroine-dawn/source/HeroineDawnPalette.png')
for view in ['front','three-quarter','side','back','face']:copy(out/(view+'.png'),f'{qa}/dcc-{view}.png')
write(f'{qa}/dcc-audit.json',audit);original=load('apps/review/public/library/provenance/female-protagonist-rogue-v1.json')
record={**original,'id':'protagonist.villager.female.v1','path':mesh,'bytes':len(body),'byteLength':len(body),'sha256':audit['sha256'],'gitBlobSha':audit['gitBlobSha'],'modified':True,'author':'Kay Lousberg / RINNE DCC adaptation','sourcePath':original['path'],'sourceSha256':original['sha256'],'sourceGitBlobSha':original['gitBlobSha'],'sourceBytes':original['bytes'],'dccSourcePath':source,'dccSourceSha256':hashlib.sha256(Path(source).read_bytes()).hexdigest(),'authoringRecipe':['assets/characters/heroine-dawn/build.py','assets/characters/heroine-dawn/finalize.py','assets/characters/heroine-dawn/refine.py','assets/characters/heroine-dawn/dcc_glb.py'],'adaptation':'Independent rounded bob and swept fringe; continuous village pinafore, ivory collar and puff sleeves; rose bows and sash; cape, earrings and utility gear removed. Original KayKit face and limbs retained; rig/motion streams unchanged.','auditPath':f'{qa}/dcc-audit.json','runtimeOrigin':origin,'productionReady':False,'visualApproval':'pending'}
doc=json.loads(body[20:20+struct.unpack_from('<I',body,12)[0]]);record.update(triangles=audit['triangles'],title='RINNE Heroine Dawn / independent KayKit-derived heroine',conversion=record['adaptation'],meshNames=[m.get('name','') for m in doc['meshes']],nodes=[n.get('name','') for n in doc['nodes']],materials=doc['materials'],images=doc['images'],animations=[v['name'] for v in doc['animations']]);write(provenance,record)
for app in ['rinne','character-studio']:
    path=f'apps/{app}/public/simulator/assets/PROTAGONIST_VILLAGER_FEMALE_V1.asset.json';r=load(path);r.update(path=origin+relative,sha256=audit['sha256'],bytes=len(body),gitBlobSha=audit['gitBlobSha'],productionStage='PRIMARY',modelingMode='dcc-blender',sourcePath=source,referencePath=provenance)
    r['license']['surfaceAuthorship']='Kay Lousberg CC0 base; RINNE Blender hair/clothing adaptation. Original rig and all motion streams preserved.';r['source']['conversion']='Blender mesh/UV authoring with unchanged source skeleton, inverse binds and 76 animation streams.';r['source'].update(sha256=original['sha256'],gitBlobSha=original['gitBlobSha'],bytes=original['bytes']);write(path,r)
catalog=Path('packages/characters/src/reference-model-catalog.js');text=catalog.read_text();start=text.index('// The previous authored head/hair');end=text.index('validateVisualIdentity(femaleProtagonist);',start);old=text[start:end]
assert "modelingMode: 'imported-reviewed'" in old and "sourceModelId: 'kaykit.rogue.v1'" in old
new=old.replace('// The previous authored head/hair model was explicitly rejected. This role now\n// selects the unchanged official Rogue mesh, not a new procedural approximation.','// Independent heroine: actual Blender adaptation of the pinned CC0 KayKit base.\n// The rejected old procedural head is not restored; raw Rogue remains a separate model.')
new=new.replace("label: '主人公・女 / KayKit Rogue（公式CC0原形）'","label: '主人公・女 / 丸いボブ・青い村人服 PRIMARY'").replace("modelingMode: 'imported-reviewed'","modelingMode: 'dcc-blender'").replace("productionStage: 'REFERENCE'","productionStage: 'PRIMARY'")
new=new.replace("projectAssetUrl('model/c8827661105eef7b2bfbef3bc676d41a47625733/Rogue.glb')",f"projectAssetUrl('{relative}')").replace("dccSourcePath: '"+original['path']+"'","dccSourcePath: '"+source+"'").replace("referencePath: 'apps/review/public/library/provenance/female-protagonist-rogue-v1.json'","referencePath: '"+provenance+"'")
new=new.replace("design: 'protagonist-female-kaykit-rogue-original'","design: 'protagonist-female-heroine-dawn'").replace("['kaykit-rogue-original-head-body-hair-clothing']","['kaykit-face-and-limbs', 'heroine-rounded-bob-and-swept-fringe', 'ivory-collar-and-puff-sleeves', 'blue-village-pinafore', 'rose-sash-and-bows']").replace("topology: 'kaykit-original-unmodified'","topology: 'kaykit-source-derived'")
a0=new.index("  note: '");new=new[:a0]+"  note: '固定CC0 KayKitの顔・手足とRig_Mediumを保持し、Blenderで主人公専用の短い丸ボブ・流し前髪・白い襟と袖・青い村人服を実編集。ケープ・三角スカーフ・重い革小物は撤去。76クリップのmotion streamとbind情報は原本どおり。原本Rogueや破棄済みモデルへfallbackしない。実画像・実レンダー観察は記録するが、human visualApproval=pending / productionReady=falseを維持。操作・装備所有・当たり判定は変更しない。'\n};\n";catalog.write_text(text[:start]+new+text[end:])
path='packages/characters/production/protagonist-villager-female-v1.production.json';r=load(path);r.update(stage='PRIMARY',modelingMode='dcc-blender');r['source'].update(meshPath=mesh,referencePaths=['assets/characters/heroine-dawn/reference.md',provenance],dcc={'tool':'Blender','version':audit['authoringTool'],'sourcePath':source,'sourceSha256':record['dccSourceSha256']});r['source']['import']['conversion']='Actual hair/clothing/UV surface edits; original skeleton and animation streams remain byte-for-byte unchanged.'
r['evidence']={'reference':{'intentLocked':True,'views':['front','side','back','three-quarter','face'],'sourceAuditPath':provenance},'blockout':{'views':['front','side','back','three-quarter'],'proportionsReviewed':True,'silhouetteReviewed':True,'reviewEvidence':qa+'/'},'primary':{'topologyReviewed':True,'uvReviewed':True,'separateSurfaces':['skin','hair','clothing','source-kaykit-parts'],'auditPath':qa+'/dcc-audit.json','meshObjects':len(audit['meshes']),'triangles':audit['triangles'],'materials':1}};r['status']['note']='Independent heroine DCC adaptation. Repository-renderer and animation probe evidence is task-scoped. Human visual approval and physical-device performance acceptance remain pending; not RUNTIME_READY.';write(path,r)
write(out/'integration.json',{'meshPath':mesh,'assetUrl':origin+relative,'modelSha256':audit['sha256'],'sourcePath':source,'provenance':provenance,'qa':qa,'artRound':audit['round']});print(json.dumps({'materialized':mesh,'sha256':audit['sha256'],'bytes':len(body),'triangles':audit['triangles']}))
