import { ARMOR_LABELS, WEAPON_LABELS, ensureProgression } from './gameplay-world.js';
const PHASES=[['jo','序'],['ha','破'],['kyu','急']];
export function createGameplayUI(gameScreen,{stations,layout,audio}){
  const root=document.createElement('div');root.className='rinne-gameplay-upgrade';root.innerHTML=`<div class="rinne-player-strip"><span data-name>旅人</span><i></i><span data-equip>素手 · 旅装</span><span data-state>探索</span></div><nav class="rinne-bottom-controls" aria-label="プレイ操作"><button data-dash class="upgrade-control is-action"><span>走</span><small>ダッシュ</small></button><button data-mind class="upgrade-control"><span>意</span><small>意識</small></button><button data-items class="upgrade-control"><span>具</span><small>所持品</small></button><button data-map class="upgrade-control"><span>図</span><small>地図</small></button><button data-debug class="upgrade-control is-debug"><span>時</span><small>DEBUG 1×</small></button></nav><section data-panel class="upgrade-panel" hidden><header><strong data-title></strong><button data-close aria-label="閉じる">×</button></header><div data-body></div></section><div data-rest class="upgrade-rest" hidden><span></span><strong>休憩中</strong><small>長押し中、息を整えている</small></div><div data-training class="upgrade-training" hidden><strong>稽古態勢</strong><span data-training-name>かかし</span></div>`;gameScreen.append(root);
  const q=s=>root.querySelector(s),ui={root,dash:q('[data-dash]'),mind:q('[data-mind]'),items:q('[data-items]'),map:q('[data-map]'),debug:q('[data-debug]'),panel:q('[data-panel]'),title:q('[data-title]'),body:q('[data-body]'),close:q('[data-close]'),rest:q('[data-rest]'),training:q('[data-training]'),trainingName:q('[data-training-name]'),name:q('[data-name]'),equip:q('[data-equip]'),state:q('[data-state]')};let state=null;
  function inventory(){ensureProgression(state);ui.title.textContent='所持品';ui.body.innerHTML='<p class="upgrade-panel-copy">施設で受け取った装備や、冒険で拾った装備を持ち替えます。</p>';const group=(title,items,active,set,label)=>{const s=document.createElement('section');s.className='inventory-group';s.innerHTML=`<h3>${title}</h3>`;const list=document.createElement('div');list.className='inventory-list';for(const item of items){const b=document.createElement('button');b.dataset.active=String(item===active);b.textContent=label(item);b.onclick=()=>{set(item);audio.item();inventory();};list.append(b);}s.append(list);ui.body.append(s);};group('武器',state.inventory.weapons,state.equipment.weapon,v=>state.equipment.weapon=v,v=>WEAPON_LABELS[v]||v);group('防具',state.inventory.armors,state.equipment.armor,v=>state.equipment.armor=v,v=>ARMOR_LABELS[v]||v);group('盾',state.inventory.shields,Boolean(state.equipment.shield),v=>state.equipment.shield=Boolean(v),v=>v?'盾あり':'盾なし');}
  function mind(){ensureProgression(state);ui.title.textContent='意識';ui.body.innerHTML='<p class="upgrade-panel-copy">序・破・急ごとに、優先する技を設定します。</p>';const skills=state.knownSkills?.length?[...state.knownSkills]:['basic.fist'];for(const [phase,label] of PHASES){const row=document.createElement('div');row.className='mind-row';const b=document.createElement('b');b.textContent=label;const select=document.createElement('select'),current=Object.entries(state.skillWeights[phase]||{}).sort((a,b)=>Number(b[1])-Number(a[1]))[0]?.[0]||skills[0];for(const skill of skills){const o=document.createElement('option');o.value=o.textContent=skill;o.selected=skill===current;select.append(o);}select.onchange=()=>{state.skillWeights[phase]={[select.value]:100};audio.ui();};row.append(b,select);ui.body.append(row);}}
  function map(){ui.title.textContent='地図';const rows=stations.filter(r=>!r.interiorId&&!r.id.startsWith('rack.')&&!r.id.includes('dummy')).slice(0,20),xs=rows.map(r=>r.x).concat(state.position.x),zs=rows.map(r=>r.z).concat(state.position.z),minX=Math.min(...xs)-6,maxX=Math.max(...xs)+6,minZ=Math.min(...zs)-6,maxZ=Math.max(...zs)+6,w=Math.max(1,maxX-minX),h=Math.max(1,maxZ-minZ),p=(x,z)=>({x:(x-minX)/w*100,y:(z-minZ)/h*100}),me=p(state.position.x,state.position.z),marks=rows.map(r=>{const m=p(r.x,r.z);return `<i class="map-mark" style="left:${m.x}%;top:${m.y}%"><span>${String(r.label||r.id).slice(0,3)}</span></i>`;}).join('');ui.body.innerHTML=`<div class="upgrade-map"><div class="map-grid"></div>${marks}<b class="map-player" style="left:${me.x}%;top:${me.y}%"></b></div><p class="map-caption">${layout.name||'村'} · 現在地と主要施設</p>`;}
  function open(type){if(!state)return;ui.panel.hidden=false;ui.panel.dataset.type=type;if(type==='mind')mind();else if(type==='items')inventory();else map();audio.ui();}function close(){ui.panel.hidden=true;delete ui.panel.dataset.type;audio.ui();}
  ui.mind.onclick=()=>open('mind');ui.items.onclick=()=>open('items');ui.map.onclick=()=>open('map');ui.close.onclick=close;
  return{...ui,bindState(next){state=next;},refresh(){if(ui.panel.hidden||!state)return;open(ui.panel.dataset.type||'items');},open,close,summary(s,{dashing=false,resting=false,training=null}={}){state=s;ui.name.textContent=`${s.name||'旅人'} · ${Math.floor(s.ageYears||0)}歳`;ui.equip.textContent=`${WEAPON_LABELS[s.equipment?.weapon]||'素手'} · ${ARMOR_LABELS[s.equipment?.armor]||'旅装'}`;ui.state.textContent=s.down?'行動不能':resting?'休憩':dashing?'疾走':s.combat||training?.d<2.8?'戦闘態勢':'探索';ui.rest.hidden=!resting;ui.dash.dataset.active=String(dashing);const engaged=training?.d<2.8;ui.training.hidden=!engaged;if(engaged)ui.trainingName.textContent=training.label;},dispose(){root.remove();}};
}
