import { createKaykitVillageDetailRuntime } from '@soul/rendering/mura/kaykit-detail';

const distance=(a,b)=>Math.hypot((a?.x||0)-(b?.x||0),(a?.z||0)-(b?.z||0));
export const WEAPON_LABELS=Object.freeze({fist:'素手',sword:'片手剣',dagger:'短剣',great:'大剣',spear:'槍',axe:'戦斧',staff:'杖'});
export const ARMOR_LABELS=Object.freeze({cloth:'旅装',light:'軽装鎧',heavy:'重装鎧'});
export function ensureProgression(s){s.inventory??={weapons:['fist'],armors:['cloth'],shields:[false]};s.inventory.weapons=Array.from(new Set([...(s.inventory.weapons||[]),'fist',s.equipment?.weapon].filter(Boolean)));s.inventory.armors=Array.from(new Set([...(s.inventory.armors||[]),'cloth',s.equipment?.armor].filter(Boolean)));s.inventory.shields=Array.from(new Set([...(s.inventory.shields||[]),Boolean(s.equipment?.shield)]));s.acquiredStations=Array.isArray(s.acquiredStations)?s.acquiredStations:[];s.worldPickups=Array.isArray(s.worldPickups)?s.worldPickups:[];s.skillWeights??={jo:{},ha:{},kyu:{}};for(const p of['jo','ha','kyu'])s.skillWeights[p]??={};}
function scarecrow(T,r){const g=new T.Group(),wood=new T.MeshStandardMaterial({color:0x735238,roughness:.9}),cloth=new T.MeshStandardMaterial({color:0xa98153,roughness:.96});g.name=`TrainingDummy:${r.id}`;g.position.set(r.x,0,r.z);const post=new T.Mesh(new T.CylinderGeometry(.11,.14,2.4,8),wood);post.position.y=1.2;const arms=new T.Mesh(new T.CylinderGeometry(.08,.1,1.65,8),wood);arms.position.y=1.65;arms.rotation.z=Math.PI/2;const body=new T.Mesh(new T.BoxGeometry(.76,.82,.28),cloth);body.position.y=1.35;const head=new T.Mesh(new T.SphereGeometry(.28,10,8),cloth);head.position.y=2.25;g.add(post,arms,body,head);g.traverse(n=>{if(n.isMesh){n.castShadow=n.receiveShadow=true;}});return g;}
function armorStand(T,r){const g=new T.Group(),wood=new T.MeshStandardMaterial({color:0x5e4634,roughness:.9}),metal=new T.MeshStandardMaterial({color:r.armor==='heavy'?0x66717e:r.armor==='light'?0x768c89:0x9e7e68,roughness:.56,metalness:r.armor==='cloth'?.08:.38});g.name=`ArmorStand:${r.id}`;g.position.set(r.x,0,r.z);const pole=new T.Mesh(new T.CylinderGeometry(.08,.1,2.15,8),wood);pole.position.y=1.08;const torso=new T.Mesh(new T.CapsuleGeometry(.34,.55,5,9),metal);torso.position.y=1.34;const shoulders=new T.Mesh(new T.BoxGeometry(.95,.2,.42),metal);shoulders.position.y=1.72;g.add(pole,torso,shoulders);return g;}
function pickup(T,r){const g=new T.Group(),metal=new T.MeshStandardMaterial({color:0xc8cfcb,roughness:.26,metalness:.72}),wood=new T.MeshStandardMaterial({color:0x765034,roughness:.78});g.name=`AdventurePickup:${r.id}`;g.position.set(r.x,.15,r.z);const shaft=new T.Mesh(new T.CylinderGeometry(.035,.045,r.weapon==='spear'?1.45:.82,7),wood);shaft.position.y=r.weapon==='spear'?.72:.44;const blade=new T.Mesh(r.weapon==='axe'?new T.BoxGeometry(.42,.34,.07):new T.ConeGeometry(r.weapon==='great'?.12:.08,r.weapon==='great'?.68:.38,5),metal);blade.position.y=r.weapon==='spear'?1.55:r.weapon==='great'?.98:.84;if(r.weapon==='axe')blade.position.x=.17;g.add(shaft,blade);return g;}
export function createGameplayWorld({view,layout,stations}){
  const T=view.THREE,dojo=stations.find(r=>r.id==='dojo')||{x:0,z:0},smith=stations.find(r=>r.id==='smith')||{x:12,z:8};
  const dummies=[[-3.5,2.5],[-1.5,4.1],[1.1,4.4],[3.4,2.7],[0,6.3]].map(([x,z],i)=>({id:`dummy-extra-${i+1}`,label:`かかし ${i+1}`,x:dojo.x+x,z:dojo.z+z}));const dummyRoot=new T.Group();dummies.forEach(r=>dummyRoot.add(scarecrow(T,r)));view.scene.add(dummyRoot);
  const armors=[['cloth',-2.4],['light',0],['heavy',2.4]].map(([armor,dx],i)=>({id:`armor-stand-${armor}`,armor,x:smith.x+dx,z:smith.z+6.1+i*.15}));const armorRoot=new T.Group();armors.forEach(r=>armorRoot.add(armorStand(T,r)));view.scene.add(armorRoot);
  const pickups=[{id:'frontier-spear',weapon:'spear',x:-3.3,z:1.8},{id:'frontier-axe',weapon:'axe',x:3.1,z:-.8},{id:'frontier-great',weapon:'great',x:.4,z:-4.25}],pickupRoot=new T.Group(),pickupNodes=new Map();for(const r of pickups){const n=pickup(T,r);pickupNodes.set(r.id,n);pickupRoot.add(n);}view.scene.add(pickupRoot);
  const detail=createKaykitVillageDetailRuntime({THREE:T,rootURL:`${import.meta.env.BASE_URL}assets/vendor/kaykit-dungeon`}),hosts=new Map(),detailClean=[];view.scene.traverse(n=>{if(n.userData?.entityId)hosts.set(n.userData.entityId,n);});layout.objects.forEach((o,i)=>{const h=hosts.get(o.id);if(h)detailClean.push(detail.attach(h,o,i));});
  return{dummies,armors,pickups,pickupNodes,nearestDummy:s=>s?.zone==='village'&&!s.interior?dummies.map(r=>({...r,d:distance(s.position,r)})).sort((a,b)=>a.d-b.d)[0]:null,setZone(s){dummyRoot.visible=armorRoot.visible=s.zone==='village'&&!s.interior;pickupRoot.visible=s.zone==='frontier';},dispose(){dummyRoot.removeFromParent();armorRoot.removeFromParent();pickupRoot.removeFromParent();detailClean.forEach(fn=>fn());detail.dispose();}};
}
export {distance};
