import './gameplay-upgrade.css';
import { createTidebreakRuntime } from '@soul/tidebreak-combat';
import { createRinneAudio } from './gameplay-audio.js';
import { createGameplayUI } from './inspiration-gameplay-ui.js';
import { createCombatPoseRuntime } from './combat-pose.js';
import { ARMOR_LABELS, WEAPON_LABELS, createGameplayWorld, distance, ensureProgression } from './gameplay-world.js';
import { guidanceFor } from './rebuild/guidance.js';
import { isVillageLife } from './rebuild/village-walk-input.js';
import { practiceDummy } from './rebuild/domain.js';
import { objectiveNavigation, requestEquipmentChange } from './rebuild/gameplay-contract.js';

const SPEED_SCALE=1.32,DASH_SCALE=1.58,DASH_DRAIN=30,REST_RECOVERY=44,HOLD_MS=480,FLICK_DASH_FALLBACK_MS=360,PHASES=new Set(['jo','ha','kyu']);
const norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]/g,'');
function bone(root,names){let out=null;root?.traverse?.(n=>{if(out||!n.isBone)return;const k=norm(n.name);if(names.some(a=>k===a||k.endsWith(a)))out=n;});return out;}
let lastToastText='',lastToastAt=0;
function toast(text){const n=document.getElementById('toast');if(!n||!text)return;const now=performance.now();if(text===lastToastText&&now-lastToastAt<850)return;lastToastText=text;lastToastAt=now;n.textContent=text;n.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>{n.hidden=true;},1900);}

export function installRinneGameplayUpgrade({prepared,buildInfo}={}){
  if(!prepared?.view||!prepared?.gameScreen)return{dispose(){}};
  const {view,canvas,gameScreen,stations,layout}=prepared,audio=createRinneAudio(),world=createGameplayWorld({view,layout,stations}),abort=new AbortController(),signal=abort.signal;
  const equipmentStations=[...stations,...world.armors.map(row=>({...row,label:`${ARMOR_LABELS[row.armor]||row.armor}置き場`,equipmentAccess:true,equipmentRadius:1.45}))];
  let state=null,dash=false,rest=false,latchedLifeRest=false,hold=null,holdTimer=0,dashTimer=0,lastTraining='',lastEquipment='',lastDash=false,lastRest=false,lastStep=0,restPose=null,sharedKey='';
  const canLatchLifeRest=()=>isVillageLife(state)&&!canvas.dataset.coopWorld&&!document.querySelector('dialog[open]');
  const requestEquip=(kind,value)=>requestEquipmentChange(state,{kind,value,stations:equipmentStations});
  const ui=createGameplayUI(gameScreen,{stations,layout,audio,requestEquip}),originalVector=view.cameraVector.bind(view),originalMove=view.canMoveTo.bind(view),originalRender=view.renderState.bind(view),originalBefore=view.scene.onBeforeRender,originalAfter=view.scene.onAfterRender,combatPose=createCombatPoseRuntime(view),contextAnchorPoint=view.THREE?.Vector3?new view.THREE.Vector3():null;
  const tidebreak=createTidebreakRuntime({weapon:'fist',onImpact:()=>audio.combat(),onLog:()=>{}}),sharedWeapons=new Set(tidebreak.weapons());gameScreen.dataset.sharedCombat=tidebreak.sourceVersion;
  const sharedWeapon=id=>sharedWeapons.has(id)?id:id==='great'&&sharedWeapons.has('greatsword')?'greatsword':sharedWeapons.has('sword')?'sword':[...sharedWeapons][0]||'fist';

  function acquire(s){
    const rack=stations.filter(r=>r.equipment&&!r.interiorId).map(r=>({...r,d:distance(s.position,r)})).sort((a,b)=>a.d-b.d)[0];
    if(!s.moving&&s.zone==='village'&&rack?.d<=1.15&&!s.acquiredStations.includes(rack.id)){s.acquiredStations.push(rack.id);if(rack.equipment.weapon&&!s.inventory.weapons.includes(rack.equipment.weapon))s.inventory.weapons.push(rack.equipment.weapon);if(rack.equipment.armor&&!s.inventory.armors.includes(rack.equipment.armor))s.inventory.armors.push(rack.equipment.armor);if(Object.hasOwn(rack.equipment,'shield')&&!s.inventory.shields.includes(Boolean(rack.equipment.shield)))s.inventory.shields.push(Boolean(rack.equipment.shield));toast(`${rack.label} を受け取った`);audio.item();}
    const stand=world.armors.map(r=>({...r,d:distance(s.position,r)})).sort((a,b)=>a.d-b.d)[0];if(!s.moving&&s.zone==='village'&&stand?.d<=1.25){if(!s.inventory.armors.includes(stand.armor)){s.inventory.armors.push(stand.armor);toast(`${ARMOR_LABELS[stand.armor]} 一式を受け取った`);audio.item();}requestEquipmentChange(s,{kind:'armor',value:stand.armor,stations:equipmentStations});}
    if(s.zone==='frontier')for(const r of world.pickups){const node=world.pickupNodes.get(r.id);if(s.worldPickups.includes(r.id)){if(node)node.visible=false;continue;}if(distance(s.position,r)>1.05)continue;s.worldPickups.push(r.id);if(!s.inventory.weapons.includes(r.weapon))s.inventory.weapons.push(r.weapon);if(node)node.visible=false;toast(`${WEAPON_LABELS[r.weapon]||r.weapon} を拾った`);audio.item();}
  }
  function sharedCombat(s,training,dt){
    // Main combat already has one authoritative executor. The training display
    // must never run a second combat timer or publish a different phase.
    if(s.combat&&!s.combat.training){const pose=s.combat.tidebreakPose;gameScreen.dataset.sharedCombatActive='true';gameScreen.dataset.sharedCombatAttack=pose?.attack||'';s.combat.sharedPhase=s.combat.phase;return;}

    const practice=training?.d<2.8?{id:training.id,hp:999,distance:training.d}:null,enemy=s.combat&&s.frontState?.enemies?.find(e=>e.id===s.combat.targetId&&!e.dead),target=practice||(enemy?{...enemy,distance:distance(s.position,enemy)}:null);
    if(!target||s.down||s.ended){sharedKey='';gameScreen.dataset.sharedCombatActive='false';return;}
    const weapon=sharedWeapon(s.equipment?.weapon),key=`${s.zone}:${target.id}:${weapon}`;if(key!==sharedKey){sharedKey=key;tidebreak.configure({weapon,hp:Math.max(1,s.hp||1),maxhp:Math.max(1,s.maxHp||1),enemyHp:Math.max(1,target.hp||100),positions:{hero:{x:0,z:0,yaw:0},enemy:{x:0,z:Math.max(1.05,Math.min(3.2,target.distance||1.8)),yaw:Math.PI}}});}
    tidebreak.input(0,0,0,0);const shared=tidebreak.step(Math.max(0,Math.min(.033,dt||0))),slot=shared.hero.slot;if(s.combat&&PHASES.has(slot))s.combat.sharedPhase=slot;if(s.combat)s.combat.sharedSource=tidebreak.sourceVersion;Object.assign(gameScreen.dataset,{sharedCombatActive:'true',sharedCombatAttack:shared.hero.attack||'',sharedCombatReady:String(Boolean(shared.hero.combatReady))});
  }
  function applyRestPose(){if(!rest||!state||state.moving||state.combat)return;const root=view.scene.getObjectByName('Player');if(!root)return;const bones={hips:bone(root,['hips']),spine:bone(root,['spine']),lu:bone(root,['upperlegl','leftupperleg']),ru:bone(root,['upperlegr','rightupperleg']),ll:bone(root,['lowerlegl','leftlowerleg']),rl:bone(root,['lowerlegr','rightlowerleg'])};restPose={root,y:root.position.y,x:root.rotation.x,bones:Object.values(bones).filter(Boolean).map(b=>[b,b.rotation.x,b.rotation.z])};root.position.y-=.13;root.rotation.x=.055;if(bones.hips)bones.hips.rotation.x+=.08;if(bones.spine)bones.spine.rotation.x+=.16;if(bones.lu)bones.lu.rotation.x+=.52;if(bones.ru)bones.ru.rotation.x+=.52;if(bones.ll)bones.ll.rotation.x-=.72;if(bones.rl)bones.rl.rotation.x-=.72;}
  function restoreRestPose(){if(!restPose)return;restPose.root.position.y=restPose.y;restPose.root.rotation.x=restPose.x;for(const [b,x,z] of restPose.bones)b.rotation.set(x,b.rotation.y,z);restPose=null;}
  function syncGuidance(s){const guide=guidanceFor({state:s,stations,front:s.frontState||null}),navigation=objectiveNavigation(s,guide);let target=document.getElementById('objective-target');if(!target){target=document.createElement('small');target.id='objective-target';target.className='objective-target';document.querySelector('.objective-card')?.append(target);}if(target){target.hidden=!navigation;target.textContent=navigation?.text||'';}gameScreen.dataset.objectiveTargetId=navigation?.targetId||'';if(s.down)gameScreen.dataset.worldTone='down';ui.setGuidance({guide,navigation});}
  function syncContextAnchor(){
    const anchor=view.combatAnchor?.();if(anchor){ui.setContextAnchor({x:anchor.x,y:anchor.y,visible:anchor.z>=-1&&anchor.z<=1});return;}

    const actor=view.scene.getObjectByName('Player');if(!actor||!contextAnchorPoint){ui.setContextAnchor({visible:false});return;}
    contextAnchorPoint.set(0,1.72,0);actor.localToWorld(contextAnchorPoint);contextAnchorPoint.project(view.camera);
    const width=view.viewport?.width??canvas.clientWidth,height=view.viewport?.height??canvas.clientHeight,visible=contextAnchorPoint.z>=-1&&contextAnchorPoint.z<=1&&Math.abs(contextAnchorPoint.x)<=1.08&&Math.abs(contextAnchorPoint.y)<=1.08;
    ui.setContextAnchor({x:(contextAnchorPoint.x*.5+.5)*width,y:(-.5*contextAnchorPoint.y+.5)*height,visible});
  }

  view.cameraVector=axis=>{const v=originalVector(axis),base=state?.phase==='birth'?1.08:SPEED_SCALE;return v.multiplyScalar(base*(dash&&state?.stamina>2&&!rest?DASH_SCALE:1));};
  view.canMoveTo=(x,z,r=.32,zone='village',interior=null)=>originalMove(x,z,zone==='village'?Math.min(r,.205):zone==='interior'?Math.min(r,.27):r,zone,interior);
  view.scene.onBeforeRender=(...a)=>{originalBefore?.apply(view.scene,a);applyRestPose();combatPose.apply(state);};view.scene.onAfterRender=(...a)=>{combatPose.restore();restoreRestPose();originalAfter?.apply(view.scene,a);};
  view.renderState=(next,dt=0)=>{
    state=next;if(latchedLifeRest&&(!canLatchLifeRest()||state.moving||state.activity)){latchedLifeRest=false;rest=false;}ensureProgression(state);ui.bindState(state);const training=world.nearestDummy(state),synthetic=training?.d<2.8&&!state.combat&&!state.down&&!state.ended,oldCombat=state.combat,oldYaw=state.yaw;if(synthetic){state.combat={targetId:training.id,phase:'jo',attackCooldown:999,training:true,sharedSource:tidebreak.sourceVersion};state.yaw=Math.atan2(training.x-state.position.x,training.z-state.position.z);if(lastTraining!==training.id){lastTraining=training.id;toast(`${training.label} · 戦闘態勢`);audio.combat();}}else if(!training||training.d>=3.2)lastTraining='';
    sharedCombat(state,training,dt);const dashing=dash&&state.moving&&!state.down&&!state.ended&&!rest&&state.stamina>2;if(dashing){state.stamina=Math.max(0,state.stamina-DASH_DRAIN*dt);state.resting=false;}if(rest&&!state.moving&&!state.down&&!state.ended&&!state.combat){state.resting=true;state.stamina=Math.min(state.staminaCap||100,state.stamina+REST_RECOVERY*dt);}acquire(state);
    const equipment=`${state.equipment.weapon}:${state.equipment.armor}:${Boolean(state.equipment.shield)}`;if(lastEquipment&&equipment!==lastEquipment)ui.refresh();lastEquipment=equipment;const now=performance.now()/1000;if(state.moving&&!rest&&now-lastStep>.18){lastStep=now;audio.step(now);}if(dashing&&!lastDash)audio.dash();if(rest&&!lastRest)audio.rest();lastDash=dashing;lastRest=rest;world.setZone(state);syncGuidance(state);ui.summary(state,{dashing,resting:rest,training});originalRender(state,dt);if(!ui.renderPlayerPortrait?.(view.renderPlayerPortrait))ui.capturePlayerPortrait?.(canvas,{x:.5,y:.57,scale:.3});syncContextAnchor();if(synthetic){state.combat=oldCombat;state.yaw=oldYaw;}
  };

  const dashOn=e=>{if(e.button!=null&&e.button!==0)return;clearTimeout(dashTimer);dash=true;rest=false;audio.unlock();ui.dash.setPointerCapture?.(e.pointerId);e.preventDefault();},dashOff=e=>{dash=false;try{ui.dash.releasePointerCapture?.(e.pointerId);}catch{}e.preventDefault();};ui.dash.addEventListener('pointerdown',dashOn,{signal});ui.dash.addEventListener('pointerup',dashOff,{signal});ui.dash.addEventListener('pointercancel',dashOff,{signal});
  canvas.addEventListener('rinne:flick-dash',e=>{if(!state||state.phase==='birth'||state.down||state.ended||state.stamina<=2)return;dash=true;rest=false;audio.unlock();clearTimeout(dashTimer);dashTimer=setTimeout(()=>{dash=false;},Math.max(80,Number(e.detail?.durationMs)||FLICK_DASH_FALLBACK_MS));},{signal});
  const strikeDummy=()=>{if(!state)return;const training=world.nearestDummy(state);if(!training||training.d>=2.8){toast('かかしへ近づいてください');return;}world.hitDummy(training.id);audio.combat();try{globalThis.navigator?.vibrate?.(12);}catch{}const events=practiceDummy(state,training),learned=events.find(event=>event.type==='inspiration');if(learned)toast(`閃き · ${learned.name}`);else if(events.some(event=>event.type==='activity-complete'))toast('打ち込みが経験として残った');else toast('打ち込む');ui.refresh();gameScreen.dispatchEvent(new CustomEvent('rinne:training-impact',{detail:{dummyId:training.id,learned:learned?.id||null}}));};
  ui.trainingStrike?.addEventListener('click',strikeDummy,{signal});
  canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;audio.unlock();if(latchedLifeRest){rest=false;latchedLifeRest=false;}clearTimeout(dashTimer);dash=false;hold={id:e.pointerId,x:e.clientX,y:e.clientY};clearTimeout(holdTimer);holdTimer=setTimeout(()=>{if(hold?.id!==e.pointerId||!state||state.phase==='birth'||state.down||state.ended||document.querySelector('dialog[open]'))return;rest=true;dash=false;toast('休憩 · スタミナ回復');},HOLD_MS);},{signal,capture:true});canvas.addEventListener('pointermove',e=>{if(hold?.id!==e.pointerId)return;if(Math.hypot(e.clientX-hold.x,e.clientY-hold.y)>10){clearTimeout(holdTimer);rest=false;}},{signal,capture:true});const end=e=>{if(hold?.id===e.pointerId){clearTimeout(holdTimer);hold=null;latchedLifeRest=e.type==='pointerup'&&rest&&canLatchLifeRest();if(!latchedLifeRest)rest=false;}};canvas.addEventListener('pointerup',end,{signal,capture:true});canvas.addEventListener('pointercancel',end,{signal,capture:true});
  const textEntry=target=>Boolean(target?.closest?.('input,textarea,select,[contenteditable]:not([contenteditable="false"])'));window.addEventListener('keydown',e=>{if(e.isComposing||e.key==='Process'||textEntry(e.target))return;if(latchedLifeRest&&['ArrowRight','ArrowLeft','ArrowUp','ArrowDown','KeyW','KeyA','KeyS','KeyD'].includes(e.code)){latchedLifeRest=false;rest=false;}if(e.code==='ShiftLeft'||e.code==='ShiftRight'){clearTimeout(dashTimer);dash=true;rest=false;return;}if(e.ctrlKey||e.metaKey||e.altKey||e.shiftKey)return;if(e.code==='KeyH')ui.open('heart');if(e.code==='KeyT')ui.open('technique');if(e.code==='KeyB')ui.open('body');if(e.code==='KeyM')ui.open('map');if(e.code==='KeyI')ui.open('items');if(e.code==='KeyL')ui.open('record');},{signal});window.addEventListener('keyup',e=>{if(e.code==='ShiftLeft'||e.code==='ShiftRight')dash=false;},{signal});document.addEventListener('visibilitychange',()=>{if(document.hidden){clearTimeout(holdTimer);hold=null;clearTimeout(dashTimer);dash=false;rest=false;latchedLifeRest=false;}},{signal});
  const rates=[1,5,10,20],clock=document.getElementById('clock-rate');if(clock){clock.closest('.clock-rate')?.setAttribute('data-product-clock','true');clock.addEventListener('click',()=>{if(clock.disabled){toast('共有世界では時間倍率を変更できません');return;}const current=Number(clock.value)||1,index=Math.max(0,rates.indexOf(current)),rate=rates[(index+1)%rates.length];clock.value=String(rate);clock.textContent=`${rate}×`;clock.onchange?.({target:clock});audio.ui();},{signal});}
  Object.assign(gameScreen.dataset,{gameplayUpgrade:'2026-09-18-game-ui-contract',assetUnity:'kaykit-dungeon-shared',build:String(buildInfo?.commit||'')});
  return{dispose(){abort.abort();clearTimeout(holdTimer);clearTimeout(dashTimer);combatPose.restore();restoreRestPose();view.cameraVector=originalVector;view.canMoveTo=originalMove;view.renderState=originalRender;view.scene.onBeforeRender=originalBefore;view.scene.onAfterRender=originalAfter;world.dispose();ui.dispose();audio.dispose();delete gameScreen.dataset.gameplayUpgrade;}};
}