import {RINNE_SOUND_REVIEW_LIBRARY,filterSoundReviewLibrary,soundReviewCounts} from './review-sound-catalog.js';
import {mountRinneReviewShell} from './review-lab-shell.js';
mountRinneReviewShell('sounds');
const q=s=>document.querySelector(s),player=new Audio(),state={kind:'all',query:'',selected:null,playing:false};
player.preload='metadata';player.volume=.72;
const ui={count:q('#sound-count'),status:q('#sound-status'),kind:q('#sound-kind'),title:q('#sound-title'),category:q('#sound-category'),id:q('#sound-id'),current:q('#sound-current'),duration:q('#sound-duration'),seek:q('#sound-seek'),play:q('#sound-play'),restart:q('#sound-restart'),volume:q('#sound-volume'),loop:q('#sound-loop'),scene:q('#sound-scene'),bpm:q('#sound-bpm'),source:q('#sound-source'),description:q('#sound-description'),catalog:q('#sound-catalog'),empty:q('#sound-empty'),search:q('#sound-search'),pulse:q('#sound-pulse')};
const clock=v=>{const n=Math.max(0,Number(v)||0);return Math.floor(n/60)+':'+String(Math.floor(n%60)).padStart(2,'0')};
const duration=()=>Number.isFinite(player.duration)&&player.duration>0?player.duration:state.selected?.duration||0;
function transport(){const d=duration(),t=Math.min(player.currentTime||0,d||Infinity);ui.current.textContent=clock(t);ui.duration.textContent=clock(d);ui.seek.max=String(d||1);ui.seek.value=String(Math.min(t,d||1));ui.play.textContent=state.playing?'❚❚ 一時停止':'▶ 再生';ui.pulse.classList.toggle('is-playing',state.playing)}
function render(){const items=filterSoundReviewLibrary({kind:state.kind,query:state.query});ui.catalog.replaceChildren();ui.empty.hidden=items.length>0;for(const item of items){const b=document.createElement('button'),a=document.createElement('span'),n=document.createElement('strong'),m=document.createElement('small');b.type='button';b.className='sound-option review-choice-card';b.setAttribute('role','listitem');b.setAttribute('aria-pressed',String(state.selected?.id===item.id));a.textContent=(item.kind==='bgm'?'BGM':'SFX')+' · '+(item.category||'その他');n.textContent=item.title;m.textContent=item.kind==='bgm'?(item.bpm?item.bpm+' BPM':'BGM'):'SFX';b.append(a,n,m);b.addEventListener('click',()=>select(item));ui.catalog.append(b)}}
function select(item){state.selected=item;state.playing=false;player.pause();player.src=item.url;player.loop=ui.loop.checked;player.load();ui.kind.textContent=item.kind==='bgm'?'BGM':'SFX';ui.title.textContent=item.title;ui.category.textContent=item.category||'—';ui.id.textContent=item.id;ui.scene.textContent=item.scene||'—';ui.bpm.textContent=item.bpm?item.bpm+' BPM':'—';ui.source.textContent=item.source;ui.description.textContent=item.description||'説明なし';ui.status.textContent=item.title+' を選択';transport();render()}
ui.play.addEventListener('click',async()=>{if(!state.selected)return;if(state.playing){player.pause();return}try{await player.play();ui.status.textContent=state.selected.title+' を再生中'}catch{ui.status.textContent='再生できません。もう一度操作してください。'}});
ui.restart.addEventListener('click',async()=>{if(!state.selected)return;player.currentTime=0;try{await player.play()}catch{}});
ui.volume.addEventListener('input',()=>player.volume=Number(ui.volume.value));ui.loop.addEventListener('change',()=>player.loop=ui.loop.checked);
ui.seek.addEventListener('input',()=>{player.currentTime=Math.min(Number(ui.seek.value)||0,duration()||0);transport()});ui.search.addEventListener('input',()=>{state.query=ui.search.value;render()});
for(const button of document.querySelectorAll('[data-sound-filter]'))button.addEventListener('click',()=>{state.kind=button.dataset.soundFilter;for(const candidate of document.querySelectorAll('[data-sound-filter]'))candidate.setAttribute('aria-pressed',String(candidate===button));render()});
player.addEventListener('play',()=>{state.playing=true;transport()});player.addEventListener('pause',()=>{state.playing=false;transport()});player.addEventListener('ended',()=>{state.playing=false;transport()});player.addEventListener('timeupdate',transport);player.addEventListener('loadedmetadata',transport);document.addEventListener('visibilitychange',()=>{if(document.hidden)player.pause()});
const counts=soundReviewCounts();ui.count.textContent='SOUNDS '+counts.total+' · SFX '+counts.sfx+' · BGM '+counts.bgm;ui.status.textContent='単独試聴できます';render();select(RINNE_SOUND_REVIEW_LIBRARY[1]||RINNE_SOUND_REVIEW_LIBRARY[0]);
