#!/usr/bin/env python3
"""Explicit generation command. Never imported by runtime, npm lifecycle or validation."""
from __future__ import annotations
import argparse
from datetime import datetime, timezone
import gzip
import json
import os
from pathlib import Path
import subprocess
import traceback
import uuid
from core import (MAX_INPUT_BYTES, MAX_RAW_BYTES, add_manifest, contained, digest,
                  inspect_glb, json_bytes, validate_request, write_immutable)
from provider import create_provider

ROOT = Path(__file__).resolve().parents[3]
LIBRARY = ROOT / 'apps/review/public/library'
CATALOG = ROOT / 'packages/assets/generated/experimental-assets.json'
CATALOG_MODULE = ROOT / 'packages/assets/generated/experimental-assets.js'


def atomic_bytes(path: Path, data: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + '.tmp-' + uuid.uuid4().hex)
    temporary.write_bytes(data)
    os.replace(temporary, path)


def atomic_json(path: Path, value) -> None:
    atomic_bytes(path, json_bytes(value))


def catalog_module_bytes(catalog: dict) -> bytes:
    assets = json.dumps(catalog['assets'], ensure_ascii=False, indent=2, allow_nan=False)
    return ("// Generated by scripts/tools/hi3dgen/pipeline.py; do not edit by hand.\n"
            "export const EXPERIMENTAL_GENERATED_ASSETS=Object.freeze(" + assets + ".map(Object.freeze));\n").encode()


def checked_bytes(path: Path, maximum: int) -> bytes:
    if not path.is_file() or not 0 < path.stat().st_size <= maximum:
        raise ValueError('INPUT_BYTE_BUDGET: ' + str(path))
    return path.read_bytes()


def prepare_images(request, work):
    from PIL import Image, ImageOps
    Image.MAX_IMAGE_PIXELS = 16_000_000
    images = []
    for index, row in enumerate(request['images']):
        source = contained(ROOT, row['path'])
        raw = checked_bytes(source, MAX_INPUT_BYTES)
        with Image.open(source) as image:
            if image.format not in ('PNG', 'JPEG', 'WEBP') or getattr(image, 'n_frames', 1) != 1:
                raise ValueError('STATIC_PNG_JPEG_WEBP_REQUIRED')
            if min(image.size) < 128 or max(image.size) > 4096:
                raise ValueError('IMAGE_DIMENSION_BUDGET')
            image = ImageOps.exif_transpose(image).convert('RGBA')
            image.thumbnail((1024,1024))
            normalized = work / f'upload-{index}.png'
            image.save(normalized, 'PNG', optimize=True)
        upload = checked_bytes(normalized, MAX_INPUT_BYTES)
        images.append({'metadata': row, 'raw': raw, 'upload': upload, 'uploadPath': normalized,
                       'originalIntegrity': digest(raw), 'uploadedIntegrity': digest(upload)})
    return images


def run(args):
    work = Path(args.resume).resolve() if args.resume else ROOT / '.artifacts/hi3dgen' / uuid.uuid4().hex
    work.mkdir(parents=True, exist_ok=True)
    stage = 'request'
    def log(current, state, **details):
        nonlocal stage
        stage = current
        event = {'at': datetime.now(timezone.utc).isoformat(), 'stage': current, 'state': state, **details}
        with (work / 'events.jsonl').open('a') as stream:
            stream.write(json.dumps(event, ensure_ascii=False, allow_nan=False) + '\n')
        print(json.dumps(event, ensure_ascii=False, allow_nan=False), flush=True)
    try:
        request_path = contained(ROOT, args.request)
        request_bytes = checked_bytes(request_path, 100_000)
        request = validate_request(json.loads(request_bytes))
        request_hash = digest(request_bytes)['sha256']
        head = subprocess.check_output(['git','rev-parse','HEAD'], cwd=ROOT, text=True).strip()
        write_immutable(work / 'request.json', request_bytes)
        log('input', 'started', assetId=request['id'])
        images = prepare_images(request, work)
        catalog = json.loads(CATALOG.read_text()) if CATALOG.exists() else {'schema':1,'usage':'experimental-review','assets':[]}
        if catalog.get('schema') != 1 or catalog.get('usage') != 'experimental-review':
            raise ValueError('EXPERIMENTAL_CATALOG_SCHEMA')
        existing = next((item for item in catalog['assets'] if item['id'] == request['id']), None)
        if existing:
            input_hashes = [item['originalIntegrity']['sha256'] for item in images]
            if existing['requestSha256'] != request_hash or existing['inputSha256'] != input_hashes:
                raise ValueError('ASSET_ID_EXISTS_WITH_DIFFERENT_INPUTS')
            output = checked_bytes(contained(LIBRARY, existing['runtimePath']), 20*1024*1024)
            if digest(output)['sha256'] != existing['sha256'] or len(output) != existing['byteLength']:
                raise ValueError('EXISTING_ASSET_INTEGRITY_FAILURE')
            inspect_glb(output)
            atomic_bytes(CATALOG_MODULE, catalog_module_bytes(catalog))
            log('complete', 'already-materialized', assetId=request['id'], inferenceRequests=0)
            return
        provider = create_provider(request['provider'], log, work)
        if len(images) > provider.max_views:
            raise ValueError('PROVIDER_MULTIVIEW_UNSUPPORTED')
        raw_path, inference_path = work/'raw.glb', work/'inference.json'
        if args.resume:
            if not raw_path.is_file() or not inference_path.is_file():
                raise ValueError('RESUME_REQUIRES_DOWNLOADED_RAW_MESH')
            inference = json.loads(inference_path.read_text())
            raw = checked_bytes(raw_path, MAX_RAW_BYTES)
            if inference['requestSha256'] != request_hash or inference['inputSha256'] != [item['originalIntegrity']['sha256'] for item in images] or digest(raw) != inference['rawIntegrity']:
                raise ValueError('RESUME_INPUT_OR_RAW_INTEGRITY_MISMATCH')
            snapshot = inference['snapshot']
            log('inference', 'resumed-downloaded-mesh', inferenceRequests=0)
        else:
            log('provenance', 'snapshot-started')
            snapshot = provider.snapshot()
            log('inference', 'started', provider=request['provider']['id'])
            raw, receipt = provider.infer(images[0]['uploadPath'], request['parameters'])
            inspect_glb(raw, MAX_RAW_BYTES)
            write_immutable(raw_path, raw)
            inference = {'requestSha256':request_hash,
                'inputSha256':[item['originalIntegrity']['sha256'] for item in images],
                'generatedAt':datetime.now(timezone.utc).isoformat(),'snapshot':snapshot,
                'providerReceipt':receipt,'rawIntegrity':digest(raw),'generationHead':head}
            write_immutable(inference_path, json_bytes(inference))
        log('postprocess', 'started')
        output_path, report_path = work/'normalized.glb', work/'postprocess.json'
        subprocess.run([args.blender,'--background','--factory-startup','--python',str(Path(__file__).with_name('postprocess.py')),
            '--','--input',str(raw_path),'--output',str(output_path),'--request',str(work/'request.json'),
            '--report',str(report_path)], cwd=ROOT, check=True, timeout=600)
        output = checked_bytes(output_path, 20*1024*1024)
        inspection = inspect_glb(output)
        report = json.loads(report_path.read_text())
        if inspection['triangles'] > request['postprocess']['maxTriangles'] or report['triangles'] != inspection['triangles']:
            raise ValueError('FINAL_TRIANGLE_BUDGET_OR_EXPORT_MISMATCH')
        metadata = digest(output)
        prefix = 'experimental/hi3dgen/' + request['id']
        runtime_path = prefix + '/' + metadata['sha256'] + '.glb'
        provenance_path = prefix + '/' + metadata['sha256'] + '.provenance.json'
        payloads = {runtime_path: output}
        inputs = []
        for item in images:
            image = item['metadata']
            original_path = prefix+'/input/'+item['originalIntegrity']['sha256']+Path(image['path']).suffix.lower()
            uploaded_path = prefix+'/input/'+item['uploadedIntegrity']['sha256']+'.png'
            payloads[original_path] = item['raw']; payloads[uploaded_path] = item['upload']
            inputs.append({**image,'sourceRepositoryPath':image['path'],
                'sourceImagePath':original_path,'uploadedImagePath':uploaded_path,
                'originalIntegrity':item['originalIntegrity'],'uploadedIntegrity':item['uploadedIntegrity']})
        license_evidence = []
        for row in snapshot['licenseEvidence']:
            path = work/'licenses'/(row['name']+'.txt')
            data = checked_bytes(path, 2*1024*1024)
            if digest(data)['sha256'] != row['sha256']:
                raise ValueError('LICENSE_EVIDENCE_INTEGRITY_FAILURE')
            relative = prefix+'/licenses/'+row['sha256']+'.txt'
            payloads[relative] = data
            license_evidence.append({**row,'materializedPath':relative})
        raw_gzip = gzip.compress(raw, compresslevel=9, mtime=0)
        if len(raw_gzip) > 95*1024*1024:
            raise ValueError('REPOSITORY_SOURCE_FILE_BUDGET')
        raw_repository_path = 'assets/generated/hi3dgen/'+request['id']+'/'+inference['rawIntegrity']['sha256']+'.glb.gz'
        request_materialized_path = prefix+'/requests/'+request_hash+'.json'
        payloads[request_materialized_path] = request_bytes
        warnings = ['Experimental generated geometry is not Production-approved.',
                    'Heading and visual quality require review; software licensing is not output-rights clearance.']
        if len(output)>8*1024*1024:
            warnings.append('Large experimental asset: above 8 MiB mobile warning threshold.')
        if inspection['triangles']>12000:
            warnings.append('Above 12,000-triangle prop warning threshold.')
        provenance = {'schema':1,'id':request['id'],'origin':'ai-generated','status':'MATERIALIZED',
            'usage':'experimental-review','productionEligible':False,'license':'LicenseRef-Generated-Experimental',
            'outputRightsStatus':'unreviewed-not-inferred-from-model-license',
            'sourceImages':inputs,'provider':{**snapshot,'licenseEvidence':license_evidence},
            'parameters':request['parameters'],'generatedAt':inference['generatedAt'],
            'generationHead':inference['generationHead'],'materializedOnHead':head,
            'request':{'path':args.request,'materializedPath':request_materialized_path,'sha256':request_hash},
            'acquisition':inference['providerReceipt'],'rawMesh':{**inference['rawIntegrity'],
                'repositoryArchivePath':raw_repository_path,'archiveIntegrity':digest(raw_gzip)},
            'output':{**metadata,'runtimePath':runtime_path,'inspection':inspection},
            'postprocess':report,'warnings':warnings}
        payloads[provenance_path] = json_bytes(provenance)
        entry = {'id':request['id'],'label':request['label'],'origin':'ai-generated','status':'MATERIALIZED',
            'usage':'experimental-review','productionEligible':False,'license':provenance['license'],
            'requestSha256':request_hash,'inputSha256':inference['inputSha256'],
            'runtimePath':runtime_path,'provenancePath':provenance_path,
            'thumbnailPath':inputs[0]['uploadedImagePath'],**metadata,'inspection':inspection,
            'boundingBox':report['boundingBox'],'up':report['up'],'originPlacement':report['origin'],
            'model':snapshot['model'],'sourceRevision':snapshot['sourceRevision'],
            'generatedAt':inference['generatedAt'],'review':{'route':'/review-objects?generated=1','visualApproval':False}}
        manifest_path = LIBRARY/'manifest.json'
        manifest = json.loads(manifest_path.read_text())
        if manifest.get('schema') != 1 or manifest.get('immutable') is not True:
            raise ValueError('ASSET_ORIGIN_MANIFEST_CONTRACT')
        log('materialize','started', byteLength=len(output), triangles=inspection['triangles'])
        for relative, data in payloads.items():
            add_manifest(manifest, relative, data)
        write_immutable(contained(ROOT,raw_repository_path), raw_gzip)
        for relative, data in payloads.items():
            write_immutable(contained(LIBRARY,relative), data)
        manifest['files'].sort(key=lambda row:row['path'])
        catalog['assets'].append(entry)
        atomic_json(manifest_path, manifest)
        atomic_json(CATALOG, catalog)
        atomic_bytes(CATALOG_MODULE, catalog_module_bytes(catalog))
        write_immutable(work/'receipt.json', json_bytes({'state':'MATERIALIZED','entry':entry,'head':head}))
        log('complete','materialized',assetId=request['id'],runtimePath=runtime_path,sha256=metadata['sha256'])
    except Exception as error:
        atomic_json(work/'failure.json', {'state':'FAILED','stage':stage,'type':type(error).__name__,'error':str(error)[:2000]})
        log(stage,'failed',error=str(error)[:2000])
        traceback.print_exc()
        raise


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--request',required=True,help='repository-relative request JSON')
    parser.add_argument('--blender',default='blender')
    parser.add_argument('--resume',help='resume postprocessing a previously downloaded, integrity-checked raw mesh')
    run(parser.parse_args())
