const clone=value=>structuredClone(value);
const isObject=value=>value&&typeof value==='object'&&!Array.isArray(value);
const entityArray=value=>Array.isArray(value)&&value.every(item=>isObject(item)&&('id'in item));
const same=(a,b)=>Object.is(a,b)||JSON.stringify(a)===JSON.stringify(b);

function mergePatch(before,after){if(same(before,after))return null;if(!isObject(before)||!isObject(after))return{$set:clone(after)};const patch={};let changed=false;for(const key of new Set([...Object.keys(before),...Object.keys(after)])){if(!(key in after)){patch[key]={$delete:true};changed=true;continue;}const child=mergePatch(before[key],after[key]);if(child!==null){patch[key]=child;changed=true;}}return changed?patch:null;}
function applyMerge(target,patch){if(patch&&'$set'in patch)return clone(patch.$set);if(patch?.$delete)return undefined;const out=isObject(target)?target:{};for(const[key,child]of Object.entries(patch||{})){const value=applyMerge(out[key],child);if(value===undefined&&child?.$delete)delete out[key];else out[key]=value;}return out;}
function atPath(root,path){let node=root;for(const key of path)node=node[key];return node;}

export function createIncrementalPatch(before,after){const ops=[];function walk(a,b,path){if(same(a,b))return;if(entityArray(a)&&entityArray(b)){const left=new Map(a.map(v=>[String(v.id),v])),right=new Map(b.map(v=>[String(v.id),v]));for(const[id,value]of right){if(!left.has(id)){ops.push({op:'entity-set',path,id,value:clone(value)});continue;}const patch=mergePatch(left.get(id),value);if(patch)ops.push({op:'entity-patch',path,id,patch});}for(const id of left.keys())if(!right.has(id))ops.push({op:'entity-delete',path,id});return;}if(isObject(a)&&isObject(b)){for(const key of new Set([...Object.keys(a),...Object.keys(b)])){if(!(key in b))ops.push({op:'delete',path:[...path,key]});else if(!(key in a))ops.push({op:'set',path:[...path,key],value:clone(b[key])});else walk(a[key],b[key],[...path,key]);}return;}ops.push({op:'set',path,value:clone(b)});}walk(before,after,[]);return ops;}

export function applyIncrementalPatch(base,ops){let root=clone(base);for(const op of ops||[]){if(!op.path?.length&&op.op==='set'){root=clone(op.value);continue;}if(op.op==='entity-set'||op.op==='entity-patch'||op.op==='entity-delete'){const list=atPath(root,op.path);if(!Array.isArray(list))throw new Error('Journal entity path is not an array');const index=list.findIndex(item=>String(item?.id)===String(op.id));if(op.op==='entity-delete'){if(index>=0)list.splice(index,1);continue;}if(op.op==='entity-set'){if(index>=0)list[index]=clone(op.value);else list.push(clone(op.value));continue;}if(index<0)throw new Error(`Journal entity missing: ${op.id}`);list[index]=applyMerge(list[index],op.patch);continue;}const parent=op.path.slice(0,-1).reduce((node,key)=>node[key],root),key=op.path.at(-1);if(op.op==='delete')delete parent[key];else if(op.op==='set')parent[key]=clone(op.value);else throw new Error(`Unknown journal op: ${op.op}`);}return root;}

export function appendJournalEntry(journal,{revision,updatedAt,ops}){if(!Number.isSafeInteger(revision)||revision<1)throw new Error('Invalid journal revision');const next=journal&&journal.version===1?journal:{version:1,baseRevision:Math.max(0,revision-1),entries:[]};next.entries.push({revision,updatedAt,ops});return next;}
export function replayJournal(base,journal,{baseRevision=0}={}){if(!journal)return{payload:clone(base),revision:baseRevision};if(journal.version!==1||journal.baseRevision!==baseRevision)throw new Error('Journal base revision mismatch');let payload=clone(base),revision=baseRevision;for(const entry of journal.entries){if(entry.revision<=revision)continue;if(entry.revision!==revision+1)throw new Error('Journal revision gap');payload=applyIncrementalPatch(payload,entry.ops);revision=entry.revision;}return{payload,revision};}
export function journalBytes(journal){return new TextEncoder().encode(JSON.stringify(journal||null)).byteLength;}
export function shouldCompactJournal(journal,{maxEntries=24,maxBytes=900_000}={}){return(journal?.entries?.length||0)>=maxEntries||journalBytes(journal)>=maxBytes;}
