import {CAUSAL_ANSWERS} from '@soul/game-data';
import {BASIC_FORMS} from '@soul/game-data/combat-forms';
import {rinnePrimaryFourMarkup} from '@soul/shared-ui/rinne-primary-four';
import {techniqueDetail as sharedTechniqueDetail} from '@soul/johakyu-battle';
import {createRinneHeartComposition,createRinneLoadoutDetail,createRinneLoadoutGridItem,createRinneLoadoutGridSection,createRinneLoadoutSlot,createRinneLoadoutSlotRow,createRinneMenuLead,createRinneSwapHint,rinneLoadoutPanelMarkup,rinneSkillSigilKind,drawRinneTechniqueSelectionLink} from '@soul/shared-ui/rinne-loadout-menu';
import {BATTLE2_TECHNIQUE_CATALOG,battle2TechniqueCatalog,battle2LearnedTechniqueRows,battle2SelectionAllowed,battle2SelectionLabel,battle2TechniqueLabel} from './battle2-technique-catalog.js';

const STORAGE_KEY='battle2.loadout.v1';
const LEARNED_STORAGE_KEY='battle2.learned-techniques.v1';
const HEART_LIMIT=5;
const PHASES=Object.freeze([['jo','序'],['ha','破'],['kyu','急']]);
const WEAPON_LABELS=Object.freeze({fist:'素手',sword:'剣',dagger:'短剣',great:'大剣',spear:'槍',axe:'戦斧',staff:'杖'});
export const BATTLE2_WEAPONS=Object.freeze(Object.keys(BASIC_FORMS).map(id=>Object.freeze({id,label:WEAPON_LABELS[id]||id})));
const BATTLE2_WEAPON_IDS=new Set(BATTLE2_WEAPONS.map(row=>row.id));

export const BATTLE2_HEART_OPTIONS=Object.freeze(CAUSAL_ANSWERS.filter(row=>row.kind==='heart'&&!row.executor).map(row=>Object.freeze({id:row.id,label:row.name,meta:row.mechanic||'戦いの心得'})));
export const BATTLE2_TECHNIQUE_OPTIONS=Object.freeze(Object.fromEntries(PHASES.map(([phase])=>[phase,Object.freeze(BATTLE2_TECHNIQUE_CATALOG.map(row=>Object.freeze({id:row.id,label:row.label,meta:row.meta})))])));
export const BATTLE2_BODY_OPTIONS=Object.freeze({
  stance:Object.freeze([
    Object.freeze({id:'seigan',label:'正眼',meta:'癖のない基本構え'}),
    Object.freeze({id:'chinshin',label:'沈身',meta:'受けを厚くする'}),
    Object.freeze({id:'ryu',label:'流構え',meta:'角度を変え続ける'}),
    Object.freeze({id:'kosei',label:'攻勢',meta:'前へ圧を掛ける'})
  ]),
  finisher:Object.freeze([
    Object.freeze({id:'kaishaku',label:'介錯',meta:'確実にトドメを刺す',durationScale:1,impactAt:.58}),
    Object.freeze({id:'sokudan',label:'即断',meta:'短く終えて次へ移る',durationScale:.78,impactAt:.52}),
    Object.freeze({id:'kakudan',label:'確断',meta:'周囲を見切って終える',durationScale:1.08,impactAt:.6}),
    Object.freeze({id:'danzetsu',label:'断絶',meta:'重い一撃で終える',durationScale:1.16,impactAt:.62})
  ]),
  zanshin:Object.freeze([
    Object.freeze({id:'still',label:'静止残心',meta:'崩さず戻る'}),
    Object.freeze({id:'breath',label:'呼吸残心',meta:'戻りを速める'}),
    Object.freeze({id:'pursuit',label:'追い残心',meta:'一歩だけ追う'}),
    Object.freeze({id:'guard',label:'守り残心',meta:'守りへ戻る'})
  ])
});
export const BATTLE2_LOADOUT_DEFAULT=Object.freeze({
  heart:Object.freeze({active:Object.freeze(['skill.observe','skill.patience','skill.edge'])}),
  technique:Object.freeze({jo:'basic.sword',ha:'basic.sword',kyu:'basic.sword'}),
  body:Object.freeze({stance:'seigan',finisher:'kaishaku',zanshin:'still'}),
  equipment:Object.freeze({weapon:'sword',shield:false})
});
const HEART_IDS=new Set(BATTLE2_HEART_OPTIONS.map(row=>row.id));
const optionIds=kind=>new Set((BATTLE2_BODY_OPTIONS[kind]||[]).map(row=>row.id));
const clone=value=>JSON.parse(JSON.stringify(value));
const labelFor=(rows,id)=>rows.find(row=>row.id===id)?.label||battle2TechniqueLabel(id)||id||'未設定';

export function normalizeBattle2Loadout(value={}){
  const legacy=Array.isArray(value?.heart?.active)?value.heart.active.filter(id=>HEART_IDS.has(id)).slice(0,HEART_LIMIT):[];
  const rawSlots=Array.isArray(value?.heart?.slots)?value.heart.slots.slice(0,HEART_LIMIT):(legacy.length?legacy:BATTLE2_LOADOUT_DEFAULT.heart.active);
  const seen=new Set(),slots=Array.from({length:HEART_LIMIT},(_,index)=>{const id=rawSlots[index];if(!HEART_IDS.has(id)||seen.has(id))return null;seen.add(id);return id;});
  const active=slots.filter(Boolean);
  const technique=Object.fromEntries(PHASES.map(([phase])=>{const chosen=value?.technique?.[phase],candidate=String(chosen).startsWith('basic.')?`basic.${value?.equipment?.weapon||'sword'}`:chosen;return[phase,battle2SelectionAllowed(candidate,{weapon:value?.equipment?.weapon||'sword'})?candidate:`basic.${value?.equipment?.weapon==='great'?'great':'sword'}`];}));
  const body={};
  for(const kind of ['stance','finisher','zanshin'])body[kind]=optionIds(kind).has(value?.body?.[kind])?value.body[kind]:BATTLE2_LOADOUT_DEFAULT.body[kind];
  const weapon=BATTLE2_WEAPON_IDS.has(value?.equipment?.weapon)?value.equipment.weapon:'sword';
  return{heart:{slots,active},technique,body,equipment:{weapon,shield:weapon==='sword'&&Boolean(value?.equipment?.shield)}};
}
export function battle2LoadoutKey(value){
  const row=normalizeBattle2Loadout(value),raw=[row.heart.active.join('.'),row.technique.jo,row.technique.ha,row.technique.kyu,row.body.stance,row.body.finisher,row.body.zanshin,row.equipment.weapon,row.equipment.shield?'shield':'bare'].join('~');
  let hash=2166136261;for(let i=0;i<raw.length;i++){hash^=raw.charCodeAt(i);hash=Math.imul(hash,16777619);}
  return(hash>>>0).toString(36).padStart(7,'0').slice(-7);
}
function readStored(){
  try{return normalizeBattle2Loadout(JSON.parse(globalThis.localStorage?.getItem(STORAGE_KEY)||'{}'));}catch{return normalizeBattle2Loadout();}
}
function writeStored(value){try{globalThis.localStorage?.setItem(STORAGE_KEY,JSON.stringify(value));}catch{}}
function readLearned(){
  try{const raw=JSON.parse(globalThis.localStorage?.getItem(LEARNED_STORAGE_KEY)||'[]');return [...new Set((Array.isArray(raw)?raw:[]).map(String).filter(Boolean))];}catch{return[];}
}
function writeLearned(ids){try{globalThis.localStorage?.setItem(LEARNED_STORAGE_KEY,JSON.stringify(ids));}catch{}}
export function createBattle2LoadoutUI({stage,onChange=()=>{}}={}){
  if(!stage)throw new TypeError('battle2 stage required');
  let value=readStored(),learnedTechniqueIds=readLearned(),section='',heartTarget=0,techniqueTarget='jo',techniqueTab='basic',bodyTarget='stance',equipmentTarget='weapon',swap=null;
  const preview={heart:null,technique:null,body:null,equipment:null},haptic=pattern=>{try{globalThis.navigator?.vibrate?.(pattern);}catch{}};
  const shell=document.createElement('div');shell.className='battle2-loadout-shell';shell.innerHTML=rinnePrimaryFourMarkup({ariaLabel:'心技体装',extraClass:'battle2-loadout-nav'})+rinneLoadoutPanelMarkup({layout:'loadout'});stage.append(shell);
  const nav=shell.querySelector('.battle2-loadout-nav'),panel=shell.querySelector('[data-panel]'),title=panel.querySelector('[data-title]'),body=panel.querySelector('[data-body]'),navButtons={heart:nav.querySelector('[data-heart]'),technique:nav.querySelector('[data-techniques]'),body:nav.querySelector('[data-body]'),items:nav.querySelector('[data-items]')};
  const emit=()=>{const scrollTop=body.querySelector('.loadout-library')?.scrollTop||0;value=normalizeBattle2Loadout(value);writeStored(value);onChange(clone(value));render();body.querySelector('.loadout-library')?.scrollTo(0,scrollTop);};
  const appendSlots=(rows,activeKey,{onSelect,onLongPress=null,swapMode=false,layout=''}={})=>{const slots=createRinneLoadoutSlotRow({swapMode,layout});for(const row of rows)slots.append(createRinneLoadoutSlot({label:row.label,value:row.value,meta:row.meta,selected:row.id===activeKey,icon:row.icon||'empty',swapMode,swapSource:swapMode&&String(row.id)===String(swap?.source),onClick:()=>onSelect?.(row.id),onLongPress:onLongPress?()=>onLongPress(row.id):null}));body.append(layout==='pentagon'?createRinneHeartComposition(slots,value.heart.slots,id=>labelFor(BATTLE2_HEART_OPTIONS,id),{compact:true}):slots);};
  const appendLibrary=(titleText,copy,rows,{focusId=null,onSelect}={})=>{const library=createRinneLoadoutGridSection(titleText,copy),grid=library.querySelector('.loadout-grid');for(const row of rows)grid.append(createRinneLoadoutGridItem({label:row.label,meta:row.meta,active:row.active,focus:String(focusId||'')===String(row.id),icon:row.icon||rinneSkillSigilKind(row.id),onClick:()=>{const scrollTop=library.scrollTop;onSelect?.(row.id,row);body.querySelector('.loadout-library')?.scrollTo(0,scrollTop);}}));body.append(library);};
  const appendDetail=(detail,{actionLabel,actionDisabled=false,onAction}={})=>body.append(createRinneLoadoutDetail({...detail,actionLabel,actionDisabled,onAction}));
  const selectionDetail=selection=>({icon:rinneSkillSigilKind(selection),...sharedTechniqueDetail(selection,{weapon:value.equipment.weapon,name:battle2SelectionLabel(selection),kicker:selection?.startsWith('basic.')?'基本技':'閃いた連技',status:'習得済み'})});

  function renderHeart(){title.textContent='心 · 心得';body.replaceChildren(createRinneMenuLead('戦闘で意識する心得を5つまで選ぶ'));const heartSlots=value.heart.slots;if(!preview.heart)preview.heart=heartSlots[heartTarget]||BATTLE2_HEART_OPTIONS[0]?.id||null;const swapActive=swap?.section==='heart',slots=Array.from({length:HEART_LIMIT},(_,index)=>{const id=heartSlots[index];return{id:String(index),label:'心得 '+(index+1),value:labelFor(BATTLE2_HEART_OPTIONS,id),meta:index===heartTarget?'選択先':'意識中',icon:rinneSkillSigilKind(id)};});appendSlots(slots,String(heartTarget),{swapMode:swapActive,layout:'pentagon',onLongPress:id=>{const index=Number(id)||0;if(!heartSlots[index])return;swap={section:'heart',source:String(index)};haptic([18]);renderHeart();},onSelect:id=>{const index=Number(id)||0;if(swapActive){const source=Number(swap.source)||0;if(source!==index){const next=[...heartSlots],a=next[source],b=next[index];next[source]=b;next[index]=a;value.heart.slots=next;value.heart.active=next.filter(Boolean);}swap=null;heartTarget=index;haptic(18);emit();return;}heartTarget=index;preview.heart=heartSlots[index]||preview.heart;renderHeart();}});if(swapActive)body.append(createRinneSwapHint('入れ替える心得枠を選択'));const row=BATTLE2_HEART_OPTIONS.find(item=>item.id===preview.heart);if(row){const current=heartSlots[heartTarget]===row.id;appendDetail({icon:rinneSkillSigilKind(row.id),kicker:'心得',title:row.label,summary:row.meta,status:value.heart.active.includes(row.id)?'意識中':'習得済み'},{actionLabel:current?'設定済み':`心得${heartTarget+1}にセット`,actionDisabled:current,onAction:()=>{const next=[...heartSlots],existing=next.indexOf(row.id),displaced=next[heartTarget]||null;next[heartTarget]=row.id;if(existing>=0&&existing!==heartTarget)next[existing]=displaced;value.heart.slots=next;value.heart.active=next.filter(Boolean);haptic(12);emit();}});}appendLibrary('心得一覧','候補を選ぶと詳細を表示',BATTLE2_HEART_OPTIONS.map(item=>({...item,active:heartSlots[heartTarget]===item.id,icon:rinneSkillSigilKind(item.id)})),{focusId:preview.heart,onSelect:id=>{preview.heart=id;renderHeart();}});}

  function techniqueTabs(){const tabs=document.createElement('nav');tabs.className='loadout-technique-tabs';tabs.setAttribute('aria-label','技一覧の表示');for(const [id,label] of [['basic','基本技'],['learned','閃いた連技']]){const button=document.createElement('button');button.type='button';button.textContent=label;button.dataset.active=String(techniqueTab===id);button.onclick=()=>{techniqueTab=id;renderTechnique();};tabs.append(button);}return tabs;}
  function renderTechnique(){title.textContent='技 · 序破急';body.replaceChildren(createRinneMenuLead('基本技または閃いた連技を、序・破・急へセットする'));if(!preview.technique){preview.technique=value.technique[techniqueTarget];}const swapActive=swap?.section==='technique',slots=PHASES.map(([phase,label])=>{const selection=value.technique[phase];return{id:phase,label,value:battle2SelectionLabel(selection),meta:phase===techniqueTarget?'選択先':'装着中',icon:rinneSkillSigilKind(selection)};});appendSlots(slots,techniqueTarget,{swapMode:swapActive,onLongPress:id=>{swap={section:'technique',source:id};haptic([18]);renderTechnique();},onSelect:id=>{if(swapActive){const source=swap.source;if(source!==id){const a=value.technique[source],b=value.technique[id];value.technique[source]=b;value.technique[id]=a;}swap=null;techniqueTarget=id;preview.technique=value.technique[id];haptic(18);emit();return;}techniqueTarget=id;preview.technique=value.technique[id];renderTechnique();}});if(swapActive)body.append(createRinneSwapHint('入れ替える序破急枠を選択'));const current=value.technique[techniqueTarget],detail=selectionDetail(preview.technique);appendDetail({...detail,status:current===preview.technique?'装着中':detail.status},{actionLabel:current===preview.technique?'設定済み':`${PHASES.find(([phase])=>phase===techniqueTarget)?.[1]||'技'}にセット`,actionDisabled:current===preview.technique,onAction:()=>{value.technique[techniqueTarget]=preview.technique;haptic(12);emit();}});body.append(techniqueTabs());if(techniqueTab==='basic')appendLibrary('基本技一覧','武器の基本技',battle2TechniqueCatalog({weapon:value.equipment.weapon}).map(row=>({id:row.id,label:row.label,meta:row.meta,active:current===row.id,icon:rinneSkillSigilKind(row.id)})),{focusId:preview.technique,onSelect:id=>{preview.technique=id;renderTechnique();}});const learned=battle2LearnedTechniqueRows(learnedTechniqueIds,{weapon:value.equipment.weapon});if(techniqueTab==='learned'&&learned.length)appendLibrary('閃いた連技','候補を選ぶと詳細を表示',learned.map(row=>({id:row.id,label:row.label,meta:row.meta||'閃きで習得',active:current===row.id,icon:rinneSkillSigilKind(row.id)})),{focusId:preview.technique,onSelect:id=>{preview.technique=id;renderTechnique();}});if(techniqueTab==='learned'&&!learned.length){const library=createRinneLoadoutGridSection('閃いた連技','');const empty=document.createElement('p');empty.className='loadout-empty';empty.textContent='戦闘で閃いた連技がここに並びます';library.querySelector('.loadout-grid').append(empty);body.append(library);}globalThis.requestAnimationFrame?.(()=>drawRinneTechniqueSelectionLink(body));}

  function renderBody(){title.textContent='体 · 身法';body.replaceChildren(createRinneMenuLead('ゲーム仕様にある構え・葬焉・残心をまとめて選ぶ'));const labels={stance:'構え',finisher:'葬焉',zanshin:'残心'},nonlethal=value.heart.active.includes('skill.nonlethal'),slots=['stance','finisher','zanshin'].map(kind=>{const id=value.body[kind];return{id:kind,label:labels[kind],value:labelFor(BATTLE2_BODY_OPTIONS[kind],id),meta:kind==='finisher'&&nonlethal?'不殺の心得中 · 実行しない':(kind===bodyTarget?'選択先':'装着中'),icon:'stance'};});appendSlots(slots,bodyTarget,{onSelect:id=>{bodyTarget=id;preview.body={kind:id,id:value.body[id]};renderBody();}});const all=['stance','finisher','zanshin'].flatMap(kind=>BATTLE2_BODY_OPTIONS[kind].map(row=>({...row,kind,meta:labels[kind]+' · '+row.meta,active:value.body[kind]===row.id,icon:'stance'})));if(!preview.body)preview.body={kind:bodyTarget,id:value.body[bodyTarget]};const selected=all.find(row=>row.kind===preview.body.kind&&row.id===preview.body.id);if(selected){const current=value.body[selected.kind]===selected.id;appendDetail({icon:'stance',kicker:labels[selected.kind],title:selected.label,summary:selected.meta,status:current?'装着中':'習得済み'},{actionLabel:current?'設定済み':`${labels[selected.kind]}にセット`,actionDisabled:current,onAction:()=>{bodyTarget=selected.kind;value.body[selected.kind]=selected.id;haptic(10);emit();}});}appendLibrary('身法一覧','候補を選ぶと詳細を表示',all,{focusId:preview.body?.id,onSelect:(id,row)=>{bodyTarget=row.kind;preview.body={kind:row.kind,id};renderBody();}});}
  function renderItems(){title.textContent='装 · 武具';body.replaceChildren(createRinneMenuLead('装備変更は次の交換から即時反映'));const weaponLabel=value.equipment.weapon==='great'?'大剣':'剣',shieldLabel=value.equipment.shield?'盾あり':'盾なし',slots=[{id:'weapon',label:'武器',value:weaponLabel,meta:equipmentTarget==='weapon'?'選択先':'装備中',icon:'blade'},{id:'shield',label:'盾',value:shieldLabel,meta:equipmentTarget==='shield'?'選択先':'装備中',icon:'guard'},{id:'armor',label:'防具',value:'重装',meta:'固定',icon:'guard'}];appendSlots(slots,equipmentTarget,{onSelect:id=>{if(id==='armor')return;equipmentTarget=id;preview.equipment=null;renderItems();}});const rows=equipmentTarget==='shield'?[{id:'off',label:'盾なし',meta:'両手を自由に',icon:'guard',active:!value.equipment.shield},{id:'on',label:'盾あり',meta:'剣装備時のみ',icon:'guard',active:value.equipment.shield}]:BATTLE2_WEAPONS.map(row=>({id:row.id,label:row.label,meta:row.id==='fist'?'武器なし':row.id==='sword'?'片手武器':['dagger'].includes(row.id)?'軽量武器':'両手運用',icon:'blade',active:value.equipment.weapon===row.id}));if(!preview.equipment)preview.equipment=rows.find(row=>row.active)?.id||rows[0]?.id;const selected=rows.find(row=>row.id===preview.equipment);if(selected)appendDetail({icon:selected.icon,kicker:equipmentTarget==='shield'?'盾':'武器',title:selected.label,summary:selected.meta,status:selected.active?'装備中':'所持'},{actionLabel:selected.active?'設定済み':'装備する',actionDisabled:selected.active,onAction:()=>{if(equipmentTarget==='weapon'){value.equipment.weapon=selected.id;if(selected.id!=='sword')value.equipment.shield=false;}else value.equipment.shield=selected.id==='on'&&value.equipment.weapon==='sword';haptic(10);emit();}});appendLibrary(equipmentTarget==='shield'?'盾':'武器','候補を選ぶと詳細を表示',rows,{focusId:preview.equipment,onSelect:id=>{preview.equipment=id;renderItems();}});}
  function render(){for(const [key,node] of Object.entries(navButtons))node.dataset.active=String(section===key);panel.hidden=!section;if(!section){delete panel.dataset.type;return;}panel.dataset.type=section;if(section==='heart')renderHeart();else if(section==='technique')renderTechnique();else if(section==='body')renderBody();else renderItems();}
  for(const [key,node] of Object.entries(navButtons))node.onclick=()=>{section=section===key?'':key;swap=null;render();};panel.querySelector('[data-close]').onclick=()=>{section='';swap=null;render();};render();
  return Object.freeze({get value(){return clone(value);},get learnedTechniqueIds(){return learnedTechniqueIds.slice();},setWeapon(weapon){if(!BATTLE2_WEAPON_IDS.has(weapon)||value.equipment.weapon===weapon)return false;value={...value,equipment:{...value.equipment,weapon,shield:weapon==='sword'&&Boolean(value.equipment.shield)}};preview.equipment=null;preview.technique=null;emit();return true;},resetLearnedTechniques(){const learned=new Set(learnedTechniqueIds);if(!learned.size)return false;learnedTechniqueIds=[];writeLearned([]);const fallback=`basic.${value.equipment.weapon==='great'?'great':'sword'}`;value={...value,technique:Object.fromEntries(PHASES.map(([phase])=>[phase,learned.has(value.technique[phase])?fallback:value.technique[phase]]))};value=normalizeBattle2Loadout(value);writeStored(value);if(preview.technique&&learned.has(preview.technique))preview.technique=value.technique[techniqueTarget];if(section==='technique')renderTechnique();return true;},learnTechnique(id,phase=null){const row=battle2LearnedTechniqueRows([id],{weapon:value.equipment.weapon})[0];if(!row)return false;let changed=false;if(!learnedTechniqueIds.includes(row.id)){learnedTechniqueIds=[...learnedTechniqueIds,row.id];writeLearned(learnedTechniqueIds);changed=true;}if(PHASES.some(([key])=>key===phase)&&battle2SelectionAllowed(row.id,{weapon:value.equipment.weapon})){if(value.technique[phase]!==row.id){value.technique[phase]=row.id;writeStored(value);changed=true;}}if(section==='technique')renderTechnique();return changed;},close(){section='';swap=null;render();},destroy(){shell.remove();}});
}
