import {DEFAULTS,STEP_MS,normalizeConfig} from './config.js';
import {runComparison} from './engine.js';
import {compareRequirementEnvelope,runCanonNucleusProofSuite} from './canon-nucleus.js';
import {runSemanticFrontierProofSuite} from './semantic-frontier.js';
import {proveCatalogAgnosticClosure} from './frontier-closure.js';
import {PERFORMANCE_STATUS,evaluateRrpPerformanceContract,realityResultToPerformanceEvidence,runRrpPerformanceContractProofSuite} from './performance-contract.js';
import {runRrpTheoryVerificationSuite} from './theory-verification.js';

export const ARCHITECTURE_PROOF_MATRIX=Object.freeze([
  {id:'clean-spread',layout:'spread',scenario:'steady',durationMs:16000,latencyMs:0,jitterMs:0,loss:0},
  {id:'clean-dense',layout:'dense',scenario:'steady',durationMs:16000,latencyMs:0,jitterMs:0,loss:0},
  {id:'wan-spread',layout:'spread',scenario:'steady',durationMs:16000,latencyMs:80,jitterMs:20,loss:.01},
  {id:'adverse-dense',layout:'dense',scenario:'steady',durationMs:16000,latencyMs:240,jitterMs:120,loss:.08},
  {id:'host-clean',layout:'spread',scenario:'host',durationMs:24000,latencyMs:80,jitterMs:20,loss:0},
  {id:'host-lossy',layout:'spread',scenario:'host',durationMs:24000,latencyMs:180,jitterMs:80,loss:.05},
  {id:'cell-failure',layout:'spread',scenario:'cell',durationMs:16000,latencyMs:120,jitterMs:50,loss:.02},
  {id:'corruption',layout:'spread',scenario:'divergence',durationMs:16000,latencyMs:80,jitterMs:20,loss:0},
  {id:'collapse-revisit',layout:'dense',scenario:'collapse',durationMs:16000,latencyMs:120,jitterMs:50,loss:.02},
]);

function workloadFrom(result,config){const ticks=Math.max(1,Math.floor(config.durationMs/STEP_MS)),fanout=Math.max(1,config.peers-1);return Math.max(1,Math.ceil(result.payloadBytes/(ticks*fanout)));}
function findMode(results,mode){return results.find(row=>row.mode===mode);}
export function runArchitectureProofLoop(){
  const canon=runCanonNucleusProofSuite(),semantic=runSemanticFrontierProofSuite(),theory=runRrpTheoryVerificationSuite({semantic}),closure=proveCatalogAgnosticClosure(),performanceContract=runRrpPerformanceContractProofSuite(),cases=[];
  for(const spec of ARCHITECTURE_PROOF_MATRIX){
    const config=normalizeConfig({...DEFAULTS,peers:30,...spec}),results=runComparison(config),comparisons={},performance={};
    for(const result of results){const realtimeBytesPerTick=workloadFrom(result,config);comparisons[result.mode]=compareRequirementEnvelope({players:config.peers,ticks:Math.max(1,Math.floor(config.durationMs/STEP_MS)),realtimeBytesPerTick,canonEvents:4,canonBytesPerEvent:512,recoveryBytesPerCanon:16_384,reliableMultiplier:1+config.loss,pendingCanonActors:1});const evidence=realityResultToPerformanceEvidence(result,{scenario:spec.id}),evaluated=evaluateRrpPerformanceContract(evidence,{requirePhysicalCertification:true});performance[result.mode]={status:evaluated.status,evidenceClass:evaluated.evidenceClass,physicalCertificationEligible:evaluated.physicalCertificationEligible,metrics:evaluated.evidence.metrics};}
    const interest=findMode(results,'interest'),cells=findMode(results,'cells'),modelEvidenceHonest=Object.values(performance).every(row=>row.status!==PERFORMANCE_STATUS.FAIL&&row.evidenceClass==='model'&&row.physicalCertificationEligible===false);
    cases.push({id:spec.id,config,results,comparisons,performance,presence:{cellFanoutWin:Boolean(interest&&cells&&cells.maxPeerKbps<interest.maxPeerKbps*.9),cellLoadRatio:interest&&cells&&interest.maxPeerKbps?cells.maxPeerKbps/interest.maxPeerKbps:null},pass:modelEvidenceHonest&&results.every(row=>row.freezeViolations===0&&row.collapseMatchesReference)&&Object.values(comparisons).every(row=>row.pass)});
  }
  const dense=cases.find(row=>row.id==='clean-dense'),spread=cases.find(row=>row.id==='clean-spread'),host=cases.find(row=>row.id==='host-clean'),corruption=cases.find(row=>row.id==='corruption');
  const boundaries={denseCounterexampleRetained:Boolean(dense&&!dense.presence.cellFanoutWin),spreadBenefitRetained:Boolean(spread&&spread.presence.cellFanoutWin),hostRecoveryObserved:Boolean(host&&host.results.every(row=>row.phase==='open'&&row.migrations.length===1&&row.freezeViolations===0)),corruptionRepairObserved:Boolean(corruption&&corruption.results.every(row=>row.invalid===1&&row.repairs>=1)),universalStrictDominanceRejected:semantic.maximal.strictUniversalDominancePossible===false,semanticPolicyClosure:semantic.maximal.weakPolicyClosure===true,futurePolicyAbsorption:closure.pass===true,performanceContractHonest:performanceContract.pass&&cases.every(row=>Object.values(row.performance).every(perf=>perf.physicalCertificationEligible===false)),generalizedPacketRecoveryProved:theory.boundaries.generalizedPacketRecovery,sequentialEpochDedupeProved:theory.boundaries.sequentialEpochDedupe,packetInterleavingsProved:theory.boundaries.packetInterleavings,twoPeerWitnessBoundaryRetained:theory.boundaries.twoPeerNoWitnessBoundary,finiteBurstBoundaryRetained:theory.boundaries.finiteBurstEventuallyProgresses,quorumFencedEpochPromotion:theory.boundaries.quorumFencedEpochPromotion,minorityCannotPromoteCanon:theory.boundaries.minorityCannotPromoteCanon,invariantCompiledCoordination:theory.boundaries.invariantCompiledCoordination,proofCarryingPlanVerified:theory.boundaries.proofCarryingPlanVerified,fencedPolicyHandoff:theory.boundaries.fencedPolicyHandoff,denseRelayCandidateProved:theory.boundaries.denseRelayFanoutFrontier,relayTradeoffsRetained:theory.boundaries.relayNotUniversal};
  const pass=canon.pass&&semantic.pass&&theory.pass&&closure.pass&&performanceContract.pass&&cases.every(row=>row.pass)&&Object.values(boundaries).every(Boolean);
  return{format:'rrp-architecture-proof/7',pass,canon,semantic,theory,closure,performanceContract,cases,boundaries,limits:['model wire does not certify SCTP/NAT/TURN','model performance evidence cannot satisfy physical-multipeer certification','physical metrics without a justified threshold remain calibration-required','Semantic Frontier is a policy closure, not a claim of physically impossible universal strict dominance','CAP/FLP and crash/BFT lower bounds remain hard constraints','finite burst-loss liveness assumes eventual delivery after the burst; permanent partition remains unavailable for strong Canon','two-peer post-failure availability still requires an external failure discriminator/fence under arbitrary partition','quorum-fenced epoch promotion preserves Canon safety under false suspicion but does not guarantee bounded-time failure detection','invariant compilation only proves declared bounded resource/effect models; omitted application invariants remain outside the proof','policy handoff requires a durable fence and may trade availability for safety during transition','adaptive relay is presence-only and trades one extra hop/failure exposure for lower dense sender fan-out','unknown future algorithms gain no-regret coverage only after their guarantee/cost policy is registered','replaceable realtime state may roll back to the last accepted recovery boundary']};
}
