import './unified-review-nav.js';
import { modelPickerInitials, modelPickerPortrait, presentModelPickerRow, visibleModelPickerRows } from './model-picker-catalog.js';

export function installReviewUX({reviewPresets,reviewWeapons}){
  const q=s=>document.querySelector(s);
  const style=document.createElement('style');
  style.textContent=`
    .model-strip{overflow:visible!important}.model-strip .model-chip{display:none!important}.model-select-trigger{width:100%;min-width:0;min-height:38px;border:1px solid #d6bd8438;border-radius:11px;background:linear-gradient(180deg,#1b2128,#0e1217);color:#f0dfb3;padding:0 12px;font-size:10px;font-weight:750;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;text-align:left;box-shadow:inset 0 1px 0 #ffffff0b,0 4px 10px #0005}.model-select-trigger:after{content:'⌄';float:right;color:#d6bd84}
    .weapon-quick{display:flex;align-items:center;gap:5px;padding:6px 12px;border-bottom:1px solid var(--line);overflow:hidden}.weapon-quick>span{flex:0 0 auto;font-size:8px;color:#90a697}.weapon-scroll{display:flex;gap:4px;overflow-x:auto;scrollbar-width:none;min-width:0}.weapon-scroll::-webkit-scrollbar{display:none}.weapon-chip{flex:0 0 auto;min-height:29px;border:1px solid #ffffff14;border-radius:9px;background:linear-gradient(180deg,#1a2027,#0d1116);color:#91a99d;padding:0 10px;font-size:8px;box-shadow:inset 0 1px 0 #ffffff08}.weapon-chip.active{border-color:#d6bd8455;background:linear-gradient(180deg,#3a3423,#19170f);color:#f0dfb3}
    .motion-pair{grid-template-columns:1fr!important;gap:12px!important}.motion-pair>div{display:grid!important;grid-template-columns:1fr 1fr!important;gap:7px!important;padding:12px!important}.motion-pair label{grid-column:1/-1!important;font-size:10px!important;margin:0!important}.motion-pair .picker-trigger{grid-column:1/-1!important;min-height:44px!important;font-size:11px!important}.motion-pair .play-slot,.motion-pair .copy-slot{min-height:40px!important;width:100%!important;margin:0!important}.motion-pair .play-slot{grid-column:1}.motion-pair .copy-slot{grid-column:2}
    .review-page[data-review-page="reaction"] .single-review,.review-page[data-review-page="stance"] .single-review,.review-page[data-review-page="parry"] .single-review{grid-template-columns:minmax(0,1fr) 58px!important}.review-page[data-review-page="reaction"] .play-slot,.review-page[data-review-page="stance"] .play-slot,.review-page[data-review-page="parry"] .play-slot{display:none!important}.review-page[data-review-page="axis"] .stage-row{grid-template-columns:28px minmax(0,1fr) 46px!important}.review-page[data-review-page="axis"] .play-slot{display:none!important}.review-page[data-review-page="axis"] .copy-slot{min-height:37px!important}.instant-note{font-size:8px;color:#8da49a;margin:5px 0 0}.instant-note:before{content:'選ぶと即再生';color:#d6bd84;margin-right:5px}
    .model-picker-backdrop{position:fixed;z-index:70;inset:0;background:#020305c9;display:flex;align-items:flex-end;backdrop-filter:blur(8px)}.model-picker-sheet{width:min(980px,100%);max-height:82dvh;margin:0 auto;background:linear-gradient(180deg,#171c22,#090c10);border:1px solid #d6bd8435;border-bottom:0;border-radius:22px 22px 0 0;padding-bottom:env(safe-area-inset-bottom);box-shadow:0 -24px 80px #000e}.model-picker-sheet header{height:52px;display:flex;align-items:center;justify-content:space-between;padding:0 14px;border-bottom:1px solid #ffffff10}.model-picker-sheet header strong{font:750 14px ui-sans-serif,system-ui;color:#f0dfb3}.model-picker-sheet header button{min-height:34px;padding:0 11px;border:1px solid #ffffff13;border-radius:9px;background:linear-gradient(180deg,#1a2027,#0d1116);color:#a9b9ae}.model-picker-list{max-height:calc(82dvh - 52px);overflow:auto;display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px;padding:10px}.model-picker-item{min-width:0;min-height:126px;display:grid;grid-template-rows:72px auto;gap:8px;align-content:start;text-align:center;border:1px solid #ffffff10;border-radius:14px;background:linear-gradient(155deg,#1a2027,#0d1116);color:#e9e2cd;padding:9px;box-shadow:inset 0 1px 0 #ffffff0a,0 5px 12px #0006}.model-picker-item.active{border-color:#d6bd8466;background:linear-gradient(155deg,#3a3424,#17150f);box-shadow:inset 0 1px 0 #fff4ce25,inset 0 0 0 1px #d6bd8417}.model-picker-portrait{width:68px;height:68px;justify-self:center;display:grid!important;place-items:center;overflow:hidden!important;border-radius:13px;background:#0b1014;box-shadow:0 5px 14px #0008}.model-picker-portrait img{width:100%;height:100%;object-fit:cover;background:#0b1014}.model-picker-portrait img[data-focus="face"]{transform:scale(2.15);transform-origin:50% 18%}.model-picker-portrait-fallback{width:100%;height:100%;display:grid!important;place-items:center;background:radial-gradient(circle at 50% 34%,#3a4650 0 22%,#1a2229 23% 42%,#0d1217 43%);color:#b8c0c5;font:800 12px/1 ui-sans-serif,system-ui;letter-spacing:.08em}.model-picker-copy{min-width:0;overflow:hidden;text-overflow:ellipsis;font-size:10px;line-height:1.25}.model-picker-copy small{display:block;color:#7d878e;font-size:7px;margin-top:3px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.model-picker-item.active .model-picker-copy{color:#f1dfaa}
    .review-library-nav{margin-left:auto;display:flex;gap:6px;pointer-events:auto}.review-reference-link{pointer-events:auto;display:inline-flex;align-items:center;justify-content:center;min-height:30px;padding:0 10px;border:1px solid #ffffff1f;border-radius:10px;background:linear-gradient(180deg,#1a2027,#0d1116);color:#e5d39d;text-decoration:none;font-size:9px;font-weight:800;letter-spacing:.03em;box-shadow:inset 0 1px 0 #ffffff09,0 4px 12px #0005}.review-reference-link:active{transform:translateY(1px)}
    @media(max-width:679px){.model-picker-list{grid-template-columns:repeat(3,minmax(0,1fr))}.model-picker-item{min-height:116px;grid-template-rows:62px auto}.model-picker-portrait{width:58px;height:58px}}
    @media(max-width:430px){.model-picker-list{grid-template-columns:repeat(2,minmax(0,1fr));gap:6px;padding:8px}.model-picker-item{min-height:104px;grid-template-rows:54px auto;padding:7px}.model-picker-portrait{width:50px;height:50px}}
  `;
  document.head.append(style);
  if(!q('.review-library-nav')){const nav=document.createElement('nav');nav.className='review-library-nav';nav.setAttribute('aria-label','参考資料');const reference=document.createElement('a');reference.className='review-reference-link';reference.href='./references.html';reference.textContent='参考';reference.setAttribute('aria-label','キャラクター参考資料を開く');nav.append(reference);q('.topbar')?.append(nav);}
  const preset=q('#preset'),strip=q('.model-strip');
  if(strip&&preset){
    const trigger=document.createElement('button');trigger.type='button';trigger.className='model-select-trigger';trigger.textContent='キャラ: Sendagaya Shino';strip.append(trigger);
    const backdrop=document.createElement('div');backdrop.className='model-picker-backdrop';backdrop.hidden=true;backdrop.innerHTML='<section class="model-picker-sheet"><header><strong>キャラクターを選ぶ</strong><button type="button">閉じる</button></header><div class="model-picker-list"></div></section>';document.body.append(backdrop);const list=backdrop.querySelector('.model-picker-list'),close=backdrop.querySelector('header button');
    function allRows(){const rows=new Map(reviewPresets.map(row=>[row.id,presentModelPickerRow(row)]));for(const option of preset.options){if(!option.value||rows.has(option.value))continue;const label=option.textContent||option.value;rows.set(option.value,presentModelPickerRow({id:option.value,label,name:label}));}return [...rows.values()];}
    function selectableRows(){return visibleModelPickerRows(allRows());}
    function rowForPreset(id){return allRows().find(row=>row.id===id)||null;}
    function activeRow(){const rows=allRows(),current=rows.find(row=>row.id===preset.value);if(current?.pickerCanonicalId)return rows.find(row=>row.id===current.pickerCanonicalId)||selectableRows()[0];if(current&&!current.pickerHidden)return current;return selectableRows()[0];}
    function portraitNode(row){const holder=document.createElement('span');holder.className='model-picker-portrait';const fallback=()=>{const node=document.createElement('span');node.className='model-picker-portrait-fallback';node.textContent=modelPickerInitials(row);node.setAttribute('aria-hidden','true');return node;};const src=modelPickerPortrait(row);if(!src){holder.append(fallback());return holder;}const image=document.createElement('img');image.src=src;image.alt='';if(row.portraitFocus)image.dataset.focus=row.portraitFocus;image.addEventListener('error',()=>holder.replaceChildren(fallback()),{once:true});holder.append(image);return holder;}
    function render(){const rows=selectableRows(),active=activeRow();list.replaceChildren(...rows.map(row=>{const b=document.createElement('button');b.type='button';b.className='model-picker-item'+(row.id===active?.id?' active':'');const copy=document.createElement('span');copy.className='model-picker-copy';copy.textContent=row.name||row.label;const meta=document.createElement('small');meta.textContent=row.pickerLabel||row.label||row.id;copy.append(meta);b.append(portraitNode(row),copy);b.onclick=()=>{preset.value=row.id;preset.dispatchEvent(new Event('change',{bubbles:true}));trigger.textContent=`キャラ: ${row.name||row.label}`;backdrop.hidden=true;render();};return b;}));}
    trigger.onclick=()=>{render();backdrop.hidden=false;};close.onclick=()=>backdrop.hidden=true;backdrop.addEventListener('click',e=>{if(e.target===backdrop)backdrop.hidden=true;});document.addEventListener('review-model-loaded',e=>{const row=rowForPreset(e.detail?.presetId);if(row)trigger.textContent=`キャラ: ${row.name||row.label}`;});
  }
  const tabs=q('.review-tabs'),weaponSelect=q('#weapon-select'),weaponToggle=q('#weapon-toggle');
  if(tabs&&weaponSelect&&weaponToggle){const bar=document.createElement('div');bar.className='weapon-quick';bar.innerHTML='<span>武器</span><div class="weapon-scroll"></div>';const scroll=bar.querySelector('.weapon-scroll');const defs=[{id:'none',label:'なし'},...reviewWeapons];const setWeapon=id=>{const enabled=id!=='none';weaponToggle.checked=enabled;if(enabled){weaponSelect.value=id;weaponSelect.dispatchEvent(new Event('input',{bubbles:true}));weaponSelect.dispatchEvent(new Event('change',{bubbles:true}));}weaponToggle.dispatchEvent(new Event('input',{bubbles:true}));scroll.querySelectorAll('.weapon-chip').forEach(b=>b.classList.toggle('active',b.dataset.weapon===id));};defs.forEach((row,i)=>{const b=document.createElement('button');b.type='button';b.className='weapon-chip'+(i===0?' active':'');b.dataset.weapon=row.id;b.textContent=row.label;b.onclick=()=>setWeapon(row.id);scroll.append(b);});tabs.after(bar);}
  const immediateIds=new Set(['reaction-select','stance-select','parry-select','axis-shin','axis-gi','axis-tai']);document.addEventListener('change',event=>{const select=event.target;if(!(select instanceof HTMLSelectElement)||!select.classList.contains('review-select')||!immediateIds.has(select.id)||!select.value)return;const master=q('#clip');if(!master)return;master.value=select.value;master.dispatchEvent(new Event('change',{bubbles:true}));});for(const page of ['reaction','stance','parry','axis']){const node=q(`[data-review-page="${page}"]`);if(node&&!node.querySelector('.instant-note')){const note=document.createElement('p');note.className='instant-note';note.textContent='候補をグリッドからタップして比較できます。';node.append(note);}}
}