import test from 'node:test';
import assert from 'node:assert/strict';
import {compileMotionLayerPlan,MOTION_LAYER_CONTRACTS,createSemanticMotionTimeline,semanticEventsBetween,predictMotionTrajectory,rankPoseCandidates,selectPoseCandidate,motionVariationProfile,resolveInteractionSchema,weaponContactConstraint,ragdollBlendBridge,personalSpaceSteering} from '../src/motion-orchestration.js';

test('layer plan is deterministic and preserves contact/ground ordering',()=>{const p=compileMotionLayerPlan();assert.deepEqual(p.order,MOTION_LAYER_CONTRACTS.map(x=>x.id));assert.ok(p.order.indexOf('interaction')<p.order.indexOf('ground-contact'));assert.ok(p.order.indexOf('ground-contact')<p.order.indexOf('weapon-sockets'));});
test('layer plan rejects cycles, unknown dependencies, conflicting exclusive writers and authority ownership',()=>{assert.throws(()=>compileMotionLayerPlan({layers:[{id:'a',dependsOn:['b'],writes:[]},{id:'b',dependsOn:['a'],writes:[]}]}));assert.throws(()=>compileMotionLayerPlan({layers:[{id:'a',dependsOn:['missing'],writes:[]}]}));assert.throws(()=>compileMotionLayerPlan({layers:[{id:'a',dependsOn:[],writes:[{scope:'x',mode:'exclusive'}]},{id:'b',dependsOn:['a'],writes:[{scope:'x',mode:'exclusive'}]}]}));assert.throws(()=>compileMotionLayerPlan({layers:[{id:'bad',dependsOn:[],writes:[{scope:'damage',mode:'exclusive'}]}]}));});
test('semantic timeline keeps gameplay contact external and queries stable events',()=>{const t=createSemanticMotionTimeline({duration:.66,contactPhase:.5,activeStart:.42,activeEnd:.58});const contact=t.events.find(e=>e.name==='contact');assert.equal(contact.seconds,.33);assert.equal(t.contactAuthority,'gameplay-external');assert.deepEqual(semanticEventsBetween(t,.25,.36).map(x=>x.name),['weapon-release','contact']);});
test('predictive locomotion is bounded advisory data',()=>{const p=predictMotionTrajectory({position:{x:0,z:0},velocity:{x:0,z:0},intent:{x:0,z:4},horizon:.4,steps:4});assert.equal(p.points.length,4);assert.equal(p.advisory,true);assert.ok(p.points.at(-1).z>0);assert.throws(()=>predictMotionTrajectory({horizon:2}));});
test('pose search ranks continuity and trajectory deterministically',()=>{const query={state:'move',speed:1,yaw:0,supportSide:'left',trajectory:[{x:0,z:.2},{x:0,z:.4}]},candidates=[{id:'b',state:'move',speed:1,yaw:0,supportSide:'left',continuity:.9,trajectory:[{x:0,z:.21},{x:0,z:.41}]},{id:'a',state:'idle',speed:0,yaw:1,supportSide:'right',continuity:.1,trajectory:[{x:.4,z:0},{x:.8,z:0}]}]};const ranked=rankPoseCandidates(query);assert.equal(ranked[0].id,'b');assert.equal(selectPoseCandidate(query).id,'b');});
test('motion variation is stable per character and never changes contact timing',()=>{const a=motionVariationProfile('hero'),b=motionVariationProfile('hero'),c=motionVariationProfile('other');assert.deepEqual(a,b);assert.notEqual(a.idlePhase,c.idlePhase);assert.equal(a.contactTimingScale,1);assert.equal(a.authoritativeTimingChanged,false);});
test('interaction schemas require explicit partner and anchors',()=>{const r=resolveInteractionSchema('blade-clash',{partner:{id:'enemy'},anchors:{self:{x:0,y:1,z:0},partner:{x:1,y:1,z:0}}});assert.equal(r.schema.id,'blade-clash');assert.equal(r.inferred,false);assert.throws(()=>resolveInteractionSchema('hug',{partner:{id:'x'}}));});
test('weapon contact stays bounded and presentation-only',()=>{const c=weaponContactConstraint({normal:{x:1,z:0},penetration:.05,relativeSpeed:4,weaponMass:1.5});assert.ok(c.deflection<=.14);assert.ok(Math.abs(c.recoilOffset.x)<=.08);assert.equal(c.damageAuthority,false);});
test('ragdoll bridge refuses fake physics and only blends when adapter exists',()=>{assert.equal(ragdollBlendBridge({requested:true,physicsAvailable:false}).reason,'physics-adapter-unavailable');const r=ragdollBlendBridge({requested:true,physicsAvailable:true,impact:.8});assert.equal(r.state,'physics');assert.equal(r.enabled,true);});
test('personal-space result is advisory and bounded',()=>{const s=personalSpaceSteering({position:{x:0,z:0},preferredVelocity:{x:1,z:0},neighbors:[{x:.1,z:0}],radius:.7,maxSuggestion:.2});assert.equal(s.worldAuthority,false);assert.ok(Math.hypot(s.suggestion.x,s.suggestion.z)<=.200001);});
