import test from 'node:test';
import assert from 'node:assert/strict';
import {buildPoseCandidateBank,selectPoseStart,routeSemanticPresentationEvent,explicitInteractionAdapter,sweptWeaponContactEvidence,personalSpaceNavigationBias,createMotionDeviceCalibration} from '../src/motion-operationalization.js';

test('candidate bank builds deterministic start frames and pose selection stays advisory',()=>{const bank=buildPoseCandidateBank({fps:60,samplesPerClip:3,clips:[{id:'walk-left',state:'move',duration:1,speed:1,yaw:0,supportSide:'left',continuity:.9},{id:'idle',state:'idle',duration:1,speed:0,yaw:0,supportSide:'right'}]});assert.equal(bank.candidates.length,6);const pick=selectPoseStart({state:'move',speed:1,yaw:0,supportSide:'left',trajectory:[{x:0,z:.4}],bank});assert.equal(pick.clipId,'walk-left');assert.equal(pick.advisory,true);assert.equal(pick.gameplayAuthority,false);assert.ok(pick.ranked.length<=5);});
test('semantic routes only presentation consumers and contact remains gameplay external',()=>{const calls=[];const result=routeSemanticPresentationEvent({name:'contact',actorId:'hero'},{camera:e=>calls.push(['camera',e]),audio:e=>calls.push(['audio',e]),'weapon-vfx':e=>calls.push(['vfx',e])});assert.equal(calls.length,3);assert.equal(result.event.contactAuthority,'gameplay-external');assert.equal(result.gameplayAuthority,false);assert.throws(()=>routeSemanticPresentationEvent({name:'damage'}));});
test('interaction adapter requires explicit partner and anchors',()=>{const args={partner:{id:'npc'},anchors:{self:{x:0,y:1,z:0},partner:{x:.8,y:1,z:0}}};const adapter=explicitInteractionAdapter('hug',args);assert.equal(adapter.partnerId,'npc');assert.equal(adapter.explicit,true);assert.equal(adapter.mayInferPartner,false);assert.throws(()=>explicitInteractionAdapter('hug',{partner:{id:'npc'}}));});
test('swept weapon evidence is presentation only and preserves hit serial',()=>{const evidence=sweptWeaponContactEvidence({point:{x:1,y:1,z:2},normal:{x:1,z:0},relativeSpeed:5,penetration:.03,weaponMass:1.2,hitSerial:17});assert.equal(evidence.hitSerial,17);assert.equal(evidence.damageAuthority,false);assert.equal(evidence.collisionAuthority,false);assert.ok(evidence.constraint.deflection>0);});
test('personal space remains opt-in advisory navigation bias',()=>{const bias=personalSpaceNavigationBias({position:{x:0,z:0},preferredVelocity:{x:1,z:0},neighbors:[{x:.1,z:0}],radius:.7,maxSuggestion:.2});assert.equal(bias.accepted,false);assert.equal(bias.consumerMustOptIn,true);assert.equal(bias.worldAuthority,false);assert.ok(Math.hypot(bias.suggestion.x,bias.suggestion.z)<=.200001);});
test('device calibration never mistakes a design budget for physical measurement',()=>{const design=createMotionDeviceCalibration({deviceClass:'pixel-fold-class-30',physicalDevice:false,cohort:12,sampleCount:100,totalMeanMs:4.2,layers:[{layer:'ik',meanMs:1,maxMs:2}]});assert.equal(design.measuredHardware,false);assert.equal(design.designBudgetIsMeasurement,false);const measured=createMotionDeviceCalibration({deviceClass:'Pixel Fold',physicalDevice:true,userAgent:'Android Pixel Fold',refreshHz:60,cohort:12,sampleCount:300,totalMeanMs:4.8,layers:[{layer:'ik',meanMs:1.1,maxMs:2.4}]});assert.equal(measured.measuredHardware,true);});
