import test from 'node:test';
import assert from 'node:assert/strict';
import {createMotionProfiler,buildMotionReviewPlan,validateMotionReviewPlan,attachMotionReviewPlan,motionDebugOverlayData,reviewRepairRequest} from '../src/motion-review-planner.js';

test('profiler recommends presentation LOD without disabling gameplay',()=>{const p=createMotionProfiler({budgetMs:2});p.record('secondary',1.4);p.record('secondary',1.2);p.record('gaze',1);const s=p.snapshot();assert.equal(s.overBudget,true);assert.notEqual(s.lodRecommendation,'full');assert.equal(s.mayDisableGameplay,false);assert.equal(s.authority,'presentation-only');});
test('review planner prioritizes contact, balance, frame and trajectory diagnostics but cannot approve or edit',()=>{const plan=buildMotionReviewPlan({revision:'abc',evidence:{frameSummary:{diagnosticPass:false,failed:2,worstChangedRatio:.2,worstJointDelta:.1},balance:{inside:false,margin:-.04},collision:{penetration:.02},semantic:{contactMismatch:true,expected:.5,actual:.56},perception:{readability:{weakestScore:.3},trajectory:{jitterFrames:[4,5]}}}});assert.equal(validateMotionReviewPlan(plan),plan);assert.equal(plan.visualApprovalRequired,true);assert.equal(plan.autoEditAllowed,false);assert.equal(plan.autoApproveAllowed,false);assert.equal(plan.next.kind,'semantic-contact-mismatch');});
test('foot slide jerk and measured device budget become review tasks without auto approval',()=>{const plan=buildMotionReviewPlan({revision:'ops',evidence:{footSliding:{failed:1,warnings:2,worst:{side:'left',maxDisplacement:.07}},jerk:{spikes:[{track:'weaponTip',kind:'angular',value:500,time:.4}]},deviceCalibration:{measuredHardware:true,deviceClass:'Pixel Fold',totalMeanMs:6.2,cohort:12},deviceBudgetMs:5.5}});assert.equal(plan.autoApproveAllowed,false);assert.ok(plan.tasks.some(t=>t.kind==='foot-slide'&&t.priority===5));assert.ok(plan.tasks.some(t=>t.kind==='motion-jerk'));assert.ok(plan.tasks.some(t=>t.kind==='device-motion-budget'));});
test('review plan attaches to existing QA without changing explicit visual approval',()=>{const report={schema:'character-motion-qa',version:1,visualApproval:'changes-requested'},plan=buildMotionReviewPlan({revision:'abc',issues:[{id:'x',severity:'warning',category:'motion',note:'jerk'}]}),next=attachMotionReviewPlan(report,plan);assert.equal(next.visualApproval,'changes-requested');assert.equal(next.motionReviewPlan,plan);assert.throws(()=>validateMotionReviewPlan({...plan,autoApproveAllowed:true}));});
test('debug overlay carries extended diagnostic geometry only',()=>{const d=motionDebugOverlayData({centerOfMass:{x:0,y:1,z:0},supports:[{x:-.1,z:0},{x:.1,z:0}],trajectory:{points:[{x:0,z:.2},{x:0,z:.4}]},interaction:{schema:'hug',partnerId:'p2',anchors:{}},hitDirection:{x:1,z:0},semanticEvents:[{name:'contact',phase:.5,seconds:.33}],weaponArc:[{x:0,y:1,z:0},{x:.3,y:1,z:.2}],warpWindow:{start:.18,contact:.5},poseRanking:[{id:'walk@12',score:.2}],layerPlan:{order:['source-pose','qa'],exclusiveOwners:{}}});assert.equal(d.version,2);assert.equal(d.diagnosticOnly,true);assert.equal(d.futureTrajectory.length,2);assert.equal(d.weaponArc.length,2);assert.equal(d.poseRanking[0].id,'walk@12');assert.equal(d.semanticEvents[0].name,'contact');});
test('repair request stays review-only and requires recapture',()=>{const plan=buildMotionReviewPlan({revision:'abc',issues:[{id:'x',severity:'warning',category:'motion',note:'jerk'}]}),r=reviewRepairRequest(plan);assert.equal(r.action,'review');assert.equal(r.requiresRecapture,true);assert.equal(r.mayEditSource,false);assert.equal(r.visualApprovalRequired,true);assert.equal(reviewRepairRequest(buildMotionReviewPlan({revision:'ok'})).action,'none');});
