import {PREY,FORMS} from './world.js';
export const SAVE_KEY='kurai.nighthunt.v2';
export class SaveError extends Error {}
export function freshProfile(id){return{version:2,id,revision:0,sequence:0,visits:{},unlocked:[],equipped:[],form:'hollow',hunts:0,totalEaten:0,offers:[],imported:null,echo:null};}
export function validateProfile(p){if(!p||p.version!==2||typeof p.id!=='string'||!p.id||!Number.isSafeInteger(p.sequence)||p.sequence<0||!Number.isSafeInteger(p.revision)||!p.visits||Array.isArray(p.visits)||typeof p.visits!=='object'||!Array.isArray(p.unlocked)||!Array.isArray(p.equipped)||p.equipped.length>3||new Set(p.equipped.filter(Boolean)).size!==p.equipped.filter(Boolean).length||p.equipped.some(k=>k!==null&&(!p.unlocked.includes(k)||typeof k!=='string'))||!Array.isArray(p.offers)||p.revision<0||!Number.isSafeInteger(p.hunts)||p.hunts<0||!Number.isSafeInteger(p.totalEaten)||p.totalEaten<0||!Object.hasOwn(FORMS,p.form)||p.unlocked.some(k=>!Object.hasOwn(PREY,k))||new Set(p.unlocked).size!==p.unlocked.length)throw new SaveError('保存データを確認できません。上書きせず停止しました。');
 for(const [id,v] of Object.entries(p.visits))if(!id||!v||v.villageId!==id||!['entered','escaped','defeated','abandoned','completed'].includes(v.status))throw new SaveError('入村記録が壊れています。再訪防止のため入村を停止しました。');return p;}
export class ProfileStore {
 constructor(storage,idFactory=()=>{throw new SaveError('IDポートがありません。');},now=()=>Date.now()){this.storage=storage;this.idFactory=idFactory;this.now=now;}
 read(){let raw;try{raw=this.storage.getItem(SAVE_KEY);}catch{throw new SaveError('保存領域を利用できません。入村記録を残せないため開始できません。');}if(raw===null){const p=freshProfile(this.idFactory());this.write(p);return p;}try{return validateProfile(JSON.parse(raw));}catch(e){throw e instanceof SaveError?e:new SaveError('保存データの読み込みに失敗しました。データは削除していません。');}}
 write(p){validateProfile(p);const raw=JSON.stringify(p);try{this.storage.setItem(SAVE_KEY,raw);if(this.storage.getItem(SAVE_KEY)!==raw)throw new Error();}catch{throw new SaveError('入村記録を保存できません。空き容量と保存権限を確認してください。');}return p;}
 change(fn){const p=this.read();const result=fn(p);p.revision++;this.write(p);return result;}
 claim(village){if(!village||typeof village.id!=='string'||!village.id||village.id.length>200||['__proto__','constructor','prototype'].includes(village.id))throw new SaveError('村の識別子がありません。');return this.change(p=>{if(Object.hasOwn(p.visits,village.id))throw new SaveError('この村にはすでに入りました。改築・撤退・敗北後も再び入れません。');p.visits[village.id]={villageId:village.id,name:village.name,status:'entered',enteredAt:this.now()};p.offers=[];return p.visits[village.id];});}
 finish(id,outcome,eaten){if(!['escaped','defeated','completed','abandoned'].includes(outcome)||!Number.isSafeInteger(eaten)||eaten<0)throw new SaveError('狩りの結果が不正です。');return this.change(p=>{const v=p.visits[id];if(!v||v.status!=='entered')return false;v.status=outcome;v.eaten=eaten;p.hunts++;return true;});}
 abandonInterrupted(){if(!Object.values(this.read().visits).some(v=>v.status==='entered'))return;this.change(p=>{for(const v of Object.values(p.visits))if(v.status==='entered')v.status='abandoned';});}
 unlock(key){if(!Object.hasOwn(PREY,key))throw new SaveError('存在しない記憶です。');return this.change(p=>{const first=!p.unlocked.includes(key);if(first){p.unlocked.push(key);const empty=p.equipped.findIndex(k=>!k);if(empty>=0)p.equipped[empty]=key;else if(p.equipped.length<3)p.equipped.push(key);}p.totalEaten++;return first;});}
 equip(key,index){return this.change(p=>{if(!p.unlocked.includes(key)||!Number.isInteger(index)||index<0||index>2)throw new SaveError('装着できない記憶です。');const old=p.equipped.indexOf(key);if(old>=0){[p.equipped[old],p.equipped[index]]=[p.equipped[index],p.equipped[old]];}else p.equipped[index]=key;p.equipped=Array.from(p.equipped,k=>k||null);});}
}
