import test from 'node:test';
import assert from 'node:assert/strict';
import {defaultMuraLayout,projectMuraLayout,validateMuraLayout,muraBlocked,muraEntry,safeMuraPosition,initialMuraObjects,riverX,inWater} from '../src/mura/index.js';
test('MURA seed uses canonical IDs and independent objects',()=>{const a=defaultMuraLayout(),b=defaultMuraLayout();assert.deepEqual(a.objects.map(o=>o.id),['b1','b2','b3']);assert.deepEqual(a.objects.map(o=>o.kind),initialMuraObjects().map(o=>o.kind));a.objects[0].x=22;assert.equal(b.objects[0].x,-7);assert.equal(a.units,'metres');});
test('layout projection strips economy, characters, ownership claims and unknown fields',()=>{const layout=projectMuraLayout({villageId:'village-123',name:'育った村',revision:12,people:[{id:'not-public'}],stock:{wood:123},objects:[{...initialMuraObjects()[0],secret:'ignored',room:[{id:'chair-1',kind:'chair',x:1,z:1,rot:0}]}]});assert.equal(layout.id,'village-123');assert.equal(layout.revision,12);assert.equal(layout.objects[0].assetId,'mura.mayor');assert.equal(layout.objects[0].room[0].id,'chair-1');assert.equal(layout.people,undefined);assert.equal(layout.objects[0].secret,undefined);});
test('unknown schema, assets, duplicate IDs and invalid placement fail closed',()=>{for(const mutate of [s=>s.schemaVersion=2,s=>s.terrainId='elsewhere',s=>s.objects[0].kind='unknown-new-building',s=>s.objects[1].id='b1',s=>s.objects[0].x=Infinity,s=>s.objects[0].rot=null,s=>s.objects[0].level=4]){const s=defaultMuraLayout();mutate(s);assert.throws(()=>validateMuraLayout(s));}});
test('rotated footprints and entrances share coordinates with housing placement',()=>{const s=defaultMuraLayout(),o=s.objects[0];o.rot=Math.PI/2;const p=muraEntry(o);assert.ok(Math.abs(p.x-1)<1e-8);assert.ok(Math.abs(p.z+5)<1e-8);assert.equal(muraBlocked(s,p.x,p.z),false);assert.equal(muraBlocked(s,o.x,o.z),true);});
test('layout revision can move a building without changing entity identity; safe relocation avoids new footprint',()=>{const s=defaultMuraLayout(),old={x:22,z:20};s.objects[0].x=22;s.objects[0].z=20;s.revision++;const p=safeMuraPosition(s,old);assert.equal(s.objects[0].id,'b1');assert.equal(muraBlocked(s,p.x,p.z),false);assert.ok(Math.hypot(p.x-old.x,p.z-old.z)<=30);});
test('visitors use the same river and ford predicates as village placement',()=>{const s=defaultMuraLayout();assert.equal(inWater(riverX(0),0),true);assert.equal(muraBlocked(s,riverX(0),0),true);assert.equal(inWater(riverX(-42),-42),false);assert.equal(muraBlocked(s,riverX(-42),-42),false);});
