import {sharedEmblemUrl} from '@soul/assets';
import noticesUrl from '@soul/night-assets/notices';
import {createExclusiveProfileStorage} from './profile-storage.js';
import {NightView} from './view.js';
import {NightAudio} from './audio.js';
import {ProfileStore,SAVE_KEY} from '@soul/raid/profile';
import {RaidSession} from '@soul/raid';
import {PREY,FORMS,offerVillages,importHousing} from '@soul/raid/world';
import {SwipeInput} from '@soul/input';
import {createTidebreakRuntime} from '@soul/tidebreak-combat';
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let view,game,store,profile,error=null,mode='title',paused=false,sheetKind='',toastUntil=0,toastText='',last=0,acc=0,returnMode=false,selectedPower=null,drag=null,lastHud=0;
const swipe=new SwipeInput(),audio=new NightAudio();
function safe(fn){try{return fn();}catch(e){console.error(e);showError(e.message||String(e));}}
function showError(text){pauseInput();$('sheet').hidden=false;$('sheet-kicker').textContent='NOTICE';$('sheet-title').textContent='確認が必要です';$('sheet-body').innerHTML='<p class="error">'+esc(text)+'</p><p class="muted">保存データの削除や上書きによる初期化はしていません。</p>';sheetKind='error';}
function pauseInput(){swipe.cancel();$('move-pad').hidden=true;$('dash-stop').hidden=true;}
function sheet(title,kicker,html,kind){pauseInput();$('sheet-title').textContent=title;$('sheet-kicker').textContent=kicker;$('sheet-body').innerHTML=html;$('sheet').hidden=false;sheetKind=kind;}
function closeSheet(){pauseInput();$('sheet').hidden=true;sheetKind='';selectedPower=null;}
function refresh(){profile=store.read();game?.refreshProfile(profile);}
function toast(text,d=3.5){toastText=text;toastUntil=performance.now()+d*1000;$('toast').textContent=text;$('toast').style.opacity='1';}
function event(e){view?.event(e);audio.event(e);if(e.type==='engage'){pauseInput();toast(e.npc.name+'と対峙',1.8);}if(e.type==='guardian')toast(e.echo?'読み込んだ守護者の構成が狩場に現れた。':'警鐘が響く。討伐騎士が村へ入った。',5);if(e.type==='bell-silenced')toast('声を喰らった。鐘の音が遠のく。');if(e.type==='ward')toast(e.text);if(e.type==='gate')toast('鉄砕く腕が、封鎖を引き裂いた。');if(e.type==='disengage')toast('間合いを切った。闇へ逃れろ。');if(e.type==='finish'){mode='result';pauseInput();showResult(e);}}
function newSession(v){refresh();game=new RaidSession(v,profile,{event,consume(role){const first=store.unlock(role);refresh();if(first){const n=PREY[role];toast(n.power+'を喰らった。'+(profile.equipped.includes(role)?'身体が変わる。':'肉体の枠へ装着できる。'),5);const unlocked=profile.unlocked.length;if([2,4,6].includes(unlocked)){setTimeout(()=>{if(mode==='hunt')toast('新たな姿が目覚めた。「肉体」で選べる。',5);},1500);}}else toast('息を飲み込み、生命が戻る。',2.5);},finish(status,n){store.finish(v.id,status,n);refresh();}});view.build(game.village);view.snapCamera(game.player);}
async function claimAndEnter(v){try{pauseInput();store.claim(v);closeSheet();newSession(v);mode='hunt';returnMode=false;$('title').hidden=true;$('hud').hidden=false;audio.start();toast('一度きりの夜。獲物を選べ。',3);last=0;acc=0;}catch(e){showError(e.message);}}
function routes(){refresh();const offers=offerVillages(store);let html='<p>喰らいたい力で、次の村を選ぶ。<br>入村した村は、撤退・敗北しても再訪できない。</p>';
 for(const v of offers){const d=PREY[v.target];html+=`<button class="route-card" data-village="${esc(v.id)}"><span class="tag">${v.weather==='rain'?'雨の夜':'深い霧'} · ${v.level>2?'記憶の深まる夜':'人の灯りが残る村'}</span><strong>${esc(v.name)}</strong><span class="arrow">›</span><span class="route-bottom"><span>${esc(d.name)}を狙う</span><span class="reward">${esc(d.power)}${profile.unlocked.includes(v.target)?' · 記憶あり':' · 未知の力'}</span></span></button>`;}
 if(profile.imported){const v=profile.imported,visited=!!profile.visits[v.id];html+=`<button class="route-card" data-imported="1" ${visited?'disabled':''}><span class="tag">読み込んだハウジング保存データ · オフライン</span><strong>${esc(v.name)}</strong><span class="reward">${visited?'入村済み · 再訪不可':'実際の配置をそのまま狩場へ'}</span></button>`;}
 html+='<p class="muted">生成された村は単独プレイ用です。実プレイヤーの村へはまだ接続していません。</p>';sheet('今夜、どこで喰らう。','CHOOSE YOUR HUNT',html,'routes');
 for(const b of document.querySelectorAll('[data-village]'))b.onclick=()=>claimAndEnter(offers.find(v=>v.id===b.dataset.village));document.querySelector('[data-imported]')?.addEventListener('click',()=>claimAndEnter(profile.imported));}
function memory(){refresh();let html='<p>喰らった記憶を、身体へ。<br>カードを枠へドラッグ。カードと枠を順にタップしても装着できる。</p><div class="slots">';for(let i=0;i<3;i++){const k=profile.equipped[i],d=PREY[k];html+=`<button class="slot" data-slot="${i}"><b>${d?d.glyph:'◇'}</b>${d?esc(d.power):'まだ、空っぽ'}</button>`;}html+='</div><div class="form-row">';for(const [k,f] of Object.entries(FORMS))html+=`<button class="form-choice ${profile.form===k?'current':''}" data-form="${k}" ${profile.unlocked.length<f.need?'disabled':''}>${f.name}<small>${profile.unlocked.length<f.need?'異なる記憶 '+f.need+'種':profile.form===k?'現在の姿':'この姿になる'}</small></button>`;html+='</div><p class="muted">'+esc(FORMS[profile.form].desc)+'</p><div class="memory-grid">';
 for(const k of profile.unlocked){const d=PREY[k];if(!d)continue;html+=`<button class="memory-chip" data-power="${k}"><b>${d.glyph}</b><strong>${d.power}</strong><small>${d.desc}</small></button>`;}html+='</div>';if(!profile.unlocked.length)html+='<p class="muted">まだ、誰も喰らっていない。最初の旅人を狙うところから始まる。</p>';
 sheet('肉体の記憶','YOU ARE WHAT YOU DEVOUR',html,'memory');
 for(const b of document.querySelectorAll('[data-form]'))b.onclick=()=>safe(()=>{store.change(p=>{const f=FORMS[b.dataset.form];if(p.unlocked.length>=f.need)p.form=b.dataset.form;});refresh();memory();});
 for(const b of document.querySelectorAll('[data-slot]'))b.onclick=()=>{if(selectedPower)safe(()=>{store.equip(selectedPower,+b.dataset.slot);refresh();memory();});};
 for(const b of document.querySelectorAll('[data-power]')){b.onpointerdown=e=>{if(e.button!==0&&e.pointerType==='mouse')return;e.preventDefault();const key=b.dataset.power;selectedPower=key;document.querySelectorAll('.memory-chip').forEach(c=>c.classList.toggle('selected',c===b));drag={key,id:e.pointerId,x:e.clientX,y:e.clientY,moved:false,el:b};b.setPointerCapture(e.pointerId);};b.onpointermove=e=>{if(!drag||drag.id!==e.pointerId)return;if(Math.hypot(e.clientX-drag.x,e.clientY-drag.y)>6)drag.moved=true;if(!drag.moved)return;const ghost=$('drag-ghost');ghost.hidden=false;ghost.textContent=PREY[drag.key].power;ghost.style.transform=`translate(${e.clientX-45}px,${e.clientY-30}px)`;document.querySelectorAll('.slot').forEach(s=>{const r=s.getBoundingClientRect();s.classList.toggle('drag-over',e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom);});};
 b.onpointerup=e=>{if(!drag||drag.id!==e.pointerId)return;const d=drag;drag=null;$('drag-ghost').hidden=true;try{b.releasePointerCapture(e.pointerId);}catch{}if(d.moved){let slot=null;for(const s of document.querySelectorAll('.slot')){const r=s.getBoundingClientRect();if(e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom)slot=+s.dataset.slot;}if(slot!==null)safe(()=>{store.equip(d.key,slot);refresh();memory();});}document.querySelectorAll('.drag-over').forEach(s=>s.classList.remove('drag-over'));};b.onpointercancel=()=>{drag=null;$('drag-ghost').hidden=true;};}
}
function settings(){refresh();let html='<p>画面をスワイプして移動。指を置いたまま滑らせると歩き、素早く弾くと走り続ける。接敵すると自動で止まり、序・破・急の戦闘へ。</p><button class="inline-action" id="sound-toggle">音：'+(audio.enabled?'入':'切')+'<small>風、足音、警鐘、捕食、戦闘音</small></button><button class="inline-action" id="visit-log">訪れた村の記録<small>'+Object.keys(profile.visits).length+'村 · すべて再訪不可</small></button><button class="inline-action" id="load-village">ハウジングの村を読み込む<small>村ゲームのセーブJSON。配置は再利用し、元のデータは変更しない。</small></button><button class="inline-action" id="load-echo">輪廻転焦の技目録を読み込む<small>守護者の構成をオフラインで再現。実プレイヤーとのオンライン対戦ではない。</small></button><button class="inline-action" id="credits">アセットと接続状況<small>GitHub取得素材・共通戦闘コード・実装範囲</small></button>';
 if(mode==='hunt')html+='<button class="inline-action" id="give-up">この村を去る<small>この夜を終了する。捕食ゼロでも入村済みのまま。</small></button>';
 sheet(mode==='hunt'?'闇で、ひと息。':'記録と連携','THE NIGHT REMEMBERS',html,'settings');$('sound-toggle').onclick=()=>{audio.start();audio.toggle();settings();};$('visit-log').onclick=visits;$('load-village').onclick=()=>importFile('village');$('load-echo').onclick=()=>importFile('echo');$('credits').onclick=credits;$('give-up')?.addEventListener('click',()=>{sheet('この夜を終える。','LEAVE THIS VILLAGE',`<p>${esc(game.village.name)}には、二度と入れません。</p><button class="primary" id="confirm-leave">村を去る</button>`,'leave');$('confirm-leave').onclick=()=>game.finish('escaped');});}
function visits(){refresh();const rows=Object.values(profile.visits).reverse();sheet('戻れない村々。','VISITED ONCE, FOREVER',rows.length?rows.map(v=>`<div class="visit-row">${esc(v.name)}<span>${({entered:'入村済み',escaped:'撤退',defeated:'敗北',abandoned:'中断',completed:'狩りを完遂'})[v.status]} · 再訪不可</span></div>`).join(''):'<p>まだ、足跡は残っていない。</p>','visits');}
function credits(){sheet('この夜の成り立ち。','SOURCE / CONNECTION',`<p>移動と戦闘は、取得したTidebreakの判定・序破急・間合い・被弾処理を再利用しています。</p><div class="credits">GitHub取得：KayKit Dungeon Remastered / Kay Lousberg / CC0<br>floor_tile_small.obj：石畳<br>banner_blue.obj：村門・礼拝所の布<br><br>家屋：ハウジング実装のモデル生成コードを再利用<br>怪物・人間：この試作の手続き型モデル<br>音：この試作の合成音<br>描画：Three.js / MIT</div><p>現在はオフラインの単独狩りです。輪廻転焦の実アカウント、村の共有サーバー、実プレイヤー対戦には未接続です。</p><p class="muted">入村履歴はこのブラウザへ保存します。保存領域の削除や端末変更をまたぐ禁止には、アカウントとサーバー側の入村台帳が必要です。</p><div class="provenance">ASSET COMMIT b0ca9bd9<br>RINNE REFERENCE: ZIP同梱 Tidebreak Atelier<br>LEGACY COMBAT SOURCE: TIDEBREAK ATELIER 10<br>${esc(__BUILD_INFO__.environment.toUpperCase())} / ${esc(__BUILD_INFO__.commit.slice(0,12))}<br><a href="${esc(noticesUrl)}" target="_blank" rel="noopener">利用素材とライセンス</a></div>`,'credits');}
function importFile(kind){const f=$('import-file');f.value='';f.onchange=async()=>{try{const file=f.files?.[0];if(!file)return;if(file.size>2_000_000)throw Error('2MB以下のJSONを選んでください。');const data=JSON.parse(await file.text());if(kind==='village'){const v=importHousing(data);store.change(p=>p.imported=v);refresh();sheet('村を読み込んだ。','HOUSING SAVE / LOCAL',`<p>${esc(v.name)}<br>${v.entities.length}個の配置を読み込みました。</p><p class="muted">${v.legacyIdentity?'この保存形式には村IDがないため、所有者ごとに1つの村として扱います。改築しても再訪できません。':'村IDで入村済みを照合します。'}<br>オンラインの所有権や住民データを取得したわけではありません。</p><button class="primary" id="after-import">${mode==='hunt'?'狩りへ戻る':'狩場を選ぶ'}</button>`,'import');$('after-import').onclick=()=>mode==='hunt'?closeSheet():routes();}else{const prepared=createTidebreakRuntime().decodeNotebook(data);store.change(p=>p.echo={weapon:prepared.weapon,loadout:prepared.slots,name:'技目録の守護者'});refresh();sheet('守護者の技を読み込んだ。','RINNE SKILL NOTEBOOK / LOCAL','<p>次の村で、警戒が高まると読み込んだ構成の守護者が現れます。</p><p class="muted">現在の再生はオフラインAIです。実プレイヤーへの接続や報酬送信は行いません。攻の先頭候補を使う比較用アダプターであり、全候補の対人同期は未実装です。</p>','import');}}catch(e){showError('読み込みできません：'+e.message);}};f.click();}
function showResult(e){const headline=e.status==='defeated'?'夜に、呑まれた。':e.target?'その命を、次の夜へ。':'闇へ、持ち帰る。';sheet(headline,'THE HUNT IS OVER',`<div class="result-stats"><div><b>${e.eaten}</b><span>喰らった人間</span></div><div><b>${profile.unlocked.length}</b><span>刻まれた記憶</span></div><div><b>${Object.keys(profile.visits).length}</b><span>戻れない村</span></div></div><p>${esc(game.village.name)}への道は、閉ざされた。</p><p class="muted">${e.status==='defeated'?'倒れても、解放した記憶は失わない。別の村で狩り直す。':e.target?'狙った人間の命を持ち帰った。得た力で、違う村の奥へ。':'すべてを喰らう必要はない。狙う力を決めて、次の村へ。'}</p><button class="primary" id="next-night">次の村を嗅ぎつける</button><button class="inline-action" id="result-memory">肉体を組み替える</button>`,'result');$('next-night').onclick=routes;$('result-memory').onclick=memory;}
function hud(now){if(!game)return;const p=game.player,al=game.alarm;let hp=Math.max(0,p.hp);$('life-fill').style.width=(hp/p.maxhp*100)+'%';$('life-text').textContent=Math.ceil(hp)+' / '+p.maxhp;$('form-name').textContent=FORMS[profile.form].name;$('village-name').textContent=game.village.name;$('night-label').textContent=game.village.source==='imported-local'?'HOUSING SAVE · LOCAL':'NIGHT '+String(profile.hunts+1).padStart(2,'0');$('alarm-fill').style.width=al+'%';$('alarm-label').textContent=al<20?'まだ、気づかれていない':al<45?'戸が閉まり始める':al<72?'警戒が村に広がる':'討伐騎士が、あなたを探している';$('objective').querySelector('span').textContent=game.targetEaten?'狙った命を得た。帰還口へ。':PREY[game.village.target].name+'の「'+PREY[game.village.target].power+'」';$('objective').querySelector('small').textContent=game.targetEaten?'喰らった命を持ち帰る':'今夜の獲物';$('battle').style.opacity=game.fight?'1':'0';$('skill-name').textContent=p.skill||'間合いを測る';document.querySelectorAll('[data-phase]').forEach(e=>e.classList.toggle('active',e.dataset.phase===p.slot));$('enemy-health').style.width=game.fight?Math.max(0,game.fight.npc.hp/game.fight.npc.maxhp*150)+'px':'0';$('eaten-label').textContent='捕食 '+game.eaten+' · 記憶 '+profile.unlocked.length+' / 8';$('scent').querySelector('span').textContent=game.scentCooldown>0?Math.ceil(game.scentCooldown)+'秒':'嗅覚';$('scent').disabled=game.scentCooldown>0;$('dash-stop').hidden=!swipe.dash;$('swipe-hint').style.opacity=game.time<14&&!game.fight?'1':'0';
 const dist=Math.hypot(game.village.entry.x-p.x,game.village.entry.z-p.z);$('return-arrow').style.transform=`rotate(${-Math.atan2(game.village.entry.x-p.x,game.village.entry.z-p.z)*180/Math.PI}deg)`;$('return-hint').hidden=(!returnMode&&!game.targetEaten&&game.escapeHold===0)||!!game.fight;$('return-hint').textContent=game.escapeHold>0?'闇に溶ける…':`帰還口まで ${Math.ceil(dist)} m · 輪の中で指を離す`;$('toast').style.opacity=now<toastUntil?'1':'0';}
function installInput(){const el=$('game');el.oncontextmenu=e=>e.preventDefault();el.addEventListener('pointerdown',e=>{if(mode!=='hunt'||!$('sheet').hidden||paused||e.pointerType==='mouse'&&e.button!==0)return;e.preventDefault();if(!swipe.down(e.pointerId,e.clientX,e.clientY,performance.now()))return;el.setPointerCapture(e.pointerId);$('move-pad').hidden=false;$('move-pad').style.left=e.clientX+'px';$('move-pad').style.top=e.clientY+'px';$('move-nub').style.transform='';});el.addEventListener('pointermove',e=>{if(!swipe.move(e.pointerId,e.clientX,e.clientY,performance.now()))return;e.preventDefault();const d=Math.hypot(swipe.dx,swipe.dy)||1,k=Math.min(1,34/d);$('move-nub').style.transform=`translate(${swipe.dx*k}px,${swipe.dy*k}px)`;});el.addEventListener('pointerup',e=>{if(swipe.id!==e.pointerId)return;e.preventDefault();const flick=swipe.up(e.pointerId,e.clientX,e.clientY,performance.now());$('move-pad').hidden=true;if(el.hasPointerCapture(e.pointerId))el.releasePointerCapture(e.pointerId);if(flick)game.shadowStep(swipe.vector(.33));});el.addEventListener('pointercancel',pauseInput);el.addEventListener('lostpointercapture',()=>{if(swipe.id!==null)pauseInput();});window.addEventListener('blur',()=>{pauseInput();if(mode==='hunt'&&$('sheet').hidden){paused=true;sheet('夜を、止めている。','PAUSED','<p>閉じると、狩りを再開します。</p>','paused');}});document.addEventListener('visibilitychange',()=>{pauseInput();audio.pause(document.hidden);if(document.hidden&&mode==='hunt'&&$('sheet').hidden){paused=true;sheet('夜を、止めている。','PAUSED','<p>閉じると、狩りを再開します。</p>','paused');}});}
function frame(now){if(error)return;requestAnimationFrame(frame);try{if(!view||!game)return;const dt=Math.max(0,Math.min(.07,(now-(last||now))/1000));last=now;const running=mode==='hunt'&&$('sheet').hidden&&!paused&&!document.hidden;
 if(running){acc=Math.min(.10,acc+dt);let steps=0;while(acc>=1/60&&steps++<6){const v=swipe.vector(.33);v.dash=swipe.dash;game.tick(1/60,v);acc-=1/60;if(game.fight&&swipe.dash)pauseInput();if(game.finished)break;}audio.tick(dt,game.player.speed>.15&&!game.fight);}else acc=0;
 view.update(game,dt,mode==='title');if(now-lastHud>80){hud(now);lastHud=now;}}catch(e){error=e;pauseInput();console.error(e);$('boot').hidden=false;$('boot-message').textContent='狩場を再開できません';$('boot-detail').textContent=e.message;$('boot-retry').hidden=false;$('game').dataset.renderer='error';}}
export async function boot(){const storage=await createExclusiveProfileStorage(__BUILD_INFO__.environment);view=new NightView($('game'));store=new ProfileStore(storage,()=>crypto.randomUUID(),()=>Date.now());profile=store.read();store.abandonInterrupted();profile=store.read();
 const preview={id:'title-only-not-entered',name:'森の向こうの灯',seed:67002,target:'arcanist',level:1,weather:'fog',source:'generated'};game=new RaidSession(preview,profile,{});view.build(game.village);game.player.x=1;game.player.z=20;game.player.yaw=.5;view.camera.position.set(5,3.6,27);view.cameraLook.set(1,.95,18);view.update(game,0,true);$('game').dataset.renderer='ready';Object.assign($('game').dataset,{app:'demon',commit:__BUILD_INFO__.commit,environment:__BUILD_INFO__.environment,platform:'web',world:'night-hunt.v2',asset:'kaykit.floor_tile_small'});$('emblem').src=sharedEmblemUrl;$('boot').hidden=true;$('title').hidden=false;
 $('begin').onclick=()=>safe(()=>{audio.start();routes();});$('title-memory').onclick=()=>safe(memory);$('title-settings').onclick=()=>safe(settings);$('connection').onclick=credits;$('game').addEventListener('webglcontextlost',e=>{e.preventDefault();error=Error('描画が中断されました。再試行するとタイトルへ戻ります。入村記録は保持します。');pauseInput();$('boot').hidden=false;$('boot-message').textContent='描画が中断されました';$('boot-detail').textContent=error.message;$('boot-retry').hidden=false;$('game').dataset.renderer='lost';});$('pause').onclick=()=>safe(settings);$('memory').onclick=()=>safe(memory);$('scent').onclick=()=>{audio.start();game.sense();};$('return').onclick=()=>{returnMode=!returnMode;toast('帰還口の輪の中で指を離すと、この夜を終える。',3);};$('dash-stop').onclick=pauseInput;
 $('sheet-close').onclick=()=>{if(sheetKind==='error'&&error)return;if(mode==='result'){mode='title';$('title').hidden=false;$('hud').hidden=true;}paused=false;closeSheet();};
 window.addEventListener('resize',()=>view.resize());installInput();requestAnimationFrame(frame);
 window.__NIGHT_HUNT__={snapshot:()=>({mode,paused:!$('sheet').hidden||paused,source:game.village.source,village:game.village.id,visited:Object.keys(store.read().visits),profile:store.read(),player:JSON.parse(JSON.stringify(game.player)),npcs:game.village.npcs.map(n=>({id:n.id,kind:n.kind,adult:n.adult,role:n.role,hp:n.hp,dead:n.dead,eaten:n.eaten,x:n.x,z:n.z,marked:n.marked,state:n.state})),combat:game.fight?game.fight.core.state():null,eaten:game.eaten,alarm:game.alarm,time:game.time,finished:game.finished,metrics:view.metrics(),input:{id:swipe.id,dx:swipe.dx,dy:swipe.dy,amount:swipe.amount,dash:swipe.dash}}),openRoutes:routes};
 // Explicit review mode only. Never deletes visit history or fakes an online identity.
 if(import.meta.env.DEV && new URLSearchParams(location.search).has('review'))window.__NIGHT_REVIEW__={enter:async(i=0)=>{await claimAndEnter(offerVillages(store)[i]);},nearHuman(i=0){const n=game.village.npcs[i];game.player.x=n.x;game.player.z=n.z+2.5;game.player.yaw=Math.PI;},setPosition(x,z){game.fight=null;game.devour=null;game.player.x=x;game.player.z=z;game.player.pose=null;},step(n=1){for(let i=0;i<Math.min(n,36000)&&!game.finished;i++)game.tick(1/60,{x:0,z:0,amount:0});},unlock(k){store.unlock(k);refresh();},finish(s='escaped'){game.finish(s);},retry(id){return store.claim({id,name:'再訪テスト'});},read:()=>store.read(),screenshot(){view.update(game,1/60,false);hud(performance.now());},ready:()=>!!game};
}
