import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {localBuildMotionDatabase,localQueryMotionDatabase,localPlanMotionTransition,localTransitionBridgePose,localSurfaceFootPlant,localSweepWeaponCapsule,localCalibratedMotionLod} from '../public/simulator/src/motion-database-math.js';
import {buildMotionDatabase,queryMotionDatabase,planMotionTransition,transitionBridgePose,surfaceFootPlantPresentation,sweepWeaponSegmentAgainstCapsule,calibratedMotionLod,createMotionDeviceCalibration} from '@soul/animations';

const clips=[{id:'idle',state:'idle',duration:1,speed:0,yaw:0,transitions:['idle->move','stop->idle']},{id:'walk',state:'move',duration:1,speed:1.1,yaw:0,transitions:['idle->move','move->stop','move->pivot','recovery->move']},{id:'slash',state:'attack',duration:.66,speed:.6,yaw:0,transitions:['move->attack'],semanticEvents:[{name:'contact',phase:.5}]},{id:'slash-recovery',state:'recovery',duration:.34,speed:.2,yaw:0,transitions:['attack->recovery','hit->recovery']}];
test('Rinne indexed motion database matches shared valid contracts',()=>{const a=localBuildMotionDatabase({clips,revision:'same'}),b=buildMotionDatabase({clips,revision:'same'});assert.deepEqual(a,b);const input={state:'move',speed:1,yaw:0,supportSide:'left',trajectory:[{x:0,z:.3}],transition:'idle->move'},qa=localQueryMotionDatabase({database:a,...input}),qb=queryMotionDatabase({database:b,...input});assert.deepEqual(qa,qb);});
test('Rinne transition plan and bridge preserve attack contact timing',()=>{const a=localBuildMotionDatabase({clips,revision:'same'}),b=buildMotionDatabase({clips,revision:'same'}),pa=localPlanMotionTransition({database:a,fromState:'move',toState:'attack',speed:.7,supportSide:'left'}),pb=planMotionTransition({database:b,fromState:'move',toState:'attack',speed:.7,supportSide:'left'});assert.deepEqual(pa,pb);assert.equal(pa.contactTimingLocked,true);assert.equal(pa.application,'additive-bridge');assert.deepEqual(localTransitionBridgePose(pa,{progress:.5}),transitionBridgePose(pb,{progress:.5}));});
test('Rinne surface event mirrors shared material presentation',()=>{const input={surface:'mud',foot:'right',position:{x:1,y:0,z:2},normal:{x:.1,y:.98,z:0},speed:1.8,weight:.9,event:{name:'foot-plant'}};assert.deepEqual(localSurfaceFootPlant(input),surfaceFootPlantPresentation(input));});
test('Rinne segment capsule sweep matches shared measured contact evidence',()=>{const input={previousBase:{x:-1,y:1,z:0},previousTip:{x:-.5,y:1,z:0},currentBase:{x:-.4,y:1,z:0},currentTip:{x:.4,y:1,z:0},capsuleStart:{x:0,y:.2,z:0},capsuleEnd:{x:0,y:1.8,z:0},radius:.2,dt:1/60,weaponMass:1.1,hitSerial:3};const a=localSweepWeaponCapsule(input),b=sweepWeaponSegmentAgainstCapsule(input);assert.deepEqual(a,b);assert.equal(a.damageAuthority,false);assert.equal(a.collisionAuthority,false);});
test('Rinne calibrated LOD refuses design-only evidence and matches shared physical tier',()=>{const design=createMotionDeviceCalibration({deviceClass:'pixel-fold-class-30',physicalDevice:false,cohort:12,sampleCount:60,totalMeanMs:7,layers:[]});assert.deepEqual(localCalibratedMotionLod(design),calibratedMotionLod(design));const physical=createMotionDeviceCalibration({deviceClass:'pixel-fold-class-30',physicalDevice:true,userAgent:'Pixel Fold QA',cohort:12,sampleCount:60,totalMeanMs:7,layers:[]});assert.deepEqual(localCalibratedMotionLod(physical),calibratedMotionLod(physical));});
test('final entry routes through finalized layer and never owns gameplay authority',async()=>{const entry=await readFile(new URL('../public/simulator/src/humanoid.js',import.meta.url),'utf8'),source=await readFile(new URL('../public/simulator/src/humanoid-finalized.js',import.meta.url),'utf8');assert.match(entry,/HumanoidRuntime,HUMANOID_FINALIZED_REVISION.*humanoid-finalized/);assert.match(source,/extends BaseHumanoidRuntime/);assert.match(source,/localPlanMotionTransition/);assert.match(source,/surfaceFootPlants/);assert.match(source,/localSweepWeaponCapsule/);assert.doesNotMatch(source,/a\.x\s*=|a\.z\s*=|a\.yaw\s*=|a\.attack\s*=/);assert.doesNotMatch(source,/\.hp\s*=|damage\s*\(/);assert.match(source,/contactTimingAuthority:'gameplay-external'/);});
test('phase alignment is restricted to non-combat presentation transitions',async()=>{const source=await readFile(new URL('../public/simulator/src/humanoid-finalized.js',import.meta.url),'utf8'),method=source.match(/applyPhaseAlignment\(a,transition\)\{([\s\S]*?)\n applyBridge/)?.[1];assert.ok(method);assert.match(method,/plan\?\.phaseAlign/);assert.match(method,/a\?\.attack\|\|a\?\.reaction\|\|a\?\.recovery\|\|a\?\.dead/);assert.match(method,/a\._humanoidPhase=transition\.plan\.selected\.phase/);assert.doesNotMatch(method,/a\.(?:x|z|yaw|attack)\s*=/);});
