import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {localBuildPoseCandidateBank,localSelectPoseStart,localSweptWeaponEvidence,localFootSliding,localJerk} from '../public/simulator/src/motion-operational-math.js';
import {buildPoseCandidateBank,selectPoseStart,sweptWeaponContactEvidence,footSlidingDiagnostics,motionJerkDiagnostics} from '@soul/animations';

const clips=[{id:'walk',state:'move',duration:1,speed:1,yaw:0,supportSide:'left',continuity:.9},{id:'idle',state:'idle',duration:1,speed:0,yaw:0,supportSide:'right'}];
test('Rinne candidate bank and start selection match shared contracts',()=>{const local=localBuildPoseCandidateBank({clips,fps:60,samplesPerClip:3}),shared=buildPoseCandidateBank({clips,fps:60,samplesPerClip:3});assert.deepEqual(local,shared);const input={state:'move',speed:1,yaw:0,supportSide:'left',trajectory:[{x:0,z:.4}]};assert.deepEqual(localSelectPoseStart({...input,bank:local}),selectPoseStart({...input,bank:shared}));});
test('Rinne swept contact evidence matches shared presentation-only contract',()=>{const input={point:{x:1,y:1,z:2},normal:{x:1,z:.2},relativeSpeed:5,penetration:.03,weaponMass:1.2,hitSerial:5};assert.deepEqual(localSweptWeaponEvidence(input),sweptWeaponContactEvidence(input));});
test('Rinne foot slide and jerk diagnostics agree with shared QA',()=>{const feet={left:[0,.01,.03].map((x,i)=>({time:i/60,x,z:0,planted:true})),right:[0,.01,.06].map((x,i)=>({time:i/60,x,z:0,planted:true}))};const tracks={hips:[0,1,2,8,9,10].map((x,i)=>({time:i*.1,position:[x,0,0],rotation:[0,i<3?0:2,0]}))};const lf=localFootSliding(feet),sf=footSlidingDiagnostics(feet);assert.equal(lf.failed,sf.failed);assert.equal(lf.warnings,sf.warnings);const lj=localJerk(tracks,{linearWarning:100,angularWarning:100}),sj=motionJerkDiagnostics(tracks,{linearWarning:100,angularWarning:100});assert.equal(lj.spikes.length,sj.spikes.length);assert.equal(lj.pass,sj.pass);});
test('final humanoid entry routes through operational layer and preserves authority',async()=>{const entry=await readFile(new URL('../public/simulator/src/humanoid.js',import.meta.url),'utf8'),source=await readFile(new URL('../public/simulator/src/humanoid-operational.js',import.meta.url),'utf8');assert.match(entry,/HumanoidRuntime,HUMANOID_OPERATIONAL_REVISION.*humanoid-operational/);assert.match(source,/extends BaseHumanoidRuntime/);assert.match(source,/poseStartSuggestion/);assert.match(source,/recordKinematics/);assert.doesNotMatch(source,/a\.x\s*=|a\.z\s*=|a\.yaw\s*=|a\.attack\s*=/);assert.doesNotMatch(source,/\.hp\s*=|damage\s*\(/);assert.match(source,/gameplayAuthority:false/);});
test('pose search applies only on committed locomotion entry and never attack/recovery',async()=>{const source=await readFile(new URL('../public/simulator/src/humanoid-operational.js',import.meta.url),'utf8'),method=source.match(/applyLocomotionPoseStart\(a,commit\)\{([\s\S]*?)\n \}/)?.[1];assert.ok(method);assert.match(method,/if\(!commit\|\|a\?\.attack\|\|a\?\.recovery\|\|a\?\.dead\)return null/);assert.match(method,/state!=='move'\|\|previous==='move'/);assert.match(method,/a\._humanoidPhase=suggestion\.phase/);assert.match(method,/presentationPhaseOnly:true/);assert.doesNotMatch(method,/a\.(?:x|z|yaw|attack)\s*=/);});
test('impact contact evidence requires identified participants and actual weapon segment',async()=>{const source=await readFile(new URL('../public/simulator/src/humanoid-operational.js',import.meta.url),'utf8');assert.match(source,/beat\?\.actorId==null\|\|beat\?\.targetId==null/);assert.match(source,/attacker\.weaponBase/);assert.match(source,/attacker\.weaponTip/);assert.match(source,/source:'authoritative-impact-weapon-segment'/);assert.match(source,/penetrationEstimated:true/);assert.match(source,/damageAuthority:false|localSweptWeaponEvidence/);});
test('semantic presentation bridge stays descriptive and explicit interaction cannot infer partner',async()=>{const source=await readFile(new URL('../public/simulator/src/humanoid-operational.js',import.meta.url),'utf8');assert.match(source,/__RINNE_MOTION_EVENT_CHANNELS__/);assert.match(source,/rinne:motion-presentation/);assert.match(source,/setInteraction\(actor/);assert.match(source,/localSchema\(schema,\{partner,anchors/);assert.match(source,/presentationOnly:true/);assert.doesNotMatch(source,/setInteraction[\s\S]{0,800}actor\.target/);});
test('physical device calibration is explicit and design budget is never measurement',async()=>{const source=await readFile(new URL('../public/simulator/src/humanoid-operational.js',import.meta.url),'utf8');assert.match(source,/deviceCalibration\(\{deviceClass='pixel-fold-class-30',physicalDevice=false/);assert.match(source,/measuredHardware=Boolean\(physicalDevice&&sampleCount>0&&totalMeanMs!==null/);assert.match(source,/designBudgetIsMeasurement:false/);assert.match(source,/physicalDevice must be explicitly asserted by device QA/);});
