// Saved-life input uses the same entry/continue/save path as rebuild-playthrough.
import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {createLife,serializeLife} from '../src/rebuild/domain.js';
import {createFront} from '../src/rebuild/combat.js';
export async function verifyJohakyuLifeBattle(browser,url,out,{sourceSha,routeAssets,fontUrl}={}){
 await mkdir(out,{recursive:true});const context=await browser.newContext({viewport:{width:1100,height:760},reducedMotion:'reduce'}),page=await context.newPage(),errors=[],report={sourceSha,passed:false};
 page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text()+' '+m.location().url);});if(routeAssets)await routeAssets(context);if(fontUrl)await context.route('https://fonts.googleapis.com/**',route=>route.fulfill({contentType:'text/css',body:`@font-face{font-family:'Kaisei Opti';src:url('${fontUrl}')}@font-face{font-family:'Zen Kaku Gothic New';src:url('${fontUrl}')}`}));
 const state=createLife({seed:73917,name:'序破急検証'});Object.assign(state,{ageSeconds:1200,ageYears:20,phase:'living',zone:'frontier',front:0,position:{x:0,z:0},resting:false,lastDepartureCycle:4});state.equipment={weapon:'sword',armor:'heavy',shield:false};state.knownSkills.push('basic.sword');state.maxHp=300;state.hp=300;const front=createFront();front.enemies=front.enemies.slice(0,1);front.enemies.forEach((e,i)=>{e.dead=i>0;if(i===0){e.x=0;e.z=2.15;e.hp=e.maxHp=100;}});state.frontState=front;
 const key='soul:v1:dev:rinne:local:life-v2';await context.addInitScript(({key,value})=>{if(!sessionStorage.getItem('shared-evidence-seeded')){localStorage.setItem(key,value);sessionStorage.setItem('shared-evidence-seeded','1');}},{key,value:serializeLife(state)});
 try{
  console.log('main goto');await page.goto(url,{waitUntil:'domcontentloaded'});await page.locator('#soul-brand-boot.armed').waitFor({state:'visible',timeout:90000});await page.getByRole('button',{name:'PARALYZE AREA 起動'}).click();await page.locator('#continue-life').waitFor({state:'visible',timeout:90000});console.log('main continue');await page.locator('#continue-life').click();await page.getByRole('button',{name:'この人生を続ける',exact:false}).click();await page.locator('#loading-card').waitFor({state:'hidden',timeout:90000});await page.waitForFunction(()=>document.querySelector('#game')?.dataset.battlePresentation==='johakyu',null,{timeout:90000});
  if(await page.locator('.rinneFirstRunSkip').isVisible())await page.locator('.rinneFirstRunSkip').click();report.canvas=await page.locator('.johakyu-world canvas').evaluateAll(nodes=>nodes.map(c=>({width:c.width,height:c.height,clientWidth:c.clientWidth,clientHeight:c.clientHeight})));assert.ok(report.canvas.every(c=>c.width>100&&c.height>100));console.log('main shared renderer ready',report.canvas);assert.equal(await page.locator('#game').getAttribute('data-runtime'),'active');assert.equal(await page.locator('.johakyu-world').isVisible(),true);
  if(fontUrl){await page.addStyleTag({content:`@font-face{font-family:EvidenceJapanese;src:url('${fontUrl}')}body,button,strong,span{font-family:EvidenceJapanese,sans-serif!important}`});await page.evaluate(()=>document.fonts.load('16px EvidenceJapanese'));}
  await page.screenshot({path:out+'/main-battle.png'});
  // Wall-time observation of the actual game loop, not a second fixture combat executor.
  await page.waitForTimeout(55000);report.hud=await page.locator('.combat-phase-indicator').evaluate(node=>({engine:node.dataset.battleEngine,techniqueId:node.dataset.techniqueId,stageIndex:node.dataset.stageIndex,phase:node.dataset.phase,label:node.querySelector('[data-phase-action]')?.textContent?.trim()||'',technique:node.querySelector('[data-exchange-cue]')?.textContent?.trim()||''}));assert.equal(report.hud.engine,'johakyu');assert.ok(report.hud.label===''||/\d段 · \d+\/\d+技/.test(report.hud.label));assert.ok(!/^guard|^slash|^heavy|^thrust/.test(report.hud.label));await page.screenshot({path:out+'/main-contact.png'});await page.locator('#back-title').click();await page.locator('#title-screen').waitFor({state:'visible'});
  const saved=await page.evaluate(key=>JSON.parse(localStorage.getItem(key)),key);report.saved={id:saved.id,hp:saved.hp,injuries:saved.injuries,front:saved.frontState,knownSkills:saved.knownSkills};assert.equal(saved.id,state.id);assert.ok(saved.frontState.enemies[0].hp<100||Object.values(saved.injuries).some(row=>row.severity>0),'shared contact must reach saved life HP');assert.ok(!saved.combat?.johakyuAction);assert.ok(!JSON.stringify(saved.frontState).includes('battleAction'));assert.ok(saved.knownSkills.includes('basic.sword'));
  await page.locator('#continue-life').click();await page.getByRole('button',{name:'この人生を続ける',exact:false}).click();await page.waitForFunction(()=>document.querySelector('#game')?.dataset.battlePresentation==='johakyu',null,{timeout:90000});assert.equal(await page.locator('.johakyu-world').count(),1);await page.screenshot({path:out+'/main-resume.png'});assert.deepEqual(errors,[]);report.passed=true;
 }catch(e){report.error=e.stack;await page.screenshot({path:out+'/failure.png'}).catch(()=>{});report.dom=await page.locator('body').innerText().catch(()=>null);throw e;}finally{report.errors=errors;await writeFile(out+'/report.json',JSON.stringify(report,null,2));await context.close();}return report;
}
