import test from 'node:test';
import assert from 'node:assert/strict';
import {SOLO_SESSION,createMenuGate,canPauseWorld} from '../src/story/menu-gate.js';
function rig(initial=SOLO_SESSION,paused=false){let session=initial,state={paused,life:{expired:false}};const pauses=[],inputs=[];let stops=0;const gate=createMenuGate({readSession:()=>session,snapshot:()=>state,pause:value=>{pauses.push(value);state.paused=value;},stopMove:()=>stops++,blockInput:value=>inputs.push(value)});return {gate,pauses,inputs,setSession:value=>session=value,get stops(){return stops;}};}
test('solo nested sheets restore the original pause only after the last sheet closes',()=>{const r=rig();r.gate.open('menu');r.gate.open('map');r.gate.close('menu');assert.deepEqual(r.pauses,[true]);r.gate.close('map');assert.deepEqual(r.pauses,[true,false]);assert.deepEqual(r.inputs,[true,false]);});
test('an already paused solo game remains paused',()=>{const r=rig(SOLO_SESSION,true);r.gate.open('book');r.gate.close('book');assert.deepEqual(r.pauses,[true,true]);});
test('shared menus only stop the local input; the world clock is never paused or resumed',()=>{const r=rig({mode:'shared',phase:'open'});r.gate.open('book');r.gate.open('picker');r.gate.close('picker');r.gate.close('book');assert.deepEqual(r.pauses,[]);assert.deepEqual(r.inputs,[true,false]);assert.equal(r.stops,1);});
test('host migration blocks local commands until authority is open, without taking world authority',()=>{const r=rig({mode:'shared',phase:'open'});r.gate.open('map');r.setSession({mode:'shared',phase:'migrating',epoch:2});r.gate.close('map');assert.deepEqual(r.inputs,[true]);r.setSession({mode:'shared',phase:'open',epoch:2});r.gate.sync();assert.deepEqual(r.inputs,[true,false]);assert.deepEqual(r.pauses,[]);});
test('unknown and closed sessions never expose local clock control',()=>{assert.equal(canPauseWorld({mode:'unknown',phase:'open'}),false);assert.equal(canPauseWorld({mode:'shared',phase:'open'}),false);assert.equal(canPauseWorld({mode:'solo',phase:'closed'}),false);assert.equal(canPauseWorld(SOLO_SESSION),true);});
