import test from 'node:test';import assert from 'node:assert/strict';import{lamportHappenedBefore,relation,vectorCompare,causalButNotSemanticWitness,equalFinalStateDifferentHistory,orderSensitiveFirstClaimWitness,independentPresentationWitness,semanticReadWriteIndependent,clockSkewWitness,multiParentWitness,provenanceNode,verifyProvenanceDag,signedIncompleteProvenanceWitness,targetedRevalidationWitness,explanationContractIssues,linearSequenceDoesNotImplyDependency,witnessNames}from'../scripts/reality-causal-provenance-model.mjs';

test('Lamport happened-before is partial and leaves independent events concurrent',()=>{const hb=lamportHappenedBefore([{id:'a',process:'p1',local:1,kind:'local'},{id:'b',process:'p2',local:1,kind:'local'}]);assert.equal(relation(hb,'a','b'),'concurrent')});
test('a total sequence between concurrent events does not create causal dependence',()=>{assert.equal(linearSequenceDoesNotImplyDependency().weatherAncestorOfRebirth,false)});
test('happened-before can overapproximate semantic dependence',()=>{const w=causalButNotSemanticWitness();assert.equal(w.hbRelation,'before');assert.deepEqual(w.semanticAncestors,['b:recv'])});
test('vector comparison distinguishes causal order and concurrency',()=>{assert.equal(vectorCompare({a:1,b:0},{a:2,b:0}),'before');assert.equal(vectorCompare({a:2,b:0},{a:1,b:1}),'concurrent')});
test('equal final snapshot does not imply equal history',()=>{const w=equalFinalStateDifferentHistory();assert.equal(w.sameFinal,true);assert.notDeepEqual(w.traceA,w.traceB)});
test('conflicting first-claim operations do not commute',()=>{const w=orderSensitiveFirstClaimWitness();assert.equal(w.commute,false);assert.equal(w.ab.owner,'alice');assert.equal(w.ba.owner,'bob')});
test('independent presentation operations commute',()=>{assert.equal(independentPresentationWitness().commute,true)});
test('read-write criterion separates obvious conflicts from independence',()=>{assert.equal(semanticReadWriteIndependent({reads:['hp'],writes:['hp']},{reads:['weather'],writes:['weather']}),true);assert.equal(semanticReadWriteIndependent({reads:['owner'],writes:['owner']},{reads:['owner'],writes:['owner']}),false)});
test('wall-clock skew can reverse observed timestamp order despite causal send-receive',()=>{const w=clockSkewWitness();assert.ok(w.observed.receive<w.observed.send);assert.equal(w.causal,'send-before-receive')});
test('semantic decision can require multiple parents',()=>{const w=multiParentWitness();assert.deepEqual(new Set(w.parents),new Set(['damage','armor','policy']));assert.equal(w.ancestors.length,3)});
test('content-addressed provenance DAG validates intact parent closure',()=>{const a=provenanceNode({kind:'fact',x:1}),b=provenanceNode({kind:'decision'},[a.id]);assert.equal(verifyProvenanceDag([a,b],b.id),true);assert.equal(verifyProvenanceDag([b],b.id),false)});
test('signed intact provenance can still omit a true semantic dependency',()=>{const w=signedIncompleteProvenanceWitness();assert.equal(w.cryptographicallyValid,true);assert.equal(w.complete,false)});
test('targeted revalidation needs semantic causal closure not unrelated world events',()=>{const w=targetedRevalidationWitness();assert.deepEqual(w.closure,['armor','damage','fatal','policy']);assert.ok(w.all.includes('weather'));assert.ok(!w.closure.includes('weather'))});
test('explanation contract requires multi-parent root when decision has several parents',()=>{const issues=explanationContractIssues({effectId:'e',semanticType:'canon',policyRoot:'p',semanticParents:['a','b'],authorityGeneration:3,operationId:'o'});assert.deepEqual(issues,['parent-set-root'])});
test('complete explanation contract includes conditional randomness and sink receipts',()=>{assert.deepEqual(explanationContractIssues({effectId:'e',semanticType:'canon',policyRoot:'p',semanticParents:['a'],authorityGeneration:3,operationId:'o',randomDependent:true,randomnessReceipt:'r',externalEffect:true,sinkReceipt:'s'}),[])});
test('witness registry is distinct',()=>{assert.equal(witnessNames.length,9);assert.equal(new Set(witnessNames).size,9)});
