import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';

const read = path => readFile(new URL(`../${path}`, import.meta.url), 'utf8');

test('Visual Review Lab navigation stays task-oriented and motion selection is contextual', async()=>{
  const ux = await read('src/review/review-ux.js');
  const nav = await read('src/review/unified-review-nav.js');
  const css = await read('src/review/unified-review-nav.css');
  const cssV2 = await read('src/review/unified-review-nav-v2.css');
  const notebook = await read('src/review/notebook.js');
  const legacy = await read('motion-library.html');
  assert.match(ux, /import '.\/unified-review-nav\.js';/);
  assert.match(nav, /\['model', 'モデル'\]/);
  assert.match(nav, /\['skill', '技'\]/);
  assert.match(nav, /\['performance', '演舞'\]/);
  assert.match(nav, /\['battle', '戦闘'\]/);
  assert.match(nav, /\['other', 'その他'\]/);
  assert.match(nav, /const BATTLE_MOTION_ITEMS = \[/);
  assert.match(nav, /\['stance-select', '構え',/);
  assert.match(nav, /\['reaction-select', '被弾',/);
  assert.match(nav, /\['posture-draw', '抜刀',/);
  assert.match(nav, /\['axis', '心技体',/);
  assert.match(nav, /\['playback', '再生・視点',/);
  assert.match(nav, /\['advanced', '詳細調整',/);
  assert.match(nav, /function renderSkillHub\(\)/);
  assert.match(nav, /function renderPerformanceHub\(\)/);
  assert.match(nav, /function renderBattleHub\(\)/);
  assert.match(nav, /url\.searchParams\.set\('tab', 'battle-motion'\)/);
  assert.match(nav, /review-tool-grid/);
  assert.doesNotMatch(nav, /\['motion', 'モーション'\]/);
  assert.doesNotMatch(nav, /motion-library-stage|motion-library\.html\?embed=1/);
  assert.match(css, /grid-template-columns:repeat\(5,minmax\(0,1fr\)\)/);
  assert.match(css, /review-controls-dock \.notebook-head\{display:none!important\}/);
  assert.match(css, /review-shell #source-label\{display:none!important\}/);
  assert.match(css, /review-shell #review-status\{display:none!important/);
  assert.match(css, /review-status\[data-kind=error\]\{display:inline-flex!important\}/);
  assert.match(css, /review-shell \.hud\{[^}]*bottom:82px!important/);
  assert.match(css, /review-tool-grid/);
  assert.match(css, /data-review-section="battle"/);
  assert.match(cssV2, /review-controls-dock:not\(\[data-open="true"\]\)[\s\S]*visibility:hidden!important/);
  assert.match(cssV2, /\.review-category-grid\{[\s\S]*grid-template-columns:repeat\(5,minmax\(0,1fr\)\)!important/);
  assert.match(cssV2, /\.unified-review-navigation \.picker-list\{[\s\S]*grid-template-columns:repeat\(5,minmax\(0,1fr\)\)!important/);
  assert.match(cssV2, /\.unified-review-navigation \.model-picker-list\{[\s\S]*grid-template-columns:repeat\(5,minmax\(0,1fr\)\)!important/);
  assert.match(cssV2, /body\[data-review-section="battle"\][\s\S]*review-page\[data-review-page="battle"\][\s\S]*display:none!important/);
  assert.match(notebook, /id = 'picker-search'/);
  assert.match(notebook, /placeholder = 'モーションを検索'/);
  assert.match(notebook, /option\.dataset\.group/);
  assert.match(notebook, /normalize\(`\$\{option\.textContent\} \$\{option\.value\} \$\{option\.dataset\.group/);
  assert.match(notebook, /STAGES\.includes\(select\.id\).*playValue\(option\.value\)/s);
  assert.match(legacy, /location\.replace\('\.\/'\)/);
  assert.doesNotMatch(ux, /review-motion-link|Motion Libraryを開く|>Motions</);
  assert.match(ux, /textContent='参考'/);
});
