import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const html = readFileSync('apps/rinne/review.html', 'utf8');
const source = readFileSync('apps/rinne/src/review/main.js', 'utf8');
const adapter = readFileSync('apps/rinne/src/review/review-adapter.js', 'utf8');
const vite = readFileSync('apps/rinne/vite.config.js', 'utf8');
const rendering = readFileSync('packages/rendering/src/index.js', 'utf8');
const devcontainer = readFileSync('.devcontainer/devcontainer.json', 'utf8');
const rootPackage = JSON.parse(readFileSync('package.json', 'utf8'));
const previewBuild = readFileSync('scripts/build-review.mjs', 'utf8');
const assetGuard = readFileSync('scripts/check-review-assets.mjs', 'utf8');
const previewWorkflow = readFileSync('.github/workflows/review-preview.yml', 'utf8');
const wrangler = readFileSync('wrangler.review.jsonc', 'utf8');

assert.match(html, /id="review-canvas"/);
assert.match(html, /レビュー情報をコピー/);
assert.match(source, /GLTFLoader/);
assert.match(source, /OrbitControls/);
assert.match(source, /1\s*\/\s*60/);
assert.match(source, /SkeletonHelper/);
assert.match(source, /review-adapter\.js/);
assert.match(adapter, /installReviewExtensions/);
assert.match(vite, /review\.html/);
assert.doesNotMatch(vite, /REVIEW_LAB|CODESPACE_NAME|review-lab-entry/);
assert.match(rendering, /GLTFLoader/);
assert.match(rendering, /OrbitControls/);
assert.doesNotMatch(devcontainer, /postStartCommand|openBrowser|REVIEW_LAB=1/);
assert.equal(rootPackage.scripts['check:review-assets'], 'node scripts/check-review-assets.mjs');
assert.equal(rootPackage.scripts['build:review'], 'node scripts/build-review.mjs && npm run check:review-assets');
assert.match(previewBuild, /build:rinne/);
assert.match(previewBuild, /copyFileSync\(review, appIndex\)/);
assert.match(assetGuard, /MAX_ASSET_BYTES = 25 \* 1024 \* 1024/);
assert.match(assetGuard, /MAX_ASSET_FILES = 20_000/);
assert.match(assetGuard, /approved large-asset path/);
assert.match(previewWorkflow, /work\/visual-review-lab-v2/);
assert.match(previewWorkflow, /npm run build:review/);
assert.match(previewWorkflow, /wrangler@4 deploy/);
assert.match(previewWorkflow, /REVIEW_PREVIEW_ENABLED/);
assert.match(wrangler, /rinne-visual-review/);
assert.match(wrangler, /dist\/rinne/);
