import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {RINNE_UI_VERSION} from '../src/ui-version.js';
const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');
const main=readFileSync(new URL('../src/main.js',import.meta.url),'utf8');
const family=readFileSync(new URL('../src/family-origin-ui.js',import.meta.url),'utf8');
const gameplay=readFileSync(new URL('../src/gameplay-ui.js',import.meta.url),'utf8');
const css=readFileSync(new URL('../src/rinne-world-ui.css',import.meta.url),'utf8');
test('RINNE UI v4 is explicit and visible',()=>{assert.equal(RINNE_UI_VERSION,'4.0.0');assert.match(html,/id="build-label">UI 4\.0\.0/);assert.match(main,/RINNE_UI_VERSION/);assert.match(family,/family-surface-version/);assert.match(gameplay,/gameplay-surface-version/);});
test('family and ritual are rebuilt as scenes rather than flat art cards',()=>{assert.doesNotMatch(family,/familyHomeArt|familyMemoryArt/);assert.match(family,/family-home-worldscape/);assert.match(family,/family-memory-relic/);assert.match(family,/MEMORY_MARKS/);assert.match(css,/landing\.webp/);assert.match(css,/dialog\.family-home-dialog[\s\S]*width:100vw/);assert.match(css,/dialog\.family-origin[\s\S]*height:100dvh/);});
test('gameplay navigation is a sigil dock, radial wheel and full archive',()=>{assert.match(gameplay,/rinne-command-sigils/);assert.match(gameplay,/rinne-wheel-menu/);assert.match(gameplay,/rinne-archive-panel/);assert.match(html,/rinne-life-sigil/);assert.match(css,/\.rinne-wheel-menu[\s\S]*border-radius:50%/);assert.match(css,/\.rinne-archive-panel[\s\S]*height:100dvh/);assert.doesNotMatch(css,/#title-screen\s*\{/);});
