import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {runInNewContext} from 'node:vm';
const scope={module:{exports:{}},URL};
runInNewContext(readFileSync(new URL('../public/session-desk/core.js',import.meta.url),'utf8'),scope);
const C=scope.module.exports;
const s=(extra={})=>C.normalize({id:'test-id-0001',title:'試験用',...extra},extra.source||'manual');
const now=Date.parse('2026-09-12T01:00:00Z');
test('invalid and credential-bearing URLs are rejected',()=>{for(const u of ['javascript:alert(1)','https://evil.test/c/abcdef','http://chatgpt.com/c/abcdef','https://u:p@chatgpt.com/c/abc','https://chatgpt.com/share/abc'])assert.equal(C.chatUrl(u),'');});
test('conversation URLs are canonicalized without query or hash',()=>assert.equal(C.chatUrl('https://chatgpt.com/c/test-1234?q=secret#x'),'https://chatgpt.com/c/test-1234'));
test('project conversation URL accepted',()=>assert.equal(C.chatUrl('https://chatgpt.com/g/project-test/c/12345678'),'https://chatgpt.com/g/project-test/c/12345678'));
test('repository name validated',()=>{assert.equal(C.repo('charukun/soul-lineage'),'charukun/soul-lineage');for(const r of ['owner/../x','https://github.com/o/r','owner/..','owner/','a/b?c'])assert.equal(C.repo(r),'');});
test('declared running without report time remains unknown',()=>assert.equal(s({status:'running'}).status,'unknown'));
test('normalize never carries message bodies, cookies or extra data',()=>{const r=s({body:'secret',mapping:{secret:true},cookies:'secret',title:'A'.repeat(400)});assert.equal(r.title.length,240);assert.ok(!('body'in r)&&!('mapping'in r)&&!('cookies'in r));});
test('export never implies runtime state',()=>{const [r]=C.fromExport([{id:'12345678',title:'完了した',update_time:now/1000,status:'running',mapping:{message:'SECRET'}}]);assert.equal(r.status,'unknown');assert.equal(r.reportedAt,null);assert.equal(r.location,'種別未確認');assert.equal(r.project,'所属未確認');assert.ok(!JSON.stringify(r).includes('SECRET'));});
test('export accepts wrapped form and skips invalid IDs',()=>{const r=C.fromExport({conversations:[{id:'test-1234',project_name:'試験Project'},{id:'bad/url'}]});assert.equal(r.length,1);assert.equal(r[0].project,'試験Project');});
test('unsupported export shape rejected',()=>assert.throws(()=>C.fromExport({foo:[]})));
test('repeat import deduplicates',()=>{const r=C.fromExport([{id:'test-1234',title:'a'}]);assert.equal(C.mergeSessions(r,r).length,1);});
test('export cannot overwrite manual report or project',()=>{const old=s({id:'chat:test-1234',status:'running',reportedAt:now,project:'手動指定'});const [fresh]=C.fromExport([{id:'test-1234',title:'更新後'}]);const [r]=C.mergeSessions([old],[fresh]);assert.equal(r.status,'running');assert.equal(r.project,'手動指定');assert.equal(r.title,'更新後');});
test('old WORK report cannot overwrite newer report',()=>{const old=s({status:'ready',reportedAt:now});const older=s({status:'running',reportedAt:now-10000,source:'work-report'});assert.equal(C.mergeSessions([old],[older])[0].status,'ready');});
test('unknown undated WORK report cannot overwrite newer report',()=>{const old=s({status:'ready',reportedAt:now});assert.equal(C.mergeSessions([old],[s({source:'work-report'})])[0].status,'ready');});
test('manual explicit unknown is allowed',()=>{const old=s({status:'ready',reportedAt:now});assert.equal(C.mergeSessions([old],[s()])[0].status,'unknown');});
test('staleness is report-age, not proven stopped',()=>{const a=s({status:'running',reportedAt:now-91*60000});assert.equal(C.stale(a,now),true);assert.equal(a.status,'running');assert.equal(C.stale(s({status:'completed',reportedAt:now-91*60000}),now),false);});
test('statistics only include registered nonarchived data',()=>{const m=C.stats([s(),s({id:'b',status:'running',reportedAt:now}),s({id:'c',archived:true})],now);assert.equal(m.registered,2);assert.equal(m.runningReported,1);assert.equal(m.attention,1);});
test('task prompt respects WORK/Integration boundary',()=>{assert.match(C.taskText({text:'修正して',role:'WORK'}),/Ready for review/);assert.match(C.taskText({text:'統合して',role:'Integration'}),/既存Integrationルール/);assert.match(C.taskText({text:'修正して'}),/main \/ Production/);});
test('backup restores only allowed schema and fields',()=>{const d=C.empty();d.sessions=[s({evil:'hidden'})];d.settings.repository='javascript:evil';const r=C.restore(d);assert.equal(r.settings.repository,'charukun/soul-lineage');assert.equal(r.github,null);assert.throws(()=>C.restore({sessions:[],tasks:[]}));});
test('GitHub indicators do not become session indicators',()=>{const r=C.githubSummary([{state:'open',draft:true}],[{status:'in_progress'},{status:'completed',conclusion:'failure'}]);assert.equal(r.openPRs,1);assert.equal(r.runningCI,1);assert.equal(r.failedCI,1);assert.ok(!('sessions'in r));});
test('script source never requests private ChatGPT endpoints or model API',()=>{const src=readFileSync(new URL('../public/session-desk/app.js',import.meta.url),'utf8');assert.ok(!src.includes('/backend-api/'));assert.ok(!src.includes('api.openai.com'));assert.ok(!src.includes('innerHTML'));assert.match(src,/crypto\.subtle\.encrypt/);assert.match(src,/credentials:'omit'/);});
