import{acceptHostOffer}from'@soul/network/peer';
import{friendVillageInviteFromLocation}from'@soul/network/friend-invite';
import{World,initial,defs,LIMIT}from'./game/core.js';
import{View}from'./web/view.js';
const $=id=>document.getElementById(id),state=text=>$('friend-state').textContent=text;
let invite=null,peer=null,view=null,last=0,drag=null;
try{invite=friendVillageInviteFromLocation(location);if(!invite)throw Error('友人から届いた招待リンクで開いてください。');$('friend-title').textContent=invite.villageName+'へ';state('この村は友人から明示的に招待された時だけ開けます。');$('friend-connect').disabled=false;}catch(e){state(e.message);}
$('friend-connect').onclick=async()=>{try{$('friend-connect').disabled=true;state('安全なP2P接続を準備しています。');peer=await acceptHostOffer(invite.offer,{RTCPeerConnection,onState:s=>{if(s==='open'){state('村の持ち主へ参加を知らせています。');queueMicrotask(()=>{try{peer?.send({type:'join',role:'visitor',playerId:crypto.randomUUID(),name:'友人の訪問者'});}catch(e){state(e.message);}});}else if(['failed','closed','disconnected','error'].includes(s))state('接続が終了しました。招待し直してもらうと再接続できます。');},onMessage:m=>{if(m?.type==='friend-village')startVisit(m.snapshot);}});$('friend-answer').value=peer.code;$('answer-wrap').hidden=false;state('参加返事を友人へ送ってください。友人が受け取ると村が開きます。');}catch(e){state(e.message);$('friend-connect').disabled=false;}};
$('copy-answer').onclick=async()=>{try{await navigator.clipboard.writeText($('friend-answer').value);state('参加返事をコピーしました。友人へ送ってください。');}catch{state('参加返事を長押ししてコピーしてください。');}};
$('share-answer').onclick=async()=>{const text=$('friend-answer').value;if(!text)return;try{if(navigator.share)await navigator.share({title:'村への参加返事',text});else{await navigator.clipboard.writeText(text);state('参加返事をコピーしました。');}}catch(e){if(e?.name!=='AbortError')state(e.message);}};
function safeSnapshot(snapshot){if(snapshot?.version!==1||typeof snapshot.villageId!=='string'||!snapshot.villageId||typeof snapshot.name!=='string'||!Array.isArray(snapshot.objects)||snapshot.objects.length>800)throw Error('友人の村データが不正です。');const objects=snapshot.objects.map((o,i)=>{if(!o||!Object.hasOwn(defs,o.kind)||typeof o.id!=='string'||o.id.length>60||![o.x,o.z,o.rot].every(Number.isFinite)||Math.abs(o.x)>LIMIT||Math.abs(o.z)>LIMIT)throw Error('友人の村に対応していない配置があります。');return{id:`friend-${i}-${o.id}`.slice(0,60),kind:o.kind,x:o.x,z:o.z,rot:o.rot,material:o.material||'base',level:Math.max(1,Math.min(3,o.level||1)),phase:'built',room:[]};});return{...snapshot,objects};}
function startVisit(raw){try{const snapshot=safeSnapshot(raw),base=initial();base.name=snapshot.name.slice(0,80);base.villageId=snapshot.villageId.slice(0,180);base.objects=snapshot.objects;base.people=[];base.nextId=900000;base.clock=Number.isFinite(snapshot.clock)?snapshot.clock:base.clock;base.time=Number.isFinite(snapshot.time)?snapshot.time:base.time;base.settings={...base.settings,speed:0,tilt:.72,quality:1};base.tutorial={dismissed:true,completed:true};base.defense={...base.defense,nextRaid:1e9,raid:null};const world=new World(base),canvas=$('friend-world');view=new View(canvas,world);view.setTime(base.time);view.span=Math.min(120,Math.max(46,52+snapshot.objects.length*.025));view.updateCamera();document.body.classList.add('visiting');$('friend-tools').hidden=false;installControls(canvas);last=performance.now();requestAnimationFrame(frame);}catch(e){state(e.message);$('friend-connect').disabled=false;}}
function installControls(canvas){canvas.addEventListener('pointerdown',e=>{e.preventDefault();drag={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;drag.x=e.clientX;drag.y=e.clientY;view.pan(dx,dy);});canvas.addEventListener('pointerup',e=>{if(drag?.id===e.pointerId)drag=null;});canvas.addEventListener('pointercancel',()=>drag=null);canvas.addEventListener('wheel',e=>{e.preventDefault();view.zoom(e.deltaY>0?1.12:.89);},{passive:false});$('zoom-in').onclick=()=>view.zoom(.82);$('zoom-out').onclick=()=>view.zoom(1.2);window.addEventListener('resize',()=>view.resize());}
function frame(now){if(!view)return;requestAnimationFrame(frame);const dt=Math.min(.06,Math.max(0,(now-last)/1000));last=now;view.render(now/1000,dt);}
