import {THREE as T} from '@soul/rendering';
import {defs,DAYS_YEAR} from './game/core.js';
import {t,exposeI18n} from './mura-i18n.js';
const {world,view}=window.village;
const $=id=>document.getElementById(id);
exposeI18n();
function currentClimate(){
 const day=Math.floor(world.state.clock),year=Math.floor(world.state.clock/DAYS_YEAR)+1,dayOfYear=((world.state.clock%DAYS_YEAR)+DAYS_YEAR)%DAYS_YEAR,seasonIndex=Math.min(3,Math.floor(dayOfYear/(DAYS_YEAR/4))),season=['spring','summer','autumn','winter'][seasonIndex],cycleYear=((year-1)%6)+1,lightAge=cycleYear<=2?'dawnAge':cycleYear<=4?'dayAge':'duskAge';world.state.climate??={day:-1,weather:'clear'};
 if(world.state.climate.day!==day){const n=(Math.sin(day*12.9898+78.233)*43758.5453)%1,roll=Math.abs(n);let weather='clear';if(season==='winter')weather=roll<.34?'snow':roll<.55?'cloudy':roll<.68?'wind':'clear';else if(season==='summer')weather=roll<.24?'rain':roll<.4?'cloudy':roll<.53?'wind':'clear';else weather=roll<.2?'rain':roll<.42?'cloudy':roll<.55?'wind':'clear';world.state.climate={day,weather};}
 return{day,year,dayOfYear,season,cycleYear,lightAge,weather:world.state.climate.weather};
}

function installSeasonWeather(){
 const count=220,geo=new T.BufferGeometry(),positions=new Float32Array(count*3);for(let i=0;i<count;i++){positions[i*3]=(Math.random()-.5)*80;positions[i*3+1]=Math.random()*45+3;positions[i*3+2]=(Math.random()-.5)*80;}geo.setAttribute('position',new T.BufferAttribute(positions,3));const mat=new T.PointsMaterial({color:0xdce9ee,size:.12,transparent:true,opacity:.55,depthWrite:false});const points=new T.Points(geo,mat);points.visible=false;view.scene.add(points);
 const foliageMaterials=new Set();for(const mesh of view.forestMeshes||[]){const mats=Array.isArray(mesh.material)?mesh.material:[mesh.material];for(const m of mats)if(m?.color){if(m.userData.muraBaseColor==null)m.userData.muraBaseColor=m.color.getHex();foliageMaterials.add(m);}}
 let lastSeason='';function tintFoliage(climate){if(lastSeason===climate.season&&world.state.climate.weather===points.userData.weather)return;lastSeason=climate.season;points.userData.weather=climate.weather;for(const m of foliageMaterials){const base=new T.Color(m.userData.muraBaseColor),hsl={};base.getHSL(hsl);if(hsl.s<.12||hsl.h<.12||hsl.h>.48){m.color.copy(base);continue;}const target={spring:0x8ebc76,summer:m.userData.muraBaseColor,autumn:0xc27645,winter:0x8e9b89}[climate.season];m.color.copy(base).lerp(new T.Color(target),climate.season==='summer'?0:.52);if(climate.weather==='rain'||climate.weather==='cloudy')m.color.multiplyScalar(.88);}}
 let last=performance.now();const animate=now=>{const dt=Math.min(.05,(now-last)/1000);last=now;const c=currentClimate();tintFoliage(c);const wet=c.weather==='rain'||c.weather==='snow';points.visible=wet;mat.size=c.weather==='snow'?.22:.075;mat.opacity=c.weather==='snow'?.72:.52;mat.color.set(c.weather==='snow'?0xf4f5ef:0xbad5e2);if(wet){const a=geo.attributes.position.array;for(let i=0;i<count;i++){a[i*3+1]-=dt*(c.weather==='snow'?3.2:34);if(c.weather==='snow')a[i*3]+=Math.sin(now*.001+i)*dt*.7;if(a[i*3+1]<.2){a[i*3]=(Math.random()-.5)*80;a[i*3+1]=45+Math.random()*15;a[i*3+2]=(Math.random()-.5)*80;}}geo.attributes.position.needsUpdate=true;points.position.x=view.target.x;points.position.z=view.target.z;}
  const cycleTint=new T.Color(c.lightAge==='dawnAge'?0xd6af91:c.lightAge==='duskAge'?0x8793b2:0xcad5c4),seasonTint=new T.Color(c.season==='spring'?0xc8d6b0:c.season==='summer'?0xbad1c8:c.season==='autumn'?0xc69a78:0xa9bbc7);view.scene.background.lerp(cycleTint,.025).lerp(seasonTint,.018);view.scene.fog.color.lerp(view.scene.background,.1);if(c.weather==='cloudy'||c.weather==='rain')view.scene.background.lerp(new T.Color(0x81939a),.08);if(c.weather==='snow')view.scene.background.lerp(new T.Color(0xc8d3d5),.05);
  const hour=Math.floor(world.state.time),minute=Math.floor((world.state.time-hour)*60),cycleNo=Math.floor((c.year-1)/6)+1,calendar=$('calendar');if(calendar)calendar.textContent=`第${cycleNo}輪 · ${c.cycleYear}/6年 · ${t(c.season)} · ${t(c.weather)} · ${String(hour).padStart(2,'0')}:${String(minute).padStart(2,'0')}`;requestAnimationFrame(animate);};requestAnimationFrame(animate);
}

const mats={wood:new T.MeshStandardMaterial({color:0x795b42,roughness:.9}),cloth:new T.MeshStandardMaterial({color:0xb86257,roughness:.95}),metal:new T.MeshStandardMaterial({color:0x556169,roughness:.58,metalness:.35}),stone:new T.MeshStandardMaterial({color:0x8c918b,roughness:1}),gold:new T.MeshStandardMaterial({color:0xc79a4d,roughness:.6,metalness:.18}),green:new T.MeshStandardMaterial({color:0x738f67,roughness:.95}),blue:new T.MeshStandardMaterial({color:0x6f92a2,roughness:.8}),crystal:new T.MeshStandardMaterial({color:0x9b82c5,roughness:.25,emissive:0x302046,emissiveIntensity:.25})};
function box(g,x,y,z,w,h,d,m=mats.wood){const n=new T.Mesh(new T.BoxGeometry(w,h,d),m);n.position.set(x,y,z);g.add(n);return n;}function cyl(g,x,y,z,r,h,m=mats.wood,rotZ=0){const n=new T.Mesh(new T.CylinderGeometry(r,r,h,7),m);n.position.set(x,y,z);n.rotation.z=rotZ;g.add(n);return n;}function sphere(g,x,y,z,r,m=mats.stone){const n=new T.Mesh(new T.SphereGeometry(r,8,6),m);n.position.set(x,y,z);g.add(n);return n;}function cone(g,x,y,z,r,h,m=mats.wood){const n=new T.Mesh(new T.ConeGeometry(r,h,7),m);n.position.set(x,y,z);g.add(n);return n;}
function mayorGear(node){if(!node||node.userData.muraMayor)return;node.userData.muraMayor=true;const g=new T.Group();g.name='MURAAAAAAA_MayorRegalia';const felt=new T.MeshStandardMaterial({color:0x4f725c,roughness:.92}),trim=new T.MeshStandardMaterial({color:0xd4b16d,roughness:.58,metalness:.12}),cloth=new T.MeshStandardMaterial({color:0x9b665d,roughness:.95});const brim=new T.Mesh(new T.CylinderGeometry(.48,.56,.11,12),felt);brim.position.set(0,1.95,0);g.add(brim);const crown=new T.Mesh(new T.ConeGeometry(.38,.62,10),felt);crown.position.set(.03,2.28,0);crown.rotation.z=-.12;g.add(crown);const sash=box(g,.22,1.15,.27,.12,1.05,.07,trim);sash.rotation.z=-.4;const cape=new T.Mesh(new T.SphereGeometry(.58,10,7,0,Math.PI*2,0,Math.PI*.48),cloth);cape.position.set(0,1.17,-.27);cape.scale.set(1,.92,.55);g.add(cape);const staff=cyl(g,.58,1.15,.08,.035,2.25,mats.wood);staff.rotation.z=-.05;sphere(g,.62,2.35,.08,.11,trim);const aura=new T.Mesh(new T.RingGeometry(.56,.72,32),new T.MeshBasicMaterial({color:0xffd783,transparent:true,opacity:.5,depthWrite:false,side:T.DoubleSide}));aura.rotation.x=-Math.PI/2;aura.position.y=.05;g.add(aura);g.userData.aura=aura;node.add(g);node.userData.muraMayorGroup=g;}
function installMayorModel(){const original=view.syncActor.bind(view);view.syncActor=(p,time,monster=false)=>{const r=original(p,time,monster),node=view.actorNodes.get(p.id);if(!monster&&p.role==='mayor'&&node){mayorGear(node);const g=node.userData.muraMayorGroup;if(g?.userData?.aura){g.userData.aura.rotation.z=time*.35;const s=1+Math.sin(time*2.2)*.06;g.userData.aura.scale.setScalar(s);}}return r;};}

installSeasonWeather();
installMayorModel();
window.__MURAAAAAAA_V2_UI__={version:3,currentClimate};
