import {Simulation,Navigation} from './game/simulation.js';
import {DAY_SECONDS,isGuard,isPlayer,ready,defs} from './game/core.js';
import {createSpatialIndex} from '@soul/world/spatial-index';
import {createFlowFieldRouter} from '@soul/world/flow-field';
import {createFixedStepScheduler,createEntityCadenceScheduler} from '@soul/world/simulation-scheduler';
import {createRuntimeProfiler} from '@soul/platform-web/runtime-profiler';
import {View} from './web/view.js';

const simStates=new WeakMap(),navStates=new WeakMap(),scratch=[];
const distance=(a,b)=>Math.hypot((a?.x||0)-(b?.x||0),(a?.z||0)-(b?.z||0));
function stateFor(sim){let state=simStates.get(sim);if(state)return state;state={fixed:createFixedStepScheduler({step:1/30,maxCatchUpSteps:8}),cadence:createEntityCadenceScheduler({maxDeltaSeconds:2}),dynamic:createSpatialIndex({cellSize:12}),objects:createSpatialIndex({cellSize:16}),objectRevision:-1,profiler:createRuntimeProfiler(),ticks:0,activeIds:new Set()};simStates.set(sim,state);if(typeof window!=='undefined')window.__VILLAGE_SIMULATION_SCALE__={snapshot:()=>({fixed:state.fixed.snapshot(),cadence:state.cadence.snapshot(),dynamic:state.dynamic.snapshot(),objects:state.objects.snapshot(),flow:navStates.get(sim.nav)?.snapshot?.()||null,profiler:state.profiler.snapshot()})};return state;}
function rebuildIndexes(sim,state){const world=sim.world;state.dynamic.beginFrame();for(const p of world.people)state.dynamic.upsert(p.id,p.x,p.z,{tag:'person',data:p});for(const a of world.state.wildlife||[])state.dynamic.upsert(a.id,a.x,a.z,{tag:'wildlife',data:a});for(const a of sim.raid?.monsters||[])state.dynamic.upsert(a.id,a.x,a.z,{tag:'raid',data:a});state.dynamic.endFrame();if(state.objectRevision!==world.state.revision){state.objectRevision=world.state.revision;state.objects.clear();state.objects.beginFrame();for(const o of world.objects){const d=defs[o.kind]||{},radius=Math.max(Number(d.w)||0,Number(d.d)||0)/2;state.objects.upsert(o.id,o.x,o.z,{radius,tag:'object',data:o});}state.objects.endFrame();}}
function focusFor(sim){if(sim.__simulationFocus)return sim.__simulationFocus;return sim.world.people.find(isPlayer)||sim.world.people.find(p=>p.role==='mayor')||sim.world.people[0]||{x:0,z:0};}

const originalRoute=Navigation.prototype.route;
Navigation.prototype.route=function sharedFlowRoute(from,to){let router=navStates.get(this);if(!router){router=createFlowFieldRouter({worldStep:2,maxFields:32,maxCells:18000,radiusCells:128});navStates.set(this,router);}const revision=`${this.world.state.revision}:${this.__trafficRevision||0}`,path=router.route({from,to,revision,isBlocked:(x,z)=>this.blocked(x,z),costAt:(x,z)=>this.world.state.traffic[`${x},${z}`]||0});return path===null?originalRoute.call(this,from,to):path;};

const originalUpdate=Simulation.prototype.update;
Simulation.prototype.update=function fixedVillageUpdate(dt){const state=stateFor(this);return state.profiler.measure('simulation',()=>state.fixed.advance(dt,step=>originalUpdate.call(this,step)));};

Simulation.prototype.step=function scaledVillageStep(dt){const state=stateFor(this),w=this.world,s=w.state;state.ticks++;this.elapsed+=dt;s.clock+=dt/DAY_SECONDS;s.time=(s.clock%1)*24;this.nav.__trafficRevision=this.trafficRevision;rebuildIndexes(this,state);
 this.arrivalTimer-=dt;if(this.arrivalTimer<=0){this.arrivalTimer=27;this.arrive();}
 this.assignmentTimer-=dt;if(this.assignmentTimer<=0){this.assignmentTimer=5;this.assignJobs();this.merchant();w.discover();}
 this.constructionTimer+=dt;if(this.constructionTimer>=.5){this.construction(this.constructionTimer);this.constructionTimer=0;}
 this.ship(dt);this.updateRaid(dt);const focus=focusFor(this),activeIds=state.activeIds;activeIds.clear();
 for(const p of w.people){activeIds.add(String(p.id));if(p.downed||p.remoteControlled)continue;const d=distance(p,focus),important=isGuard(p)||isPlayer(p)||p.role==='mayor'||p.task==='defending'||(this.raid?.phase==='active'&&d<80),decision=state.cadence.consume(p.id,dt,d,{important,combat:p.task==='defending'});p.simulationTier=decision.tier;p.simulationHz=decision.hz;
  // Path following stays at the fixed 30 Hz authority step so lower AI cadence does not create visible teleporting.
  if(p.task==='walk'){if(decision.due){p.hunger=Math.max(0,(p.hunger??80)-decision.delta*.34);p.decorateRetry=Math.max(0,(p.decorateRetry||0)-decision.delta);}this.walk(p,dt);continue;}
  if(!decision.due)continue;const pdt=decision.delta;p.hunger=Math.max(0,(p.hunger??80)-pdt*.34);p.decorateRetry=Math.max(0,(p.decorateRetry||0)-pdt);if(isGuard(p)){this.guardStep(p,pdt);continue;}if(p.bubble&&p.bubble.until<this.elapsed)p.bubble=null;p.moving=false;p.timer-=pdt;if(p.timer>0)continue;if(p.task==='idle')this.decide(p);else this.finish(p);}
 if(state.ticks%300===0)state.cadence.sweep(activeIds);rebuildIndexes(this,state);this.updateWildlife(dt);this.rescueAndRecovery(dt);this.momentTimer-=dt;if(this.momentTimer<=0){this.momentTimer=22+this.random()*15;this.quietMoments();}this.decayTimer+=dt;if(this.decayTimer>8){const factor=Math.pow(.98,this.decayTimer/60);for(const[k,v]of Object.entries(s.traffic)){if(v*factor<.02)delete s.traffic[k];else s.traffic[k]=v*factor;}this.decayTimer=0;this.trafficRevision++;}
};

const originalNearbyGuard=Simulation.prototype.nearbyGuard;
Simulation.prototype.nearbyGuard=function indexedNearbyGuard(p){const state=stateFor(this),row=state.dynamic.nearest(p.x,p.z,{radius:11,tag:'person',filter:r=>{const g=r.data;return g!==p&&isGuard(g)&&g.health>0&&!g.downed;}});return row?.data||originalNearbyGuard.call(this,p);};

Simulation.prototype.updateWildlife=function indexedWildlife(dt){const state=stateFor(this),w=this.world,s=w.state;if(s.clock>=s.defense.nextWildlife){s.defense.nextWildlife=s.clock+3+this.random()*2;this.spawnWildlife();}for(const a of s.wildlife){if(a.health<=0)continue;const radius=a.hostile?20:8,row=state.dynamic.nearest(a.x,a.z,{radius,tag:'person',filter:r=>{const p=r.data;return !p.downed&&!p.insideId&&p.health>0;}}),vulnerable=row?.data;if(a.hostile&&vulnerable){a.targetId=vulnerable.id;if(distance(a,vulnerable)<2.6){a.moving=false;this.hurt(vulnerable,dt*(a.damage||5),'wildlife');}else this.threatMotion(a,vulnerable,dt,a.speed||2.1);if(!a.warned){a.warned=true;this.remember(vulnerable,'野生動物の気配に気づいた','護衛のそばへ');}}else{a.wanderTime=(a.wanderTime||0)-dt;if(a.wanderTime<=0){a.wanderTime=8+this.random()*10;const angle=this.random()*6.28,r=5+this.random()*12;a.wanderTarget={x:a.homeX+Math.cos(angle)*r,z:a.homeZ+Math.sin(angle)*r};a.repath=0;}if(a.wanderTarget&&distance(a,a.wanderTarget)>2)this.threatMotion(a,a.wanderTarget,dt,a.hostile?1.1:a.species==='rabbit'?1.5:1);else a.moving=false;}}const dead=s.wildlife.filter(a=>a.health<=0);if(dead.length){s.stats.defeated+=dead.length;for(const a of dead)if(a.hostile){w.gain('leather',1);this.emit('護衛が野生動物を追い払い、落ち着きを取り戻しました','rescue');}s.wildlife=s.wildlife.filter(a=>a.health>0);}};

Simulation.prototype.updateRaid=function indexedRaid(dt){const state=stateFor(this),w=this.world,s=w.state;if(!this.raid){if(s.clock>=s.defense.nextRaid-.75)this.startRaid();return;}const r=this.raid;if(r.phase==='warning'){if(s.clock<r.startDay)return;r.phase='active';s.stats.raids++;this.emit('魔王軍が村へ。住人は屋内へ避難し、警備職が迎撃します。','threat');for(const p of w.people)if(!isGuard(p)){p.task='idle';p.timer=0;p.path=[];}}r.age+=dt;const fire=w.objects.find(o=>o.kind==='campfire');for(const a of r.monsters){if(a.health<=0)continue;const row=state.dynamic.nearest(a.x,a.z,{radius:240,tag:'person',filter:x=>{const p=x.data;return !p.downed&&p.health>0&&!p.insideId;}}),target=row?.data;if(target&&distance(a,target)<2.5){a.moving=false;this.hurt(target,dt*(a.damage||r.budget.damage),'monster');}else this.threatMotion(a,target||fire,dt,a.speed||1.5);state.objects.queryRadiusInto(scratch,a.x,a.z,30,{tag:'object'});for(const record of scratch){const o=record.data;if(!ready(o))continue;const d=distance(a,o);if(['watchtower','wardlamp'].includes(o.kind)&&d<(o.kind==='wardlamp'?16:28)){const staffed=o.kind==='wardlamp'||w.people.some(p=>p.jobId===o.id);if(staffed)a.health=Math.max(0,a.health-dt*(o.kind==='wardlamp'?3:4)*(o.level||1));}if(defs[o.kind].building&&d<8)o.damage=Math.min(80,(o.damage||0)+dt*(o.material==='stone'?.25:.6));}}
 const before=r.monsters.length;r.monsters=r.monsters.filter(a=>a.health>0);s.stats.defeated+=before-r.monsters.length;if(!r.monsters.length||r.age>100){const won=!r.monsters.length;this.raid=null;s.defense.lastRaid=s.clock;s.defense.nextRaid=s.clock+12+this.random()*2;this.emit(won?'村を守りきりました。住人が小径へ戻ってきます。':'魔王軍が退いていきました。村はゆっくり元の暮らしへ。','rescue');this.moment('焚き火のまわりに、いつもの暮らしが戻りました。',w.people.slice(0,2));}};

const render=View.prototype.render;
if(typeof render==='function'&&!render.__simulationScaleFocus){const wrapped=function simulationScaleFocus(...args){const sim=globalThis.window?.village?.sim;if(sim){const focus=sim.__simulationFocus||(sim.__simulationFocus={x:0,z:0});focus.x=this.target?.x||0;focus.z=this.target?.z||0;}return render.apply(this,args);};wrapped.__simulationScaleFocus=true;View.prototype.render=wrapped;}
