"""Canonical scout's measured spec authoring. All meshing is performed by upstream.

This file is fixture DATA authoring, not the Forge reconstruction engine. Pixel
measurements belong to the recorded reference. Another subject requires its own
observations and spec; replacing only the source image cannot reuse these numbers.
"""
import os,sys,copy,math
from pathlib import Path
from PIL import Image,ImageDraw
r=Path(os.environ['FORGE_REPO']);sys.path.insert(0,str(r/'packages/assets/forge'))
from upstream.engine import Engine,save_json,load_json
up=Path(os.environ['IMG2THREEJS_ROOT']);w=Path(os.environ['FORGE_WORKSPACE'])
e=Engine(upstream=up,plugin=Path(os.environ['IMG2THREEJS_PLUGIN']),cache=Path(os.environ['FORGE_CACHE']))
s=load_json(w/'img2threejs/object-sculpt-spec.json');a=load_json(w/'img2threejs/assessment.json')
s['preSpecAssessment']=a['preSpecAssessment'];s['qualityContract']=a['qualityContract'];s['targetId']='canonical-scout-upstream'
template=copy.deepcopy(s['componentTree'][1]);mt={m['id']:m for m in s['materials']};scale=1.6/260
components=[];positions={'root':[0,0,0]}
def xyz(x,y,z=0):return [(x-60)*scale,(265-y)*scale,z*scale]
def comp(id,material,pos,dimensions=(1,1,1),primitive='ellipsoid',level='meso',parent='root',descriptor=None,layer='L3',rotation=None):
 c=copy.deepcopy(template);c.update(id=id,name=id,material=material,materialLayers=[material],parent=parent,primitive=primitive,level=level,importance=.9,confidence=.75)
 positions[id]=list(pos);pp=positions.get(parent,[0,0,0]);c['transform']={'position':[pos[k]-pp[k] for k in range(3)],'rotation':rotation or [0,0,0],'scale':list(dimensions)}
 c['dimensions']={'width':dimensions[0],'height':dimensions[1],'depth':dimensions[2],'units':'metre','confidence':.75}
 c['topologyClass']='assembled-solid';c['topologyRationale']='Observed '+id+' volume; '+layer+' geometry generated by pinned upstream from source measurements.'
 c['geometryDescriptor'].update(descriptor or {});c['geometryDescriptor']['uvStrategy']='generated';c['attachment']=None
 c['evidenceRefs']=['img2threejs/observation.json','source/front.png','source/side.png','source/back.png'];c['fidelityTier']='reference-reconstruction';c['primaryLayer']=layer
 c['localFeatures']=[{'id':id+'-outline','description':'Observed outline and surface identity for '+id,'evidenceRefs':c['evidenceRefs']}]
 c['surfaceDetail']['notes']='Source projection is required later. Hidden surfaces are inferred. No retired model texture is reused.'
 c['actionProfile']['collider']['scale']=list(dimensions);c['actionProfile']['destruction']['debrisMaterial']=material;c['actionProfile']['destruction']['fractureGroup']=id
 if parent:
  local=c['transform']['position'];c['attachment']={'parentSocket':parent+'-to-'+id,'localStart':local,'localEnd':[local[0],local[1]+.01,local[2]],'contactType':'rigid-weld' if layer=='L3' else 'soft-attach','baseRadius':.01,'endRadius':.005,'embedDepth':.01,'gapTolerance':.01,'evidenceRefs':c['evidenceRefs']}
  par=next((q for q in components if q['id']==parent),None)
  if par:par['actionProfile']['sockets'].append({'id':parent+'-to-'+id,'localPosition':local,'localRotation':[0,0,0],'purpose':'observed-part-attachment'})
 components.append(c);return c
comp('root','hidden',[0,0,0],(.0001,.0001,.0001),'box','macro',None)
comp('pelvis','skin',xyz(60,139),(.23,.15,.14),level='macro',layer='L0')
comp('abdomen','shirt',xyz(60,123),(.21,.19,.15),level='macro',parent='pelvis',layer='L0')
comp('chest','shirt',xyz(60,93),(.24,.27,.16),level='macro',parent='abdomen',layer='L0')
comp('neck','skin',xyz(60,60),(.08,.09,.085),parent='chest',layer='L0')
prims=[{'id':'cranium','type':'ellipsoid','radii':[.118,.143,.116],'center':[0,.036,-.016]},
 {'id':'jaw','type':'ellipsoid','radii':[.092,.053,.089],'center':[0,-.055,.02]},
 {'id':'nose-form','type':'ellipsoid','radii':[.020,.025,.026],'center':[0,-.034,.118]},
 {'id':'cheek-l','type':'ellipsoid','radii':[.035,.041,.034],'center':[.065,-.039,.077]},
 {'id':'cheek-r','type':'ellipsoid','radii':[.035,.041,.034],'center':[-.065,-.039,.077]}]
ops=[{'id':'jaw-union','type':'smooth-union','left':'cranium','right':'jaw','radius':.040},
 {'id':'nose-union','type':'smooth-union','left':'jaw-union','right':'nose-form','radius':.018},
 {'id':'cheek-union-l','type':'smooth-union','left':'nose-union','right':'cheek-l','radius':.025},
 {'id':'cheek-union-r','type':'smooth-union','left':'cheek-union-l','right':'cheek-r','radius':.025}]
c=comp('head','skin',xyz(59,37,-.5),level='macro',parent='neck',layer='L0',descriptor={'sdf':{'primitives':prims,'operations':ops,'resolution':40,'bounds':{'min':[-.16,-.16,-.16],'max':[.16,.19,.17]}}})
c['topologyClass']='implicit';c['topologyRationale']='Continuous observed cranium, jaw, cheeks and nose using upstream smooth-union fields; not an eye-textured sphere.'

def poly_mask(name,view,points,size,flip=False):
 im=Image.new('L',size,0);ImageDraw.Draw(im).polygon(points,fill=255)
 if flip:im=im.transpose(Image.Transpose.FLIP_LEFT_RIGHT)
 path=w/'img2threejs/masks'/f'{name}-{view}.png';path.parent.mkdir(parents=True,exist_ok=True);im.save(path)
 pixels=list(im.resize((96,96),Image.Resampling.NEAREST).getdata())
 return [''.join('1' if v>127 else '0' for v in pixels[y*96:(y+1)*96]) for y in range(96)]
def hull(id,material,frontPolygon,sidePolygon,frontSize,sideSize,pos,bounds,frontRef,sideRef,parent):
 fm=poly_mask(id,'front',frontPolygon,frontSize);sm=poly_mask(id,'side',sidePolygon,sideSize,True)
 d={'projection':'orthographic','boundsSpace':'component-local','bounds':bounds,'resolution':20,'triangleBudget':96000,'views':[{'axis':'front','confidence':.8,'mask':fm},{'axis':'side','confidence':.75,'mask':sm}],'hiddenRegions':['Silhouette hulls cannot recover unseen concavities or occluded interiors.']}
 save_json(w/f'img2threejs/masks/{id}-hull.json',d)
 e.run('forge/stage3_build/visual_hull.py',[f'img2threejs/masks/{id}-hull.json','--out',f'img2threejs/masks/{id}-hull-measured.json'],w)
 c=comp(id,material,pos,level='macro',parent=parent,descriptor={'visualHull':d},layer='L4' if id=='cape' else 'L3')
 c['evidenceRefs']=[frontRef,sideRef,'source/back.png','img2threejs/observation.json']
 c['topologyRationale']='Original upstream silhouette-cone intersection retained as raw constraint geometry. This pin forbids combined subdivision; refinement is a separate recorded stage.'
 return c
hull('cape','green',[(30,0),(49,0),(59,9),(69,30),(83,42),(74,48),(64,51),(17,51),(0,43),(12,24),(20,8)],[(14,0),(34,0),(43,9),(45,32),(47,50),(15,51),(0,46),(6,24),(10,9)],(84,52),(48,52),xyz(60,86,0),{'min':[-.257,-.16,-.142],'max':[.257,.16,.142]},'source/front.png:18,60,102,112','source/side.png:22,60,70,112','chest')
hull('hair','hair',[(30,0),(43,2),(55,10),(65,21),(70,39),(65,46),(51,50),(19,50),(5,46),(0,34),(7,20),(17,7)],[(15,0),(35,2),(47,12),(51,25),(47,39),(36,49),(9,47),(0,33),(5,12)],(71,51),(52,51),xyz(59,31,-9),{'min':[-.219,-.157,-.123],'max':[.219,.157,.061]},'source/back.png:bob silhouette mirrored to +X','source/side.png:rear bob; front boundary under fringe is occluded','head')

def sweep(id,material,stations,parent='root',level='meso',layer='L1',radial=16):
 c=comp(id,material,[0,0,0],primitive='tapered-sweep',parent=parent,level=level,layer=layer,descriptor={'taperedSweep':{'stations':[{'position':p,'rx':rx,'rz':rz} for p,rx,rz in stations],'radialSegments':radial,'capEnds':True}})
 c['transform']['position']=[-v for v in positions.get(parent,[0,0,0])];return c
for j,(x0,x1,ytip,rx) in enumerate([(49,41,44,5),(53,47,37,5.5),(58,54,36,5.5),(63,63,38,6),(68,71,36,5),(73,81,44,5)]):
 sweep('bang-'+str(j),'hair',[(xyz(x0,12,13),.012,rx*scale*.45),(xyz((x0+x1)/2,22,18),.028,rx*scale),(xyz(x1,ytip-5,18),.014,rx*scale*.72),(xyz(x1,ytip,15),0,0)],'head',layer='L3')
for side,sign in [('l',1),('r',-1)]:
 for j in range(3):
  xx=60+sign*(23+j*2)
  sweep(f'hair-side-{side}-{j}','hair',[(xyz(60+sign*18,14,3-j*3),.015,.028),(xyz(xx,29,7-j*4),.030,.035),(xyz(xx+sign*2,46,4-j*4),.018,.024),(xyz(xx-sign*4+j,54+j%2,2-j*4),0,0)],'head',layer='L3')

def lathe(id,mat,center,profile,scalevec,parent,level='meso'):
 return comp(id,mat,center,scalevec,'lathe',level,parent,{'latheProfile':{'points':profile,'segments':40,'phiStart':0,'phiLength':math.tau}},'L3')
lathe('collar','green',xyz(60,61),[[.5,-.5],[.55,-.42],[.53,.42],[.49,.5],[.39,.5],[.40,-.5],[.5,-.5]],[.115,.068,.115],'neck')
lathe('belt','leather',xyz(60,120),[[.5,-.5],[.51,-.4],[.51,.4],[.5,.5],[.46,.5],[.46,-.5],[.5,-.5]],[.248,.057,.176],'pelvis')
for id,dx,dy,dims in [('buckle-top',0,-.018,(.056,.009,.013)),('buckle-bottom',0,.018,(.056,.009,.013)),('buckle-left',-.024,0,(.009,.042,.013)),('buckle-right',.024,0,(.009,.042,.013))]:
 comp(id,'brass',[dx,xyz(60,120)[1]+dy,.092],dims,'box','micro','belt',{'subdivide':{'iterations':1}})
for side,sgn in [('l',1),('r',-1)]:
 def X(offset,y,z=0):return xyz(60+sgn*offset,y,z)
 sweep('upper-arm-'+side,'shirt',[(X(18,72),.043,.045),(X(25,87),.047,.049),(X(32,103),.043,.048)],'chest',layer='L0')
 sweep('sleeve-'+side,'shirt',[(X(30,100),.047,.048),(X(34,113),.054,.054),(X(37,126),.044,.045),(X(38,130),.029,.030)],'chest',layer='L4')
 sweep('forearm-'+side,'skin',[(X(33,104),.029,.032),(X(38,132),.026,.029),(X(41,142),.022,.025)],'chest',layer='L0')
 comp('cuff-'+side,'leather',X(38,131),(.079,.049,.077),'ellipsoid','meso','chest')
 sweep('hand-'+side,'skin',[(X(41,138),.020,.024),(X(41.5,145,1),.020,.025),(X(41,153,2),.012,.016)],'chest',layer='L0')
 for j in range(4):
  sweep(f'finger-{side}-{j}','skin',[(X(39+j*1.2,146,2),.0045,.005),(X(38.6+j*1.35,155-(j==0)*2,2),.003,.003),(X(38.5+j*1.35,155.7-(j==0)*2,2),0,0)],'chest',level='micro',layer='L3',radial=8)
 sweep('thigh-'+side,'skin',[(X(13,144),.059,.064),(X(13.5,156),.055,.059),(X(14.5,174,1),.045,.048),(X(15.3,187,2),.036,.039),(X(15.5,195,1),.035,.037)],'pelvis',layer='L0')
 sweep('shin-'+side,'skin',[(X(15.5,188,1),.036,.038),(X(17.5,203,0),.043,.044),(X(18,213,-1),.040,.037),(X(17.5,229,-2),.027,.028),(X(17.5,241,-2),.025,.027)],'pelvis',layer='L0')
 sweep('shorts-'+side,'pants',[(X(13,130),.062,.077),(X(13,141),.068,.080),(X(14,151),.067,.074)],'pelvis',layer='L4')
 lathe('short-hem-'+side,'shirt',X(14,150),[[.5,-.5],[.53,-.4],[.53,.4],[.49,.5],[.43,.5],[.43,-.5],[.5,-.5]],[.142,.046,.157],'pelvis')
 comp('sock-'+side,'shirt',X(18,216,-2),(.057,.059,.062),parent='pelvis')
 lathe('boot-cuff-'+side,'green',X(18,229,-2),[[.55,-.5],[.48,-.4],[.43,.5],[.50,.55],[.59,-.48],[.55,-.5]],[.114,.078,.126],'pelvis')
 bp=[{'id':'toe','type':'ellipsoid','radii':[.046,.043,.082],'center':[0,.046,.063]},{'id':'instep','type':'ellipsoid','radii':[.041,.074,.054],'center':[0,.086,.003]},{'id':'ankle','type':'ellipsoid','radii':[.038,.058,.046],'center':[0,.151,-.027]},{'id':'heel','type':'box','size':[.071,.045,.057],'center':[0,.025,-.042]}]
 bo=[{'id':'a','type':'smooth-union','left':'toe','right':'instep','radius':.02},{'id':'b','type':'smooth-union','left':'a','right':'ankle','radius':.025},{'id':'c','type':'smooth-union','left':'b','right':'heel','radius':.013}]
 c=comp('boot-'+side,'leather',[sgn*.11,0,-scale],parent='pelvis',descriptor={'sdf':{'primitives':bp,'operations':bo,'resolution':36,'bounds':{'min':[-.062,-.005,-.09],'max':[.062,.22,.155]}}})
 c['topologyClass']='implicit';c['topologyRationale']='Source-constrained rounded toe, instep, ankle and heel with real depth; upstream SDF mesh.'
 comp('sole-'+side,'sole',X(18,263,2),(.085,.025,.18),'box','micro','pelvis',{'subdivide':{'iterations':1}})
 comp('heel-'+side,'sole',X(18,260,-7),(.074,.05,.044),'box','micro','pelvis',{'subdivide':{'iterations':1}})
comp('pouch','leather',xyz(84,125,-1),(.073,.093,.036),'box','meso','pelvis',{'subdivide':{'iterations':2}})
for j,(x,y) in enumerate([(50,86),(70,86),(47,101),(72,101)]):comp('cape-button-'+str(j),'brass',xyz(x,y,22),(.023,.023,.013),'ellipsoid','micro','cape')

# Non-pointed body/cloth is represented by original smooth-union SDF descriptors,
# never by fake tapered tips to evade the hair-specific validator.
for c in components:
 if not c['id'].startswith(('upper-arm-','sleeve-','forearm-','hand-','thigh-','shin-','shorts-')):continue
 stations=c['geometryDescriptor']['taperedSweep']['stations'];primitives=[];ops=[]
 for j,(a,b) in enumerate(zip(stations,stations[1:])):
  pa,pb=a['position'],b['position'];delta=[pb[k]-pa[k] for k in range(3)];length=math.sqrt(sum(v*v for v in delta));mid=[(pa[k]+pb[k])/2 for k in range(3)];rx=(a['rz']+b['rz'])/2;rz=(a['rx']+b['rx'])/2
  primitives.append({'id':c['id']+'-'+str(j),'type':'ellipsoid','radii':[rx,length/2+min(rx,rz)*.75,rz],'transform':{'position':mid,'rotation':[0,0,math.atan2(-delta[0],delta[1])]}})
  if j:ops.append({'id':c['id']+'-union-'+str(j),'type':'smooth-union','left':primitives[0]['id'] if j==1 else c['id']+'-union-'+str(j-1),'right':primitives[j]['id'],'radius':min(rx,rz)*.3})
 bounds={'min':[min(a['position'][k]-max(a['rx'],a['rz'])*1.2 for a in stations) for k in range(3)],'max':[max(a['position'][k]+max(a['rx'],a['rz'])*1.2 for a in stations) for k in range(3)]}
 c.update(primitive='ellipsoid',topologyClass='implicit',level='macro',topologyRationale='Continuous organic/cloth volume along measured joint and profile samples. Upstream SDF union preserves measured widths and depths.')
 c['geometryDescriptor'].pop('taperedSweep');c['geometryDescriptor']['sdf']={'primitives':primitives,'operations':ops,'bounds':bounds,'resolution':32}

materials=[]
palettes={'skin':('#f5cbb5',.73),'hair':('#ad7755',.65),'green':('#657036',.86),'shirt':('#e8e1d5',.88),'pants':('#403c3b',.9),'leather':('#4b3529',.66),'brass':('#bd9861',.34),'sole':('#241c19',.87),'hidden':('#808080',1)}
for id,(color,rough) in palettes.items():
 m=copy.deepcopy(mt.get(id,mt.get('skin')));m.update(id=id,name=id,baseColor=color,localOverrides=[],opacity={'base':0 if id=='hidden' else 1},doubleSided=False)
 m['albedo']={'baseColor':color,'palette':[color],'notes':'Flat color is inferred fallback until real camera-projection baking has passed.'}
 m['roughness']={'base':rough,'variation':.02};m['metalness']={'base':1 if id=='brass' else 0,'variation':0}
 m['normal']={'pattern':'none','strength':0,'scale':1,'space':'tangent'};m['bump']={'pattern':'none','amplitude':0,'scale':1};m['displacement']={'pattern':'none','amplitude':0,'scale':1,'silhouetteAffects':False}
 m['surfaceFrequencyBands']=[];m['clearcoat']={'base':.06 if id in ['skin','hair','leather'] else 0};materials.append(m)
matmap={m['id']:m for m in materials};cm={c['id']:c for c in components}
for d in s['preSpecAssessment']['detailInventory']['details']:
 if d['kind']=='painted-mark':d['kind']='decal'
 owner=d['mapsTo']['ref'].split('.')[0];feature=d['id']
 if d['affects']=='material':
  owner={'leather':'leather','green':'green','skin':'skin'}.get(owner,'green');matmap[owner]['localOverrides'].append({'id':feature,'description':d['description'],'evidenceRefs':[d['evidenceRef']],'implementation':'multi-view source projection bake required'})
 else:
  owner={'sleeves':'sleeve-l','shorts':'short-hem-l','boots':'boot-l','buckle':'buckle-top'}.get(owner,owner)
  if owner not in cm:owner='hair'
  cm[owner]['localFeatures'].append({'id':feature,'description':d['description'],'evidenceRefs':[d['evidenceRef']]})
 d['mapsTo']['ref']=owner+'/'+feature
cm['root']['colorMaterialRecipe']={'dominantAlbedo':'rgba(128, 128, 128, 0)','secondaryAlbedo':'rgba(128, 128, 128, 0)','materialClass':'unknown','materialClassConfidence':0,'evidenceRefs':['Intentionally invisible structural origin.']}
matmap['hidden']['qualityTier']='utility'
s['componentTree']=components;s['materials']=materials
s['repetitionSystems']=[{'id':'cape-fastener-set','level':'micro','role':'four observed front fasteners','count':4,'elementComponentIds':['cape-button-'+str(i) for i in range(4)],'buildsGeometry':True,'material':'brass','evidenceRefs':['source/front.png:buttons'],'placement':'two source-observed front columns'}]
if not any(p['id']=='structural-pass' for p in s['buildPasses']):s['buildPasses'].insert(1,{'id':'structural-pass','goal':'Verify separate layered surfaces and observed attachments.','componentRefs':[],'acceptance':['No detached body or garment components; preserve measured world-space placement.']})
for p in s['buildPasses']:p['componentRefs']=[c['id'] for c in components]
s['rigIntent']=s.pop('rig',None)
s['referenceCamera']=load_json(w/'img2threejs/camera-front-starter.json').get('referenceCamera',load_json(w/'img2threejs/camera-front-starter.json'))
s['lightingFromPhoto']=[{'type':'key','direction':[-1,2,3],'intensity':1.4,'notes':'Broad illustration-like upper-front lighting, not physical inverse rendering.'},{'type':'fill','intensity':2,'notes':'Neutral environment; no tone mapping for albedo comparisons.'},{'type':'ground-shadow','notes':'Beauty only; exclude floor from silhouette captures.'}]
s['coordinateFrame'].update(upAxis='+Y',forwardAxis='+Z',units='metre')
s['performanceBudget']['targetTriangles']=60000
s['assumptions']=['Source-specific measured fixture, not a generic starter.','Hidden internal skin, scalp and cloth are inferred; visible silhouette and proportion remain observed constraints.','Raw geometry is unbound. Repair and freeze before Stage R additive binding.','Visual hull is used only for compatible masked orthographic part views. Back is never Top.']
save_json(w/'img2threejs/object-sculpt-spec.json',s)
print('Authored source-constrained components:',len(components))
