/** Diagnostic readback of the actual exported GLB; never a pass approval. */
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {resolve,join,extname} from 'node:path';
import {createHash} from 'node:crypto';
const w=resolve(process.argv[2]),repo=resolve(import.meta.dirname,'../..'),out=join(w,'review/material-pass/albedo-diagnostic');await mkdir(out,{recursive:true});
const app=`import * as THREE from 'three';import{GLTFLoader}from'three/addons/loaders/GLTFLoader.js';import{applyReferenceCamera}from'/adapters/reference_camera.js';
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setSize(540,1080);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.NoToneMapping;document.body.append(renderer.domElement);
const scene=new THREE.Scene();scene.background=new THREE.Color('white');const camera=new THREE.PerspectiveCamera();const cams=await(await fetch('/img2threejs/evidence/cameras.json')).json();
const gltf=await new GLTFLoader().loadAsync('/build/material-pass.glb');const root=gltf.scene;scene.add(root);const saved=new Map();root.traverse(n=>{if(n.isMesh){saved.set(n,n.material);n.material=new THREE.MeshBasicMaterial({map:n.material.map,color:n.material.color,side:n.material.side});}});
window.draw=view=>{applyReferenceCamera(THREE,camera,cams[view]||cams.front);root.rotation.y=({front:0,back:Math.PI,front34:-Math.PI/4})[view];root.updateMatrixWorld(true);renderer.render(scene,camera);};window.ready=true;`;
const html='<!doctype html><style>body{margin:0}canvas{display:block}</style><script type="importmap">{"imports":{"three":"/vendor/build/three.module.js","three/addons/":"/vendor/examples/jsm/"}}</script><script type="module" src="/app.js"></script>';
const server=createServer(async(req,res)=>{try{const p=new URL(req.url,'http://localhost').pathname;if(p==='/'){res.setHeader('Content-Type','text/html');res.end(html);return;}if(p==='/app.js'){res.setHeader('Content-Type','text/javascript');res.end(app);return;}if(p==='/favicon.ico'){res.writeHead(204);res.end();return;}const base=p.startsWith('/vendor/')?join(repo,'node_modules/three'):p.startsWith('/adapters/')?join(repo,'packages/assets/forge'):w;const file=resolve(base,p.replace(/^\/(vendor|adapters)\//,'').replace(/^\//,''));if(!file.startsWith(base+'/'))throw Error('Path escape');res.setHeader('Content-Type',({'.js':'text/javascript','.json':'application/json','.png':'image/png','.glb':'model/gltf-binary'}[extname(file)]||'application/octet-stream'));res.end(await readFile(file));}catch(e){res.writeHead(404);res.end(String(e));}});
await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;
try{const{chromium}=await import('@playwright/test');browser=await chromium.launch({args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--no-sandbox']});const page=await browser.newPage({viewport:{width:540,height:1080}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.ready,null,{timeout:60000});for(const v of ['front','back','front34']){await page.evaluate(v=>window.draw(v),v);await page.locator('canvas').screenshot({path:join(out,v+'.png')});}await writeFile(join(out,'receipt.json'),JSON.stringify({sourceHead:process.env.HEAD_SHA,modelSha256:createHash('sha256').update(await readFile(join(w,'build/material-pass.glb'))).digest('hex'),diagnostic:'Actual GLB albedo through unlit MeshBasicMaterial; all PBR/lighting disabled only for causal diagnosis',visualApproval:'not-applicable',errors},null,2));if(errors.length)throw Error(JSON.stringify(errors));}finally{await browser?.close();server.close();}
