/** Explicit task-only authoring transport. Not part of normal Fast DEV. */
import {execFileSync} from 'node:child_process';
import {mkdirSync,writeFileSync,readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const run=(program,args)=>execFileSync(program,args,{stdio:'inherit'});
run('python3',['packages/assets/forge/upstream_engine.py','materialize','--key','harness']);
run('python3',['scripts/character-forge/verify_upstream.py']);
const out='test-results/character-forge-upstream';mkdirSync(out,{recursive:true});
run('python3',['scripts/character-forge/audit_targets.py','--out',out+'/adapter-target-discovery.json']);
run('node',['--test','packages/characters/tests/character-expressions.test.mjs']);
run('python3',['-m','pip','install','-r','packages/assets/forge/requirements.txt']);
run('python3',['scripts/character-forge/prepare_upstream_fixture.py','--workspace',out+'/upstream-scout']);
const workspace=out+'/upstream-scout',cache='.cache/character-forge-upstream';
run('python3',['scripts/character-forge/prepare_scout_materials.py','--workspace',workspace,'--cache',cache]);
run('python3',['scripts/character-forge/author_upstream_scout.py','--workspace',workspace,'--cache',cache]);
run('python3',['scripts/character-forge/scout_setup_evidence.py','--workspace',workspace,'--cache',cache]);
run('python3',['packages/assets/forge/upstream_workspace.py','run','--workspace',workspace,'--entry','forge/stage3_build/generate_threejs_factory.py','--','object-sculpt-spec.json','--pass-id','blockout','--out','build/blockout.ts']);
run('python3',['packages/assets/forge/upstream_workspace.py','mark','--workspace',workspace,'--','build-current-pass','--evidence','build/blockout.ts']);
run('npm',['ci','--ignore-scripts']);
run('npx',['playwright','install','--with-deps','chromium']);
run('node',['scripts/character-forge/render_upstream.mjs',workspace,'blockout']);
run('python3',['packages/assets/forge/upstream_workspace.py','mark','--workspace',workspace,'--','render-capture','--evidence','review/blockout/render-receipt.json']);
run('python3',['scripts/character-forge/review_upstream.py','--workspace',workspace,'--cache',cache,'--pass-id','blockout']);
run('python3',['scripts/character-forge/apply_visual_review.py','--workspace',workspace,'--cache',cache,'--review','scripts/character-forge/fixtures/upstream-scout-blockout-r2-review.json']);
run('python3',['scripts/character-forge/author_scout_structural.py','--workspace',workspace,'--cache',cache]);
run('python3',['packages/assets/forge/upstream_workspace.py','run','--workspace',workspace,'--entry','forge/stage3_build/generate_threejs_factory.py','--','object-sculpt-spec.json','--pass-id','structural-pass','--out','build/structural-pass.ts']);
run('python3',['packages/assets/forge/upstream_workspace.py','mark','--workspace',workspace,'--','build-current-pass','--evidence','build/structural-pass.ts']);
run('node',['scripts/character-forge/render_upstream.mjs',workspace,'structural-pass']);
run('python3',['packages/assets/forge/upstream_workspace.py','mark','--workspace',workspace,'--','render-capture','--evidence','review/structural-pass/render-receipt.json']);
run('python3',['scripts/character-forge/review_upstream.py','--workspace',workspace,'--cache',cache,'--pass-id','structural-pass']);
const lock=JSON.parse(readFileSync('package-lock.json','utf8')).packages['node_modules/three'];
if(!/^https:\/\/registry\.npmjs\.org\/three\/-\/three-[0-9.]+\.tgz$/.test(lock.resolved))throw new Error('Unexpected Three.js source');
const response=await fetch(lock.resolved);if(!response.ok)throw new Error(`Three.js download failed: ${response.status}`);
const data=Buffer.from(await response.arrayBuffer()),integrity='sha512-'+createHash('sha512').update(data).digest('base64');
if(integrity!==lock.integrity)throw new Error('Three.js lock integrity mismatch');
writeFileSync(out+'/three.tgz',data);
writeFileSync(out+'/capability-probe.json',JSON.stringify({head:process.env.HEAD_SHA,stage:'authoring-materialization',three:lock,notVisualValidation:true}));
