import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,readdirSync} from 'node:fs';
import {manifest} from '../model-manifest.mjs';
import {WAVES,SKILLS,BLESSINGS,freshStats,waveEnemies,seededRandom,distance,clamp,clock,chooseAutoBlessing} from '../src/domain/rules.js';
test('five finite waves, exactly one boss, and a reachable end',()=>{assert.equal(WAVES.length,5);assert.equal(WAVES.flatMap((_,i)=>waveEnemies(i+1)).filter(t=>t==='boss').length,1);assert.equal(WAVES.reduce((n,w)=>n+w.count,0),73);assert.throws(()=>waveEnemies(0));});
test('three distinct skills have positive bounded cooldowns',()=>{assert.equal(SKILLS.length,3);for(const s of SKILLS){assert.ok(s.cooldown>0);assert.ok(s.damage>0);assert.ok(s.radius>0);}});
test('upgrades compose and healing never lowers maximum health',()=>{const s=freshStats();BLESSINGS.find(b=>b.id==='edge').apply(s);assert.equal(s.damage,1.25);BLESSINGS.find(b=>b.id==='flow').apply(s);assert.equal(s.cooldown,.8);s.hp=1;assert.equal(chooseAutoBlessing(s),'blood');BLESSINGS.find(b=>b.id==='blood').apply(s);assert.equal(s.hp,390);assert.equal(s.maxHp,390);});
test('seeded random replay is reproducible and bounds are correct',()=>{const a=seededRandom(31),b=seededRandom(31);for(let i=0;i<100;i++){const v=a();assert.equal(v,b());assert.ok(v>=0&&v<1);}assert.equal(distance({x:0,z:0},{x:3,z:4}),5);assert.equal(clamp(-5,0,2),0);assert.equal(clock(125),'02:05');});
test('all model provenance is pinned, hashed and explicitly licensed',()=>{assert.equal(manifest.length,33);for(const a of manifest){assert.equal(a.license,'CC0-1.0');assert.match(a.sha256,/^[a-f\d]{64}$/);assert.match(a.revision,/^[a-f\d]{40}$/);assert.ok(a.repository.startsWith('https://github.com/KayKit-Game-Assets/'));assert.ok(a.bytes>0);}});
test('no original procedural 3D models or primitive fallback',()=>{for(const file of readdirSync(new URL('../src/adapters',import.meta.url))){if(!file.endsWith('.js'))continue;const code=readFileSync(new URL('../src/adapters/'+file,import.meta.url),'utf8');assert.doesNotMatch(code,/new\s+(?:THREE\.)?(?:Box|Sphere|Cone|Cylinder|Plane|Torus|Capsule|Extrude|Lathe|Buffer)Geometry\s*\(/);}});
