import {chromium} from 'playwright';import{writeFile,mkdir}from'node:fs/promises';
const out=process.env.EVIDENCE_DIR,base='https://soul-lineage-rinne-dev.c-okamoto.workers.dev/';await mkdir(out,{recursive:true});const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage']});const context=await browser.newContext({viewport:{width:1280,height:800},locale:'ja-JP',storageState:process.env.PRIOR_STATE,recordVideo:{dir:out+'/video',size:{width:1280,height:800}}});const page=await context.newPage(),start=Date.now(),events=[],actions=[],notes=[];page.setDefaultTimeout(5000);const pause=ms=>page.waitForTimeout(ms);page.on('pageerror',e=>events.push(String(e)));page.on('response',r=>{if(r.status()>=400)events.push({url:r.url(),status:r.status()});});
async function snap(name){await pause(350);let j=await page.evaluate(()=>({text:document.body.innerText,storage:{...localStorage},canvas:{...document.querySelector('#game')?.dataset},elements:[...document.querySelectorAll('button,input,select')].filter(e=>e.getBoundingClientRect().width&&e.getBoundingClientRect().height).map(e=>({text:e.innerText,id:e.id,value:e.value,data:{...e.dataset},disabled:e.disabled,rect:e.getBoundingClientRect().toJSON()}))}));j.elapsedMs=Date.now()-start;await writeFile(out+'/'+name+'.json',JSON.stringify(j,null,2));console.log('OBS',name,j.text);await pause(700);}
async function tap(sel){const l=page.locator(sel).first();if(!await l.count())return false;const b=await l.boundingBox();if(!b?.width||!b?.height)return false;await page.mouse.click(b.x+b.width/2,b.y+b.height/2);actions.push({tap:sel,at:Date.now()-start});await pause(350);return true;}
async function close(){if(!await tap('[data-book-action="close"]'))await tap('button[data-close]');}
async function state(){return page.evaluate(()=>{for(const k of Object.keys(localStorage))if(k.endsWith(':life-v2'))try{return JSON.parse(localStorage.getItem(k));}catch{}return null;});}
async function go(tx,tz,label,max=6){let old;for(let i=0;i<max;i++){let s=await state();if(!s||s.ended||s.down||s.interior)break;let dx=tx-s.position.x,dz=tz-s.position.z,d=Math.hypot(dx,dz);if(d<1.4)break;let ax=(.81*dx-.587*dz)/d,ay=(.587*dx+.81*dz)/d;if(old&&Math.hypot(s.position.x-old.x,s.position.z-old.z)<.2)[ax,ay]=[-ay,ax];old={...s.position};await page.mouse.move(560,440);await page.mouse.down();await page.mouse.move(560+ax*90,440+ay*90,{steps:10});await pause(Math.min(2300,Math.max(450,d/4*750)));await page.mouse.up();await pause(2700);await snap(label+'-'+i);} }
async function safe(n,fn){try{await fn();}catch(e){notes.push({n,error:String(e)});await snap('error-'+n).catch(()=>{});}}
try{
 await writeFile(out+'/version-before.json',await(await context.request.get(base+'version.json')).text());await page.goto(base,{waitUntil:'domcontentloaded',timeout:60000});await pause(4500);await tap('#soul-brand-boot');await pause(1800);await tap('#soul-brand-boot');await pause(1500);await page.mouse.click(100,160);await page.waitForFunction(()=>{const n=document.querySelector('.title-actions');return n&&!n.inert;},{},{timeout:30000});await tap('#continue-life');await snap('01-family');await tap('[data-family-action="continue"]');await page.locator('#game[data-runtime="active"]').waitFor({state:'attached',timeout:40000});await snap('02-resume');
 await tap('[data-menu]');await tap('[data-record]');await tap('[data-inspiration-tab="life"]');await snap('03-life-clock');const rate20=page.getByRole('button',{name:'20×',exact:true});await rate20.click({timeout:6000});await pause(27000);await snap('04-age-after-reading');await page.getByRole('button',{name:'1×',exact:true}).click();await snap('05-life-clock-restored');await close();await snap('06-adult-world');
 await safe('manor',async()=>{await go(-13,-1,'07-manor',5);await snap('08-manor-entrance');await tap('[data-action]');await snap('09-manor-action');await close();});
 await safe('battle',async()=>{await go(-4,-12,'10-road',5);await go(-4,-27,'11-gate',7);await go(0,-31,'12-contact',5);for(let i=0;i<5;i++){await pause(2500);await snap('13-combat-'+i);}await tap('[data-body]');await snap('14-body-after');await close();});
 await safe('record-final',async()=>{await tap('[data-menu]');await tap('[data-record]');await tap('[data-inspiration-tab="life"]');await snap('15-life-traces');await tap('[data-inspiration-tab="lineage"]');await snap('16-lineage');await close();});
 await writeFile(out+'/storage-state.json',JSON.stringify(await context.storageState(),null,2));await writeFile(out+'/version-after.json',await(await context.request.get(base+'version.json')).text());
}catch(e){notes.push({fatal:String(e.stack||e)});await snap('fatal').catch(()=>{});}
finally{await writeFile(out+'/diagnostics.json',JSON.stringify({events,actions,notes,start},null,2));await context.close();await browser.close();}
