import {chromium} from 'playwright';import {writeFile,mkdir} from 'node:fs/promises';
const out=process.env.EVIDENCE_DIR,base='https://soul-lineage-rinne-dev.c-okamoto.workers.dev/';await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--use-angle=swiftshader','--enable-unsafe-swiftshader','--disable-dev-shm-usage','--disable-background-timer-throttling','--disable-renderer-backgrounding']});
const context=await browser.newContext({viewport:{width:1280,height:800},locale:'ja-JP',recordVideo:{dir:out+'/video',size:{width:1280,height:800}}});const page=await context.newPage(),start=Date.now(),events=[],notes=[],actions=[];page.setDefaultTimeout(5000);
page.on('pageerror',e=>events.push({type:'pageerror',text:String(e)}));page.on('response',r=>{if(r.status()>=400)events.push({type:'http',status:r.status(),url:r.url()});});
const pause=ms=>page.waitForTimeout(ms);
async function snap(name){await pause(400);const data=await page.evaluate(()=>({at:new Date().toISOString(),text:document.body.innerText,url:location.href,game:{...document.querySelector('#game-screen')?.dataset},canvas:{...document.querySelector('#game')?.dataset},tutorial:{...document.querySelector('#rinneFirstRunGuide')?.dataset},storage:{...localStorage},elements:[...document.querySelectorAll('button,input,select,dialog,.rb-detail-copy,.rb-tile,.family-memory-presence')].filter(e=>e.getBoundingClientRect().width&&e.getBoundingClientRect().height).map(e=>{const s=getComputedStyle(e);return{id:e.id,tag:e.tagName,text:e.innerText,value:e.value,class:e.className,data:{...e.dataset},label:e.getAttribute('aria-label'),disabled:e.disabled,rect:e.getBoundingClientRect().toJSON(),style:{opacity:s.opacity,visibility:s.visibility,fontSize:s.fontSize,animation:s.animationName}};})}));data.elapsedMs=Date.now()-start;await writeFile(out+'/'+name+'.json',JSON.stringify(data,null,2));console.log('OBSERVE',name,JSON.stringify({text:data.text,tutorial:data.tutorial,elapsedMs:data.elapsedMs}));await pause(700);}
async function tap(sel){const l=page.locator(sel).first();if(!await l.count())return false;const b=await l.boundingBox();if(!b||b.width<1||b.height<1)return false;await page.mouse.click(b.x+b.width/2,b.y+b.height/2);actions.push({tap:sel,at:Date.now()-start});await pause(350);return true;}
async function close(){if(!await tap('[data-book-action="close"]'))await tap('button[data-close]');}
async function safe(name,fn){try{await fn();}catch(e){notes.push({name,error:String(e)});await snap('error-'+name).catch(()=>{});}}
async function drag(dx,dy,ms){await page.mouse.move(560,440);await page.mouse.down();await page.mouse.move(560+dx,440+dy,{steps:12});await pause(ms);await page.mouse.up();actions.push({drag:[dx,dy,ms],at:Date.now()-start});}
async function state(){return page.evaluate(()=>{for(const k of Object.keys(localStorage)){if(k.endsWith(':life-v2')){try{return JSON.parse(localStorage.getItem(k));}catch{}}}return null;});}
async function go(tx,tz,label,max=10){let old=null;for(let i=0;i<max;i++){const s=await state();if(!s||s.ended||s.down||s.zone!=='village'||s.interior)break;const dx=tx-s.position.x,dz=tz-s.position.z,d=Math.hypot(dx,dz);if(d<1.35)break;let ax=(.810*dx-.587*dz)/d,ay=(.587*dx+.810*dz)/d;if(old&&Math.hypot(s.position.x-old.x,s.position.z-old.z)<.15){[ax,ay]=[-ay,ax];actions.push({detour:label});}old={...s.position};await drag(ax*90,ay*90,Math.min(2500,Math.max(700,d/4*900)));await pause(3000);if(i%2===0)await snap('nav-'+label+'-'+i);}await snap('arrive-'+label);}
try{
 await writeFile(out+'/version-before.json',await(await context.request.get(base+'version.json')).text());await page.goto(base,{waitUntil:'domcontentloaded',timeout:60000});await pause(4500);await tap('#soul-brand-boot');await pause(1800);await tap('#soul-brand-boot');await pause(1500);await page.mouse.click(100,160);await page.waitForFunction(()=>{const a=document.querySelector('.title-actions');return a&&!a.inert;},{},{timeout:30000});
 await tap('#open-settings');await snap('01-settings-on');await tap('#title-motion-toggle');await snap('02-settings-off');await tap('#close-settings');await tap('#new-life');await pause(800);await snap('03-question-motion-off');
 for(let i=0;i<3;i++){await tap('[data-memory-current]');await pause(850);await snap('04-answer-'+i);}await tap('[data-origin-confirm]');await page.locator('#game[data-runtime="active"]').waitFor({state:'attached',timeout:40000});await snap('05-newborn');
 await tap('.rinneFirstRunStart');await drag(170,-70,1800);await pause(600);await snap('06-tutorial-move');await tap('[data-heart]');await pause(1200);await snap('07-tutorial-heart');await close();await tap('.rinneFirstRunSkip');await snap('08-tutorial-skipped');
 await tap('#clock-rate');await tap('#clock-rate');await tap('#clock-rate');await pause(13000);await snap('09-child');await pause(11000);await tap('#clock-rate');await snap('10-age-clock1');
 for(const [name,sel]of[['heart','[data-heart]'],['technique','[data-techniques]'],['body','button[data-body]'],['items','[data-items]']])await safe(name,async()=>{await close();await tap(sel);await snap('11-'+name+'-desktop');await page.setViewportSize({width:393,height:852});await snap('12-'+name+'-phone');await page.setViewportSize({width:852,height:393});await snap('13-'+name+'-landscape');await page.setViewportSize({width:1280,height:800});await close();});
 await safe('search',async()=>{await tap('[data-heart]');await tap('[data-book-search]');await page.keyboard.type('test',{delay:150});await snap('14-search-test');await close();});
 await safe('map',async()=>{await tap('[data-menu]');await tap('[data-map]');await snap('15-map');await page.setViewportSize({width:393,height:852});await snap('16-map-phone');await page.setViewportSize({width:1280,height:800});await close();});
 await safe('record',async()=>{await tap('[data-menu]');await tap('[data-record]');await snap('17-record');await close();});await safe('speech',async()=>{await tap('.speech-fan-toggle');await snap('18-speech');await tap('.speech-phrase');await snap('19-speech-result');});
 await safe('camera',async()=>{const s=page.locator('#camera-position');await s.focus();await page.keyboard.press('End');await snap('20-camera-far');await page.keyboard.press('Home');await snap('21-camera-near');for(let i=0;i<50;i++)await page.keyboard.press('ArrowUp');});
 await safe('village-combat',async()=>{await close();await tap('#game');await go(-5,-10,'south-road',8);await go(-5,-26,'outside-gate',10);await go(0,-31,'village-battle',6);for(let i=0;i<5;i++){await pause(3500);await snap('22-combat-'+i);}await tap('[data-body]');await snap('23-after-combat-body');await close();});
 await safe('rebirth-or-save',async()=>{const s=await state();if(s?.ended){await snap('24-life-end');await tap('[data-family-action="rebirth"]');await pause(2000);await snap('25-rebirth');}else{await tap('#back-title');await pause(1000);await tap('#continue-life');await snap('24-family-resume');await tap('[data-family-action="continue"]');await pause(1000);await snap('25-resumed');}});
 await writeFile(out+'/storage-state.json',JSON.stringify(await context.storageState(),null,2));await writeFile(out+'/version-after.json',await(await context.request.get(base+'version.json')).text());
}catch(e){notes.push({fatal:String(e.stack||e)});await snap('fatal').catch(()=>{});}
finally{await writeFile(out+'/diagnostics.json',JSON.stringify({events,notes,actions,start},null,2));await context.close();await browser.close();}
